// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/openchoreo/openchoreo/internal/openchoreo-api/api/gen"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteDeploymentPipeline provides a mock function with given fields: ctx, namespaceName, deploymentPipelineName
func (_m *MockClient) DeleteDeploymentPipeline(ctx context.Context, namespaceName string, deploymentPipelineName string) error {
	ret := _m.Called(ctx, namespaceName, deploymentPipelineName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDeploymentPipeline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, deploymentPipelineName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeleteDeploymentPipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDeploymentPipeline'
type MockClient_DeleteDeploymentPipeline_Call struct {
	*mock.Call
}

// DeleteDeploymentPipeline is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - deploymentPipelineName string
func (_e *MockClient_Expecter) DeleteDeploymentPipeline(ctx interface{}, namespaceName interface{}, deploymentPipelineName interface{}) *MockClient_DeleteDeploymentPipeline_Call {
	return &MockClient_DeleteDeploymentPipeline_Call{Call: _e.mock.On("DeleteDeploymentPipeline", ctx, namespaceName, deploymentPipelineName)}
}

func (_c *MockClient_DeleteDeploymentPipeline_Call) Run(run func(ctx context.Context, namespaceName string, deploymentPipelineName string)) *MockClient_DeleteDeploymentPipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_DeleteDeploymentPipeline_Call) Return(_a0 error) *MockClient_DeleteDeploymentPipeline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeleteDeploymentPipeline_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_DeleteDeploymentPipeline_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeploymentPipeline provides a mock function with given fields: ctx, namespaceName, deploymentPipelineName
func (_m *MockClient) GetDeploymentPipeline(ctx context.Context, namespaceName string, deploymentPipelineName string) (*gen.DeploymentPipeline, error) {
	ret := _m.Called(ctx, namespaceName, deploymentPipelineName)

	if len(ret) == 0 {
		panic("no return value specified for GetDeploymentPipeline")
	}

	var r0 *gen.DeploymentPipeline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.DeploymentPipeline, error)); ok {
		return rf(ctx, namespaceName, deploymentPipelineName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.DeploymentPipeline); ok {
		r0 = rf(ctx, namespaceName, deploymentPipelineName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.DeploymentPipeline)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, deploymentPipelineName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetDeploymentPipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeploymentPipeline'
type MockClient_GetDeploymentPipeline_Call struct {
	*mock.Call
}

// GetDeploymentPipeline is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - deploymentPipelineName string
func (_e *MockClient_Expecter) GetDeploymentPipeline(ctx interface{}, namespaceName interface{}, deploymentPipelineName interface{}) *MockClient_GetDeploymentPipeline_Call {
	return &MockClient_GetDeploymentPipeline_Call{Call: _e.mock.On("GetDeploymentPipeline", ctx, namespaceName, deploymentPipelineName)}
}

func (_c *MockClient_GetDeploymentPipeline_Call) Run(run func(ctx context.Context, namespaceName string, deploymentPipelineName string)) *MockClient_GetDeploymentPipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetDeploymentPipeline_Call) Return(_a0 *gen.DeploymentPipeline, _a1 error) *MockClient_GetDeploymentPipeline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetDeploymentPipeline_Call) RunAndReturn(run func(context.Context, string, string) (*gen.DeploymentPipeline, error)) *MockClient_GetDeploymentPipeline_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeploymentPipelines provides a mock function with given fields: ctx, namespaceName, params
func (_m *MockClient) ListDeploymentPipelines(ctx context.Context, namespaceName string, params *gen.ListDeploymentPipelinesParams) (*gen.DeploymentPipelineList, error) {
	ret := _m.Called(ctx, namespaceName, params)

	if len(ret) == 0 {
		panic("no return value specified for ListDeploymentPipelines")
	}

	var r0 *gen.DeploymentPipelineList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListDeploymentPipelinesParams) (*gen.DeploymentPipelineList, error)); ok {
		return rf(ctx, namespaceName, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListDeploymentPipelinesParams) *gen.DeploymentPipelineList); ok {
		r0 = rf(ctx, namespaceName, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.DeploymentPipelineList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *gen.ListDeploymentPipelinesParams) error); ok {
		r1 = rf(ctx, namespaceName, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListDeploymentPipelines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeploymentPipelines'
type MockClient_ListDeploymentPipelines_Call struct {
	*mock.Call
}

// ListDeploymentPipelines is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - params *gen.ListDeploymentPipelinesParams
func (_e *MockClient_Expecter) ListDeploymentPipelines(ctx interface{}, namespaceName interface{}, params interface{}) *MockClient_ListDeploymentPipelines_Call {
	return &MockClient_ListDeploymentPipelines_Call{Call: _e.mock.On("ListDeploymentPipelines", ctx, namespaceName, params)}
}

func (_c *MockClient_ListDeploymentPipelines_Call) Run(run func(ctx context.Context, namespaceName string, params *gen.ListDeploymentPipelinesParams)) *MockClient_ListDeploymentPipelines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*gen.ListDeploymentPipelinesParams))
	})
	return _c
}

func (_c *MockClient_ListDeploymentPipelines_Call) Return(_a0 *gen.DeploymentPipelineList, _a1 error) *MockClient_ListDeploymentPipelines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListDeploymentPipelines_Call) RunAndReturn(run func(context.Context, string, *gen.ListDeploymentPipelinesParams) (*gen.DeploymentPipelineList, error)) *MockClient_ListDeploymentPipelines_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
