// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/openchoreo/openchoreo/internal/openchoreo-api/api/gen"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteClusterWorkflowPlane provides a mock function with given fields: ctx, clusterWorkflowPlaneName
func (_m *MockClient) DeleteClusterWorkflowPlane(ctx context.Context, clusterWorkflowPlaneName string) error {
	ret := _m.Called(ctx, clusterWorkflowPlaneName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClusterWorkflowPlane")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, clusterWorkflowPlaneName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeleteClusterWorkflowPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClusterWorkflowPlane'
type MockClient_DeleteClusterWorkflowPlane_Call struct {
	*mock.Call
}

// DeleteClusterWorkflowPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterWorkflowPlaneName string
func (_e *MockClient_Expecter) DeleteClusterWorkflowPlane(ctx interface{}, clusterWorkflowPlaneName interface{}) *MockClient_DeleteClusterWorkflowPlane_Call {
	return &MockClient_DeleteClusterWorkflowPlane_Call{Call: _e.mock.On("DeleteClusterWorkflowPlane", ctx, clusterWorkflowPlaneName)}
}

func (_c *MockClient_DeleteClusterWorkflowPlane_Call) Run(run func(ctx context.Context, clusterWorkflowPlaneName string)) *MockClient_DeleteClusterWorkflowPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_DeleteClusterWorkflowPlane_Call) Return(_a0 error) *MockClient_DeleteClusterWorkflowPlane_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeleteClusterWorkflowPlane_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_DeleteClusterWorkflowPlane_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterWorkflowPlane provides a mock function with given fields: ctx, clusterWorkflowPlaneName
func (_m *MockClient) GetClusterWorkflowPlane(ctx context.Context, clusterWorkflowPlaneName string) (*gen.ClusterWorkflowPlane, error) {
	ret := _m.Called(ctx, clusterWorkflowPlaneName)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterWorkflowPlane")
	}

	var r0 *gen.ClusterWorkflowPlane
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gen.ClusterWorkflowPlane, error)); ok {
		return rf(ctx, clusterWorkflowPlaneName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gen.ClusterWorkflowPlane); ok {
		r0 = rf(ctx, clusterWorkflowPlaneName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ClusterWorkflowPlane)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterWorkflowPlaneName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetClusterWorkflowPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterWorkflowPlane'
type MockClient_GetClusterWorkflowPlane_Call struct {
	*mock.Call
}

// GetClusterWorkflowPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterWorkflowPlaneName string
func (_e *MockClient_Expecter) GetClusterWorkflowPlane(ctx interface{}, clusterWorkflowPlaneName interface{}) *MockClient_GetClusterWorkflowPlane_Call {
	return &MockClient_GetClusterWorkflowPlane_Call{Call: _e.mock.On("GetClusterWorkflowPlane", ctx, clusterWorkflowPlaneName)}
}

func (_c *MockClient_GetClusterWorkflowPlane_Call) Run(run func(ctx context.Context, clusterWorkflowPlaneName string)) *MockClient_GetClusterWorkflowPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetClusterWorkflowPlane_Call) Return(_a0 *gen.ClusterWorkflowPlane, _a1 error) *MockClient_GetClusterWorkflowPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetClusterWorkflowPlane_Call) RunAndReturn(run func(context.Context, string) (*gen.ClusterWorkflowPlane, error)) *MockClient_GetClusterWorkflowPlane_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusterWorkflowPlanes provides a mock function with given fields: ctx, params
func (_m *MockClient) ListClusterWorkflowPlanes(ctx context.Context, params *gen.ListClusterWorkflowPlanesParams) (*gen.ClusterWorkflowPlaneList, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListClusterWorkflowPlanes")
	}

	var r0 *gen.ClusterWorkflowPlaneList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ListClusterWorkflowPlanesParams) (*gen.ClusterWorkflowPlaneList, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ListClusterWorkflowPlanesParams) *gen.ClusterWorkflowPlaneList); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ClusterWorkflowPlaneList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.ListClusterWorkflowPlanesParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListClusterWorkflowPlanes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusterWorkflowPlanes'
type MockClient_ListClusterWorkflowPlanes_Call struct {
	*mock.Call
}

// ListClusterWorkflowPlanes is a helper method to define mock.On call
//   - ctx context.Context
//   - params *gen.ListClusterWorkflowPlanesParams
func (_e *MockClient_Expecter) ListClusterWorkflowPlanes(ctx interface{}, params interface{}) *MockClient_ListClusterWorkflowPlanes_Call {
	return &MockClient_ListClusterWorkflowPlanes_Call{Call: _e.mock.On("ListClusterWorkflowPlanes", ctx, params)}
}

func (_c *MockClient_ListClusterWorkflowPlanes_Call) Run(run func(ctx context.Context, params *gen.ListClusterWorkflowPlanesParams)) *MockClient_ListClusterWorkflowPlanes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gen.ListClusterWorkflowPlanesParams))
	})
	return _c
}

func (_c *MockClient_ListClusterWorkflowPlanes_Call) Return(_a0 *gen.ClusterWorkflowPlaneList, _a1 error) *MockClient_ListClusterWorkflowPlanes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListClusterWorkflowPlanes_Call) RunAndReturn(run func(context.Context, *gen.ListClusterWorkflowPlanesParams) (*gen.ClusterWorkflowPlaneList, error)) *MockClient_ListClusterWorkflowPlanes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
