with-expecter: true
filename: "{{.InterfaceName | lower}}.go"
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
structname: "{{.InterfaceName}}"
packages:
  github.com/openchoreo/openchoreo/internal/openchoreo-api/services/authz:
    interfaces:
      Service:
  github.com/openchoreo/openchoreo/internal/occ/cmd/clustertrait:
    interfaces:
      Client:
  github.com/openchoreo/openchoreo/internal/occ/cmd/clustercomponenttype:
    interfaces:
      Client:
  github.com/openchoreo/openchoreo/internal/occ/cmd/componenttype:
    interfaces:
      Client:
  github.com/openchoreo/openchoreo/internal/occ/cmd/trait:
    interfaces:
      Client:
  github.com/openchoreo/openchoreo/internal/openchoreo-api/services/gitsecret:
    interfaces:
      Service:
  github.com/openchoreo/openchoreo/internal/authz/core:
    interfaces:
      PDP:
