with-expecter: true
filename: "{{.InterfaceName | lower}}.go"
dir: "{{.InterfaceDir}}/mocks"
outpkg: mocks
structname: "{{.InterfaceName}}"
packages:
  github.com/openchoreo/openchoreo/internal/openchoreo-api/services/authz:
    interfaces:
      Service:
  github.com/openchoreo/openchoreo/internal/occ/cmd/clustertrait:
    interfaces:
      Client:
