// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/openchoreo/openchoreo/internal/openchoreo-api/api/gen"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteTrait provides a mock function with given fields: ctx, namespaceName, traitName
func (_m *MockClient) DeleteTrait(ctx context.Context, namespaceName string, traitName string) error {
	ret := _m.Called(ctx, namespaceName, traitName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTrait")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, traitName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeleteTrait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTrait'
type MockClient_DeleteTrait_Call struct {
	*mock.Call
}

// DeleteTrait is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - traitName string
func (_e *MockClient_Expecter) DeleteTrait(ctx interface{}, namespaceName interface{}, traitName interface{}) *MockClient_DeleteTrait_Call {
	return &MockClient_DeleteTrait_Call{Call: _e.mock.On("DeleteTrait", ctx, namespaceName, traitName)}
}

func (_c *MockClient_DeleteTrait_Call) Run(run func(ctx context.Context, namespaceName string, traitName string)) *MockClient_DeleteTrait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_DeleteTrait_Call) Return(_a0 error) *MockClient_DeleteTrait_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeleteTrait_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_DeleteTrait_Call {
	_c.Call.Return(run)
	return _c
}

// GetTrait provides a mock function with given fields: ctx, namespaceName, traitName
func (_m *MockClient) GetTrait(ctx context.Context, namespaceName string, traitName string) (*gen.Trait, error) {
	ret := _m.Called(ctx, namespaceName, traitName)

	if len(ret) == 0 {
		panic("no return value specified for GetTrait")
	}

	var r0 *gen.Trait
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.Trait, error)); ok {
		return rf(ctx, namespaceName, traitName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.Trait); ok {
		r0 = rf(ctx, namespaceName, traitName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Trait)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, traitName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetTrait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTrait'
type MockClient_GetTrait_Call struct {
	*mock.Call
}

// GetTrait is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - traitName string
func (_e *MockClient_Expecter) GetTrait(ctx interface{}, namespaceName interface{}, traitName interface{}) *MockClient_GetTrait_Call {
	return &MockClient_GetTrait_Call{Call: _e.mock.On("GetTrait", ctx, namespaceName, traitName)}
}

func (_c *MockClient_GetTrait_Call) Run(run func(ctx context.Context, namespaceName string, traitName string)) *MockClient_GetTrait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetTrait_Call) Return(_a0 *gen.Trait, _a1 error) *MockClient_GetTrait_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetTrait_Call) RunAndReturn(run func(context.Context, string, string) (*gen.Trait, error)) *MockClient_GetTrait_Call {
	_c.Call.Return(run)
	return _c
}

// ListTraits provides a mock function with given fields: ctx, namespaceName, params
func (_m *MockClient) ListTraits(ctx context.Context, namespaceName string, params *gen.ListTraitsParams) (*gen.TraitList, error) {
	ret := _m.Called(ctx, namespaceName, params)

	if len(ret) == 0 {
		panic("no return value specified for ListTraits")
	}

	var r0 *gen.TraitList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListTraitsParams) (*gen.TraitList, error)); ok {
		return rf(ctx, namespaceName, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListTraitsParams) *gen.TraitList); ok {
		r0 = rf(ctx, namespaceName, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.TraitList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *gen.ListTraitsParams) error); ok {
		r1 = rf(ctx, namespaceName, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListTraits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTraits'
type MockClient_ListTraits_Call struct {
	*mock.Call
}

// ListTraits is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - params *gen.ListTraitsParams
func (_e *MockClient_Expecter) ListTraits(ctx interface{}, namespaceName interface{}, params interface{}) *MockClient_ListTraits_Call {
	return &MockClient_ListTraits_Call{Call: _e.mock.On("ListTraits", ctx, namespaceName, params)}
}

func (_c *MockClient_ListTraits_Call) Run(run func(ctx context.Context, namespaceName string, params *gen.ListTraitsParams)) *MockClient_ListTraits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*gen.ListTraitsParams))
	})
	return _c
}

func (_c *MockClient_ListTraits_Call) Return(_a0 *gen.TraitList, _a1 error) *MockClient_ListTraits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListTraits_Call) RunAndReturn(run func(context.Context, string, *gen.ListTraitsParams) (*gen.TraitList, error)) *MockClient_ListTraits_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
