// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/openchoreo/openchoreo/internal/openchoreo-api/api/gen"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteNamespaceRole provides a mock function with given fields: ctx, namespaceName, name
func (_m *MockClient) DeleteNamespaceRole(ctx context.Context, namespaceName string, name string) error {
	ret := _m.Called(ctx, namespaceName, name)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNamespaceRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, name)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeleteNamespaceRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNamespaceRole'
type MockClient_DeleteNamespaceRole_Call struct {
	*mock.Call
}

// DeleteNamespaceRole is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - name string
func (_e *MockClient_Expecter) DeleteNamespaceRole(ctx interface{}, namespaceName interface{}, name interface{}) *MockClient_DeleteNamespaceRole_Call {
	return &MockClient_DeleteNamespaceRole_Call{Call: _e.mock.On("DeleteNamespaceRole", ctx, namespaceName, name)}
}

func (_c *MockClient_DeleteNamespaceRole_Call) Run(run func(ctx context.Context, namespaceName string, name string)) *MockClient_DeleteNamespaceRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_DeleteNamespaceRole_Call) Return(_a0 error) *MockClient_DeleteNamespaceRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeleteNamespaceRole_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_DeleteNamespaceRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespaceRole provides a mock function with given fields: ctx, namespaceName, name
func (_m *MockClient) GetNamespaceRole(ctx context.Context, namespaceName string, name string) (*gen.AuthzRole, error) {
	ret := _m.Called(ctx, namespaceName, name)

	if len(ret) == 0 {
		panic("no return value specified for GetNamespaceRole")
	}

	var r0 *gen.AuthzRole
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.AuthzRole, error)); ok {
		return rf(ctx, namespaceName, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.AuthzRole); ok {
		r0 = rf(ctx, namespaceName, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.AuthzRole)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetNamespaceRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespaceRole'
type MockClient_GetNamespaceRole_Call struct {
	*mock.Call
}

// GetNamespaceRole is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - name string
func (_e *MockClient_Expecter) GetNamespaceRole(ctx interface{}, namespaceName interface{}, name interface{}) *MockClient_GetNamespaceRole_Call {
	return &MockClient_GetNamespaceRole_Call{Call: _e.mock.On("GetNamespaceRole", ctx, namespaceName, name)}
}

func (_c *MockClient_GetNamespaceRole_Call) Run(run func(ctx context.Context, namespaceName string, name string)) *MockClient_GetNamespaceRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetNamespaceRole_Call) Return(_a0 *gen.AuthzRole, _a1 error) *MockClient_GetNamespaceRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetNamespaceRole_Call) RunAndReturn(run func(context.Context, string, string) (*gen.AuthzRole, error)) *MockClient_GetNamespaceRole_Call {
	_c.Call.Return(run)
	return _c
}

// ListNamespaceRoles provides a mock function with given fields: ctx, namespaceName, params
func (_m *MockClient) ListNamespaceRoles(ctx context.Context, namespaceName string, params *gen.ListNamespaceRolesParams) (*gen.AuthzRoleList, error) {
	ret := _m.Called(ctx, namespaceName, params)

	if len(ret) == 0 {
		panic("no return value specified for ListNamespaceRoles")
	}

	var r0 *gen.AuthzRoleList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListNamespaceRolesParams) (*gen.AuthzRoleList, error)); ok {
		return rf(ctx, namespaceName, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListNamespaceRolesParams) *gen.AuthzRoleList); ok {
		r0 = rf(ctx, namespaceName, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.AuthzRoleList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *gen.ListNamespaceRolesParams) error); ok {
		r1 = rf(ctx, namespaceName, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListNamespaceRoles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNamespaceRoles'
type MockClient_ListNamespaceRoles_Call struct {
	*mock.Call
}

// ListNamespaceRoles is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - params *gen.ListNamespaceRolesParams
func (_e *MockClient_Expecter) ListNamespaceRoles(ctx interface{}, namespaceName interface{}, params interface{}) *MockClient_ListNamespaceRoles_Call {
	return &MockClient_ListNamespaceRoles_Call{Call: _e.mock.On("ListNamespaceRoles", ctx, namespaceName, params)}
}

func (_c *MockClient_ListNamespaceRoles_Call) Run(run func(ctx context.Context, namespaceName string, params *gen.ListNamespaceRolesParams)) *MockClient_ListNamespaceRoles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*gen.ListNamespaceRolesParams))
	})
	return _c
}

func (_c *MockClient_ListNamespaceRoles_Call) Return(_a0 *gen.AuthzRoleList, _a1 error) *MockClient_ListNamespaceRoles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListNamespaceRoles_Call) RunAndReturn(run func(context.Context, string, *gen.ListNamespaceRolesParams) (*gen.AuthzRoleList, error)) *MockClient_ListNamespaceRoles_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
