// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	json "encoding/json"

	gen "github.com/openchoreo/openchoreo/internal/openchoreo-api/api/gen"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreateReleaseBinding provides a mock function with given fields: ctx, namespaceName, req
func (_m *MockClient) CreateReleaseBinding(ctx context.Context, namespaceName string, req gen.ReleaseBinding) (*gen.ReleaseBinding, error) {
	ret := _m.Called(ctx, namespaceName, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateReleaseBinding")
	}

	var r0 *gen.ReleaseBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, gen.ReleaseBinding) (*gen.ReleaseBinding, error)); ok {
		return rf(ctx, namespaceName, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, gen.ReleaseBinding) *gen.ReleaseBinding); ok {
		r0 = rf(ctx, namespaceName, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ReleaseBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, gen.ReleaseBinding) error); ok {
		r1 = rf(ctx, namespaceName, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CreateReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReleaseBinding'
type MockClient_CreateReleaseBinding_Call struct {
	*mock.Call
}

// CreateReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - req gen.ReleaseBinding
func (_e *MockClient_Expecter) CreateReleaseBinding(ctx interface{}, namespaceName interface{}, req interface{}) *MockClient_CreateReleaseBinding_Call {
	return &MockClient_CreateReleaseBinding_Call{Call: _e.mock.On("CreateReleaseBinding", ctx, namespaceName, req)}
}

func (_c *MockClient_CreateReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, req gen.ReleaseBinding)) *MockClient_CreateReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(gen.ReleaseBinding))
	})
	return _c
}

func (_c *MockClient_CreateReleaseBinding_Call) Return(_a0 *gen.ReleaseBinding, _a1 error) *MockClient_CreateReleaseBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CreateReleaseBinding_Call) RunAndReturn(run func(context.Context, string, gen.ReleaseBinding) (*gen.ReleaseBinding, error)) *MockClient_CreateReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWorkflowRun provides a mock function with given fields: ctx, namespaceName, req
func (_m *MockClient) CreateWorkflowRun(ctx context.Context, namespaceName string, req gen.WorkflowRun) (*gen.WorkflowRun, error) {
	ret := _m.Called(ctx, namespaceName, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkflowRun")
	}

	var r0 *gen.WorkflowRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, gen.WorkflowRun) (*gen.WorkflowRun, error)); ok {
		return rf(ctx, namespaceName, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, gen.WorkflowRun) *gen.WorkflowRun); ok {
		r0 = rf(ctx, namespaceName, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.WorkflowRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, gen.WorkflowRun) error); ok {
		r1 = rf(ctx, namespaceName, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_CreateWorkflowRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkflowRun'
type MockClient_CreateWorkflowRun_Call struct {
	*mock.Call
}

// CreateWorkflowRun is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - req gen.WorkflowRun
func (_e *MockClient_Expecter) CreateWorkflowRun(ctx interface{}, namespaceName interface{}, req interface{}) *MockClient_CreateWorkflowRun_Call {
	return &MockClient_CreateWorkflowRun_Call{Call: _e.mock.On("CreateWorkflowRun", ctx, namespaceName, req)}
}

func (_c *MockClient_CreateWorkflowRun_Call) Run(run func(ctx context.Context, namespaceName string, req gen.WorkflowRun)) *MockClient_CreateWorkflowRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(gen.WorkflowRun))
	})
	return _c
}

func (_c *MockClient_CreateWorkflowRun_Call) Return(_a0 *gen.WorkflowRun, _a1 error) *MockClient_CreateWorkflowRun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_CreateWorkflowRun_Call) RunAndReturn(run func(context.Context, string, gen.WorkflowRun) (*gen.WorkflowRun, error)) *MockClient_CreateWorkflowRun_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComponent provides a mock function with given fields: ctx, namespaceName, componentName
func (_m *MockClient) DeleteComponent(ctx context.Context, namespaceName string, componentName string) error {
	ret := _m.Called(ctx, namespaceName, componentName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComponent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, componentName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeleteComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComponent'
type MockClient_DeleteComponent_Call struct {
	*mock.Call
}

// DeleteComponent is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentName string
func (_e *MockClient_Expecter) DeleteComponent(ctx interface{}, namespaceName interface{}, componentName interface{}) *MockClient_DeleteComponent_Call {
	return &MockClient_DeleteComponent_Call{Call: _e.mock.On("DeleteComponent", ctx, namespaceName, componentName)}
}

func (_c *MockClient_DeleteComponent_Call) Run(run func(ctx context.Context, namespaceName string, componentName string)) *MockClient_DeleteComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_DeleteComponent_Call) Return(_a0 error) *MockClient_DeleteComponent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeleteComponent_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_DeleteComponent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkflow provides a mock function with given fields: ctx, namespaceName, workflowName
func (_m *MockClient) DeleteWorkflow(ctx context.Context, namespaceName string, workflowName string) error {
	ret := _m.Called(ctx, namespaceName, workflowName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkflow")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, workflowName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeleteWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkflow'
type MockClient_DeleteWorkflow_Call struct {
	*mock.Call
}

// DeleteWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - workflowName string
func (_e *MockClient_Expecter) DeleteWorkflow(ctx interface{}, namespaceName interface{}, workflowName interface{}) *MockClient_DeleteWorkflow_Call {
	return &MockClient_DeleteWorkflow_Call{Call: _e.mock.On("DeleteWorkflow", ctx, namespaceName, workflowName)}
}

func (_c *MockClient_DeleteWorkflow_Call) Run(run func(ctx context.Context, namespaceName string, workflowName string)) *MockClient_DeleteWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_DeleteWorkflow_Call) Return(_a0 error) *MockClient_DeleteWorkflow_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeleteWorkflow_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_DeleteWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRelease provides a mock function with given fields: ctx, namespaceName, componentName, req
func (_m *MockClient) GenerateRelease(ctx context.Context, namespaceName string, componentName string, req gen.GenerateReleaseRequest) (*gen.ComponentRelease, error) {
	ret := _m.Called(ctx, namespaceName, componentName, req)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRelease")
	}

	var r0 *gen.ComponentRelease
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, gen.GenerateReleaseRequest) (*gen.ComponentRelease, error)); ok {
		return rf(ctx, namespaceName, componentName, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, gen.GenerateReleaseRequest) *gen.ComponentRelease); ok {
		r0 = rf(ctx, namespaceName, componentName, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ComponentRelease)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, gen.GenerateReleaseRequest) error); ok {
		r1 = rf(ctx, namespaceName, componentName, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GenerateRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRelease'
type MockClient_GenerateRelease_Call struct {
	*mock.Call
}

// GenerateRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentName string
//   - req gen.GenerateReleaseRequest
func (_e *MockClient_Expecter) GenerateRelease(ctx interface{}, namespaceName interface{}, componentName interface{}, req interface{}) *MockClient_GenerateRelease_Call {
	return &MockClient_GenerateRelease_Call{Call: _e.mock.On("GenerateRelease", ctx, namespaceName, componentName, req)}
}

func (_c *MockClient_GenerateRelease_Call) Run(run func(ctx context.Context, namespaceName string, componentName string, req gen.GenerateReleaseRequest)) *MockClient_GenerateRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(gen.GenerateReleaseRequest))
	})
	return _c
}

func (_c *MockClient_GenerateRelease_Call) Return(_a0 *gen.ComponentRelease, _a1 error) *MockClient_GenerateRelease_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GenerateRelease_Call) RunAndReturn(run func(context.Context, string, string, gen.GenerateReleaseRequest) (*gen.ComponentRelease, error)) *MockClient_GenerateRelease_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterComponentTypeSchema provides a mock function with given fields: ctx, cctName
func (_m *MockClient) GetClusterComponentTypeSchema(ctx context.Context, cctName string) (*json.RawMessage, error) {
	ret := _m.Called(ctx, cctName)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterComponentTypeSchema")
	}

	var r0 *json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*json.RawMessage, error)); ok {
		return rf(ctx, cctName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *json.RawMessage); ok {
		r0 = rf(ctx, cctName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cctName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetClusterComponentTypeSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterComponentTypeSchema'
type MockClient_GetClusterComponentTypeSchema_Call struct {
	*mock.Call
}

// GetClusterComponentTypeSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - cctName string
func (_e *MockClient_Expecter) GetClusterComponentTypeSchema(ctx interface{}, cctName interface{}) *MockClient_GetClusterComponentTypeSchema_Call {
	return &MockClient_GetClusterComponentTypeSchema_Call{Call: _e.mock.On("GetClusterComponentTypeSchema", ctx, cctName)}
}

func (_c *MockClient_GetClusterComponentTypeSchema_Call) Run(run func(ctx context.Context, cctName string)) *MockClient_GetClusterComponentTypeSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetClusterComponentTypeSchema_Call) Return(_a0 *json.RawMessage, _a1 error) *MockClient_GetClusterComponentTypeSchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetClusterComponentTypeSchema_Call) RunAndReturn(run func(context.Context, string) (*json.RawMessage, error)) *MockClient_GetClusterComponentTypeSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterDataPlane provides a mock function with given fields: ctx, cdpName
func (_m *MockClient) GetClusterDataPlane(ctx context.Context, cdpName string) (*gen.ClusterDataPlane, error) {
	ret := _m.Called(ctx, cdpName)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterDataPlane")
	}

	var r0 *gen.ClusterDataPlane
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gen.ClusterDataPlane, error)); ok {
		return rf(ctx, cdpName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gen.ClusterDataPlane); ok {
		r0 = rf(ctx, cdpName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ClusterDataPlane)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cdpName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetClusterDataPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterDataPlane'
type MockClient_GetClusterDataPlane_Call struct {
	*mock.Call
}

// GetClusterDataPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - cdpName string
func (_e *MockClient_Expecter) GetClusterDataPlane(ctx interface{}, cdpName interface{}) *MockClient_GetClusterDataPlane_Call {
	return &MockClient_GetClusterDataPlane_Call{Call: _e.mock.On("GetClusterDataPlane", ctx, cdpName)}
}

func (_c *MockClient_GetClusterDataPlane_Call) Run(run func(ctx context.Context, cdpName string)) *MockClient_GetClusterDataPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetClusterDataPlane_Call) Return(_a0 *gen.ClusterDataPlane, _a1 error) *MockClient_GetClusterDataPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetClusterDataPlane_Call) RunAndReturn(run func(context.Context, string) (*gen.ClusterDataPlane, error)) *MockClient_GetClusterDataPlane_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterObservabilityPlane provides a mock function with given fields: ctx, clusterObservabilityPlaneName
func (_m *MockClient) GetClusterObservabilityPlane(ctx context.Context, clusterObservabilityPlaneName string) (*gen.ClusterObservabilityPlane, error) {
	ret := _m.Called(ctx, clusterObservabilityPlaneName)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterObservabilityPlane")
	}

	var r0 *gen.ClusterObservabilityPlane
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gen.ClusterObservabilityPlane, error)); ok {
		return rf(ctx, clusterObservabilityPlaneName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gen.ClusterObservabilityPlane); ok {
		r0 = rf(ctx, clusterObservabilityPlaneName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ClusterObservabilityPlane)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterObservabilityPlaneName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetClusterObservabilityPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterObservabilityPlane'
type MockClient_GetClusterObservabilityPlane_Call struct {
	*mock.Call
}

// GetClusterObservabilityPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterObservabilityPlaneName string
func (_e *MockClient_Expecter) GetClusterObservabilityPlane(ctx interface{}, clusterObservabilityPlaneName interface{}) *MockClient_GetClusterObservabilityPlane_Call {
	return &MockClient_GetClusterObservabilityPlane_Call{Call: _e.mock.On("GetClusterObservabilityPlane", ctx, clusterObservabilityPlaneName)}
}

func (_c *MockClient_GetClusterObservabilityPlane_Call) Run(run func(ctx context.Context, clusterObservabilityPlaneName string)) *MockClient_GetClusterObservabilityPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetClusterObservabilityPlane_Call) Return(_a0 *gen.ClusterObservabilityPlane, _a1 error) *MockClient_GetClusterObservabilityPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetClusterObservabilityPlane_Call) RunAndReturn(run func(context.Context, string) (*gen.ClusterObservabilityPlane, error)) *MockClient_GetClusterObservabilityPlane_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterTraitSchema provides a mock function with given fields: ctx, clusterTraitName
func (_m *MockClient) GetClusterTraitSchema(ctx context.Context, clusterTraitName string) (*json.RawMessage, error) {
	ret := _m.Called(ctx, clusterTraitName)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterTraitSchema")
	}

	var r0 *json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*json.RawMessage, error)); ok {
		return rf(ctx, clusterTraitName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *json.RawMessage); ok {
		r0 = rf(ctx, clusterTraitName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterTraitName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetClusterTraitSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterTraitSchema'
type MockClient_GetClusterTraitSchema_Call struct {
	*mock.Call
}

// GetClusterTraitSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterTraitName string
func (_e *MockClient_Expecter) GetClusterTraitSchema(ctx interface{}, clusterTraitName interface{}) *MockClient_GetClusterTraitSchema_Call {
	return &MockClient_GetClusterTraitSchema_Call{Call: _e.mock.On("GetClusterTraitSchema", ctx, clusterTraitName)}
}

func (_c *MockClient_GetClusterTraitSchema_Call) Run(run func(ctx context.Context, clusterTraitName string)) *MockClient_GetClusterTraitSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetClusterTraitSchema_Call) Return(_a0 *json.RawMessage, _a1 error) *MockClient_GetClusterTraitSchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetClusterTraitSchema_Call) RunAndReturn(run func(context.Context, string) (*json.RawMessage, error)) *MockClient_GetClusterTraitSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterWorkflowPlane provides a mock function with given fields: ctx, clusterWorkflowPlaneName
func (_m *MockClient) GetClusterWorkflowPlane(ctx context.Context, clusterWorkflowPlaneName string) (*gen.ClusterWorkflowPlane, error) {
	ret := _m.Called(ctx, clusterWorkflowPlaneName)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterWorkflowPlane")
	}

	var r0 *gen.ClusterWorkflowPlane
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gen.ClusterWorkflowPlane, error)); ok {
		return rf(ctx, clusterWorkflowPlaneName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gen.ClusterWorkflowPlane); ok {
		r0 = rf(ctx, clusterWorkflowPlaneName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ClusterWorkflowPlane)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterWorkflowPlaneName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetClusterWorkflowPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterWorkflowPlane'
type MockClient_GetClusterWorkflowPlane_Call struct {
	*mock.Call
}

// GetClusterWorkflowPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterWorkflowPlaneName string
func (_e *MockClient_Expecter) GetClusterWorkflowPlane(ctx interface{}, clusterWorkflowPlaneName interface{}) *MockClient_GetClusterWorkflowPlane_Call {
	return &MockClient_GetClusterWorkflowPlane_Call{Call: _e.mock.On("GetClusterWorkflowPlane", ctx, clusterWorkflowPlaneName)}
}

func (_c *MockClient_GetClusterWorkflowPlane_Call) Run(run func(ctx context.Context, clusterWorkflowPlaneName string)) *MockClient_GetClusterWorkflowPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetClusterWorkflowPlane_Call) Return(_a0 *gen.ClusterWorkflowPlane, _a1 error) *MockClient_GetClusterWorkflowPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetClusterWorkflowPlane_Call) RunAndReturn(run func(context.Context, string) (*gen.ClusterWorkflowPlane, error)) *MockClient_GetClusterWorkflowPlane_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterWorkflowSchema provides a mock function with given fields: ctx, clusterWorkflowName
func (_m *MockClient) GetClusterWorkflowSchema(ctx context.Context, clusterWorkflowName string) (*json.RawMessage, error) {
	ret := _m.Called(ctx, clusterWorkflowName)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterWorkflowSchema")
	}

	var r0 *json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*json.RawMessage, error)); ok {
		return rf(ctx, clusterWorkflowName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *json.RawMessage); ok {
		r0 = rf(ctx, clusterWorkflowName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterWorkflowName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetClusterWorkflowSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterWorkflowSchema'
type MockClient_GetClusterWorkflowSchema_Call struct {
	*mock.Call
}

// GetClusterWorkflowSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterWorkflowName string
func (_e *MockClient_Expecter) GetClusterWorkflowSchema(ctx interface{}, clusterWorkflowName interface{}) *MockClient_GetClusterWorkflowSchema_Call {
	return &MockClient_GetClusterWorkflowSchema_Call{Call: _e.mock.On("GetClusterWorkflowSchema", ctx, clusterWorkflowName)}
}

func (_c *MockClient_GetClusterWorkflowSchema_Call) Run(run func(ctx context.Context, clusterWorkflowName string)) *MockClient_GetClusterWorkflowSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetClusterWorkflowSchema_Call) Return(_a0 *json.RawMessage, _a1 error) *MockClient_GetClusterWorkflowSchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetClusterWorkflowSchema_Call) RunAndReturn(run func(context.Context, string) (*json.RawMessage, error)) *MockClient_GetClusterWorkflowSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponent provides a mock function with given fields: ctx, namespaceName, componentName
func (_m *MockClient) GetComponent(ctx context.Context, namespaceName string, componentName string) (*gen.Component, error) {
	ret := _m.Called(ctx, namespaceName, componentName)

	if len(ret) == 0 {
		panic("no return value specified for GetComponent")
	}

	var r0 *gen.Component
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.Component, error)); ok {
		return rf(ctx, namespaceName, componentName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.Component); ok {
		r0 = rf(ctx, namespaceName, componentName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Component)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, componentName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponent'
type MockClient_GetComponent_Call struct {
	*mock.Call
}

// GetComponent is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentName string
func (_e *MockClient_Expecter) GetComponent(ctx interface{}, namespaceName interface{}, componentName interface{}) *MockClient_GetComponent_Call {
	return &MockClient_GetComponent_Call{Call: _e.mock.On("GetComponent", ctx, namespaceName, componentName)}
}

func (_c *MockClient_GetComponent_Call) Run(run func(ctx context.Context, namespaceName string, componentName string)) *MockClient_GetComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetComponent_Call) Return(_a0 *gen.Component, _a1 error) *MockClient_GetComponent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetComponent_Call) RunAndReturn(run func(context.Context, string, string) (*gen.Component, error)) *MockClient_GetComponent_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponentTypeSchema provides a mock function with given fields: ctx, namespaceName, ctName
func (_m *MockClient) GetComponentTypeSchema(ctx context.Context, namespaceName string, ctName string) (*json.RawMessage, error) {
	ret := _m.Called(ctx, namespaceName, ctName)

	if len(ret) == 0 {
		panic("no return value specified for GetComponentTypeSchema")
	}

	var r0 *json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*json.RawMessage, error)); ok {
		return rf(ctx, namespaceName, ctName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *json.RawMessage); ok {
		r0 = rf(ctx, namespaceName, ctName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, ctName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetComponentTypeSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponentTypeSchema'
type MockClient_GetComponentTypeSchema_Call struct {
	*mock.Call
}

// GetComponentTypeSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - ctName string
func (_e *MockClient_Expecter) GetComponentTypeSchema(ctx interface{}, namespaceName interface{}, ctName interface{}) *MockClient_GetComponentTypeSchema_Call {
	return &MockClient_GetComponentTypeSchema_Call{Call: _e.mock.On("GetComponentTypeSchema", ctx, namespaceName, ctName)}
}

func (_c *MockClient_GetComponentTypeSchema_Call) Run(run func(ctx context.Context, namespaceName string, ctName string)) *MockClient_GetComponentTypeSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetComponentTypeSchema_Call) Return(_a0 *json.RawMessage, _a1 error) *MockClient_GetComponentTypeSchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetComponentTypeSchema_Call) RunAndReturn(run func(context.Context, string, string) (*json.RawMessage, error)) *MockClient_GetComponentTypeSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetDataPlane provides a mock function with given fields: ctx, namespaceName, dpName
func (_m *MockClient) GetDataPlane(ctx context.Context, namespaceName string, dpName string) (*gen.DataPlane, error) {
	ret := _m.Called(ctx, namespaceName, dpName)

	if len(ret) == 0 {
		panic("no return value specified for GetDataPlane")
	}

	var r0 *gen.DataPlane
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.DataPlane, error)); ok {
		return rf(ctx, namespaceName, dpName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.DataPlane); ok {
		r0 = rf(ctx, namespaceName, dpName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.DataPlane)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, dpName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetDataPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataPlane'
type MockClient_GetDataPlane_Call struct {
	*mock.Call
}

// GetDataPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - dpName string
func (_e *MockClient_Expecter) GetDataPlane(ctx interface{}, namespaceName interface{}, dpName interface{}) *MockClient_GetDataPlane_Call {
	return &MockClient_GetDataPlane_Call{Call: _e.mock.On("GetDataPlane", ctx, namespaceName, dpName)}
}

func (_c *MockClient_GetDataPlane_Call) Run(run func(ctx context.Context, namespaceName string, dpName string)) *MockClient_GetDataPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetDataPlane_Call) Return(_a0 *gen.DataPlane, _a1 error) *MockClient_GetDataPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetDataPlane_Call) RunAndReturn(run func(context.Context, string, string) (*gen.DataPlane, error)) *MockClient_GetDataPlane_Call {
	_c.Call.Return(run)
	return _c
}

// GetEnvironment provides a mock function with given fields: ctx, namespaceName, envName
func (_m *MockClient) GetEnvironment(ctx context.Context, namespaceName string, envName string) (*gen.Environment, error) {
	ret := _m.Called(ctx, namespaceName, envName)

	if len(ret) == 0 {
		panic("no return value specified for GetEnvironment")
	}

	var r0 *gen.Environment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.Environment, error)); ok {
		return rf(ctx, namespaceName, envName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.Environment); ok {
		r0 = rf(ctx, namespaceName, envName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Environment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, envName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetEnvironment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEnvironment'
type MockClient_GetEnvironment_Call struct {
	*mock.Call
}

// GetEnvironment is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - envName string
func (_e *MockClient_Expecter) GetEnvironment(ctx interface{}, namespaceName interface{}, envName interface{}) *MockClient_GetEnvironment_Call {
	return &MockClient_GetEnvironment_Call{Call: _e.mock.On("GetEnvironment", ctx, namespaceName, envName)}
}

func (_c *MockClient_GetEnvironment_Call) Run(run func(ctx context.Context, namespaceName string, envName string)) *MockClient_GetEnvironment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetEnvironment_Call) Return(_a0 *gen.Environment, _a1 error) *MockClient_GetEnvironment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetEnvironment_Call) RunAndReturn(run func(context.Context, string, string) (*gen.Environment, error)) *MockClient_GetEnvironment_Call {
	_c.Call.Return(run)
	return _c
}

// GetObservabilityPlane provides a mock function with given fields: ctx, namespaceName, observabilityPlaneName
func (_m *MockClient) GetObservabilityPlane(ctx context.Context, namespaceName string, observabilityPlaneName string) (*gen.ObservabilityPlane, error) {
	ret := _m.Called(ctx, namespaceName, observabilityPlaneName)

	if len(ret) == 0 {
		panic("no return value specified for GetObservabilityPlane")
	}

	var r0 *gen.ObservabilityPlane
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.ObservabilityPlane, error)); ok {
		return rf(ctx, namespaceName, observabilityPlaneName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.ObservabilityPlane); ok {
		r0 = rf(ctx, namespaceName, observabilityPlaneName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ObservabilityPlane)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, observabilityPlaneName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetObservabilityPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObservabilityPlane'
type MockClient_GetObservabilityPlane_Call struct {
	*mock.Call
}

// GetObservabilityPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - observabilityPlaneName string
func (_e *MockClient_Expecter) GetObservabilityPlane(ctx interface{}, namespaceName interface{}, observabilityPlaneName interface{}) *MockClient_GetObservabilityPlane_Call {
	return &MockClient_GetObservabilityPlane_Call{Call: _e.mock.On("GetObservabilityPlane", ctx, namespaceName, observabilityPlaneName)}
}

func (_c *MockClient_GetObservabilityPlane_Call) Run(run func(ctx context.Context, namespaceName string, observabilityPlaneName string)) *MockClient_GetObservabilityPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetObservabilityPlane_Call) Return(_a0 *gen.ObservabilityPlane, _a1 error) *MockClient_GetObservabilityPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetObservabilityPlane_Call) RunAndReturn(run func(context.Context, string, string) (*gen.ObservabilityPlane, error)) *MockClient_GetObservabilityPlane_Call {
	_c.Call.Return(run)
	return _c
}

// GetProjectDeploymentPipeline provides a mock function with given fields: ctx, namespaceName, projectName
func (_m *MockClient) GetProjectDeploymentPipeline(ctx context.Context, namespaceName string, projectName string) (*gen.DeploymentPipeline, error) {
	ret := _m.Called(ctx, namespaceName, projectName)

	if len(ret) == 0 {
		panic("no return value specified for GetProjectDeploymentPipeline")
	}

	var r0 *gen.DeploymentPipeline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.DeploymentPipeline, error)); ok {
		return rf(ctx, namespaceName, projectName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.DeploymentPipeline); ok {
		r0 = rf(ctx, namespaceName, projectName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.DeploymentPipeline)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, projectName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetProjectDeploymentPipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProjectDeploymentPipeline'
type MockClient_GetProjectDeploymentPipeline_Call struct {
	*mock.Call
}

// GetProjectDeploymentPipeline is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectName string
func (_e *MockClient_Expecter) GetProjectDeploymentPipeline(ctx interface{}, namespaceName interface{}, projectName interface{}) *MockClient_GetProjectDeploymentPipeline_Call {
	return &MockClient_GetProjectDeploymentPipeline_Call{Call: _e.mock.On("GetProjectDeploymentPipeline", ctx, namespaceName, projectName)}
}

func (_c *MockClient_GetProjectDeploymentPipeline_Call) Run(run func(ctx context.Context, namespaceName string, projectName string)) *MockClient_GetProjectDeploymentPipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetProjectDeploymentPipeline_Call) Return(_a0 *gen.DeploymentPipeline, _a1 error) *MockClient_GetProjectDeploymentPipeline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetProjectDeploymentPipeline_Call) RunAndReturn(run func(context.Context, string, string) (*gen.DeploymentPipeline, error)) *MockClient_GetProjectDeploymentPipeline_Call {
	_c.Call.Return(run)
	return _c
}

// GetReleaseBinding provides a mock function with given fields: ctx, namespaceName, releaseBindingName
func (_m *MockClient) GetReleaseBinding(ctx context.Context, namespaceName string, releaseBindingName string) (*gen.ReleaseBinding, error) {
	ret := _m.Called(ctx, namespaceName, releaseBindingName)

	if len(ret) == 0 {
		panic("no return value specified for GetReleaseBinding")
	}

	var r0 *gen.ReleaseBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.ReleaseBinding, error)); ok {
		return rf(ctx, namespaceName, releaseBindingName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.ReleaseBinding); ok {
		r0 = rf(ctx, namespaceName, releaseBindingName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ReleaseBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, releaseBindingName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReleaseBinding'
type MockClient_GetReleaseBinding_Call struct {
	*mock.Call
}

// GetReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - releaseBindingName string
func (_e *MockClient_Expecter) GetReleaseBinding(ctx interface{}, namespaceName interface{}, releaseBindingName interface{}) *MockClient_GetReleaseBinding_Call {
	return &MockClient_GetReleaseBinding_Call{Call: _e.mock.On("GetReleaseBinding", ctx, namespaceName, releaseBindingName)}
}

func (_c *MockClient_GetReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, releaseBindingName string)) *MockClient_GetReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetReleaseBinding_Call) Return(_a0 *gen.ReleaseBinding, _a1 error) *MockClient_GetReleaseBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetReleaseBinding_Call) RunAndReturn(run func(context.Context, string, string) (*gen.ReleaseBinding, error)) *MockClient_GetReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// GetTraitSchema provides a mock function with given fields: ctx, namespaceName, traitName
func (_m *MockClient) GetTraitSchema(ctx context.Context, namespaceName string, traitName string) (*json.RawMessage, error) {
	ret := _m.Called(ctx, namespaceName, traitName)

	if len(ret) == 0 {
		panic("no return value specified for GetTraitSchema")
	}

	var r0 *json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*json.RawMessage, error)); ok {
		return rf(ctx, namespaceName, traitName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *json.RawMessage); ok {
		r0 = rf(ctx, namespaceName, traitName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, traitName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetTraitSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTraitSchema'
type MockClient_GetTraitSchema_Call struct {
	*mock.Call
}

// GetTraitSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - traitName string
func (_e *MockClient_Expecter) GetTraitSchema(ctx interface{}, namespaceName interface{}, traitName interface{}) *MockClient_GetTraitSchema_Call {
	return &MockClient_GetTraitSchema_Call{Call: _e.mock.On("GetTraitSchema", ctx, namespaceName, traitName)}
}

func (_c *MockClient_GetTraitSchema_Call) Run(run func(ctx context.Context, namespaceName string, traitName string)) *MockClient_GetTraitSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetTraitSchema_Call) Return(_a0 *json.RawMessage, _a1 error) *MockClient_GetTraitSchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetTraitSchema_Call) RunAndReturn(run func(context.Context, string, string) (*json.RawMessage, error)) *MockClient_GetTraitSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflow provides a mock function with given fields: ctx, namespaceName, workflowName
func (_m *MockClient) GetWorkflow(ctx context.Context, namespaceName string, workflowName string) (*gen.Workflow, error) {
	ret := _m.Called(ctx, namespaceName, workflowName)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflow")
	}

	var r0 *gen.Workflow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.Workflow, error)); ok {
		return rf(ctx, namespaceName, workflowName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.Workflow); ok {
		r0 = rf(ctx, namespaceName, workflowName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Workflow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, workflowName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetWorkflow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflow'
type MockClient_GetWorkflow_Call struct {
	*mock.Call
}

// GetWorkflow is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - workflowName string
func (_e *MockClient_Expecter) GetWorkflow(ctx interface{}, namespaceName interface{}, workflowName interface{}) *MockClient_GetWorkflow_Call {
	return &MockClient_GetWorkflow_Call{Call: _e.mock.On("GetWorkflow", ctx, namespaceName, workflowName)}
}

func (_c *MockClient_GetWorkflow_Call) Run(run func(ctx context.Context, namespaceName string, workflowName string)) *MockClient_GetWorkflow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetWorkflow_Call) Return(_a0 *gen.Workflow, _a1 error) *MockClient_GetWorkflow_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetWorkflow_Call) RunAndReturn(run func(context.Context, string, string) (*gen.Workflow, error)) *MockClient_GetWorkflow_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflowPlane provides a mock function with given fields: ctx, namespaceName, workflowPlaneName
func (_m *MockClient) GetWorkflowPlane(ctx context.Context, namespaceName string, workflowPlaneName string) (*gen.WorkflowPlane, error) {
	ret := _m.Called(ctx, namespaceName, workflowPlaneName)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowPlane")
	}

	var r0 *gen.WorkflowPlane
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.WorkflowPlane, error)); ok {
		return rf(ctx, namespaceName, workflowPlaneName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.WorkflowPlane); ok {
		r0 = rf(ctx, namespaceName, workflowPlaneName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.WorkflowPlane)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, workflowPlaneName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetWorkflowPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowPlane'
type MockClient_GetWorkflowPlane_Call struct {
	*mock.Call
}

// GetWorkflowPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - workflowPlaneName string
func (_e *MockClient_Expecter) GetWorkflowPlane(ctx interface{}, namespaceName interface{}, workflowPlaneName interface{}) *MockClient_GetWorkflowPlane_Call {
	return &MockClient_GetWorkflowPlane_Call{Call: _e.mock.On("GetWorkflowPlane", ctx, namespaceName, workflowPlaneName)}
}

func (_c *MockClient_GetWorkflowPlane_Call) Run(run func(ctx context.Context, namespaceName string, workflowPlaneName string)) *MockClient_GetWorkflowPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetWorkflowPlane_Call) Return(_a0 *gen.WorkflowPlane, _a1 error) *MockClient_GetWorkflowPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetWorkflowPlane_Call) RunAndReturn(run func(context.Context, string, string) (*gen.WorkflowPlane, error)) *MockClient_GetWorkflowPlane_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflowRun provides a mock function with given fields: ctx, namespaceName, workflowRunName
func (_m *MockClient) GetWorkflowRun(ctx context.Context, namespaceName string, workflowRunName string) (*gen.WorkflowRun, error) {
	ret := _m.Called(ctx, namespaceName, workflowRunName)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowRun")
	}

	var r0 *gen.WorkflowRun
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.WorkflowRun, error)); ok {
		return rf(ctx, namespaceName, workflowRunName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.WorkflowRun); ok {
		r0 = rf(ctx, namespaceName, workflowRunName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.WorkflowRun)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, workflowRunName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetWorkflowRun_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowRun'
type MockClient_GetWorkflowRun_Call struct {
	*mock.Call
}

// GetWorkflowRun is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - workflowRunName string
func (_e *MockClient_Expecter) GetWorkflowRun(ctx interface{}, namespaceName interface{}, workflowRunName interface{}) *MockClient_GetWorkflowRun_Call {
	return &MockClient_GetWorkflowRun_Call{Call: _e.mock.On("GetWorkflowRun", ctx, namespaceName, workflowRunName)}
}

func (_c *MockClient_GetWorkflowRun_Call) Run(run func(ctx context.Context, namespaceName string, workflowRunName string)) *MockClient_GetWorkflowRun_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetWorkflowRun_Call) Return(_a0 *gen.WorkflowRun, _a1 error) *MockClient_GetWorkflowRun_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetWorkflowRun_Call) RunAndReturn(run func(context.Context, string, string) (*gen.WorkflowRun, error)) *MockClient_GetWorkflowRun_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflowRunLogs provides a mock function with given fields: ctx, namespaceName, runName, params
func (_m *MockClient) GetWorkflowRunLogs(ctx context.Context, namespaceName string, runName string, params *gen.GetWorkflowRunLogsParams) ([]gen.WorkflowRunLogEntry, error) {
	ret := _m.Called(ctx, namespaceName, runName, params)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowRunLogs")
	}

	var r0 []gen.WorkflowRunLogEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *gen.GetWorkflowRunLogsParams) ([]gen.WorkflowRunLogEntry, error)); ok {
		return rf(ctx, namespaceName, runName, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *gen.GetWorkflowRunLogsParams) []gen.WorkflowRunLogEntry); ok {
		r0 = rf(ctx, namespaceName, runName, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]gen.WorkflowRunLogEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *gen.GetWorkflowRunLogsParams) error); ok {
		r1 = rf(ctx, namespaceName, runName, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetWorkflowRunLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowRunLogs'
type MockClient_GetWorkflowRunLogs_Call struct {
	*mock.Call
}

// GetWorkflowRunLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - runName string
//   - params *gen.GetWorkflowRunLogsParams
func (_e *MockClient_Expecter) GetWorkflowRunLogs(ctx interface{}, namespaceName interface{}, runName interface{}, params interface{}) *MockClient_GetWorkflowRunLogs_Call {
	return &MockClient_GetWorkflowRunLogs_Call{Call: _e.mock.On("GetWorkflowRunLogs", ctx, namespaceName, runName, params)}
}

func (_c *MockClient_GetWorkflowRunLogs_Call) Run(run func(ctx context.Context, namespaceName string, runName string, params *gen.GetWorkflowRunLogsParams)) *MockClient_GetWorkflowRunLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*gen.GetWorkflowRunLogsParams))
	})
	return _c
}

func (_c *MockClient_GetWorkflowRunLogs_Call) Return(_a0 []gen.WorkflowRunLogEntry, _a1 error) *MockClient_GetWorkflowRunLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetWorkflowRunLogs_Call) RunAndReturn(run func(context.Context, string, string, *gen.GetWorkflowRunLogsParams) ([]gen.WorkflowRunLogEntry, error)) *MockClient_GetWorkflowRunLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflowRunStatus provides a mock function with given fields: ctx, namespaceName, runName
func (_m *MockClient) GetWorkflowRunStatus(ctx context.Context, namespaceName string, runName string) (*gen.WorkflowRunStatusResponse, error) {
	ret := _m.Called(ctx, namespaceName, runName)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowRunStatus")
	}

	var r0 *gen.WorkflowRunStatusResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.WorkflowRunStatusResponse, error)); ok {
		return rf(ctx, namespaceName, runName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.WorkflowRunStatusResponse); ok {
		r0 = rf(ctx, namespaceName, runName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.WorkflowRunStatusResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, runName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetWorkflowRunStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowRunStatus'
type MockClient_GetWorkflowRunStatus_Call struct {
	*mock.Call
}

// GetWorkflowRunStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - runName string
func (_e *MockClient_Expecter) GetWorkflowRunStatus(ctx interface{}, namespaceName interface{}, runName interface{}) *MockClient_GetWorkflowRunStatus_Call {
	return &MockClient_GetWorkflowRunStatus_Call{Call: _e.mock.On("GetWorkflowRunStatus", ctx, namespaceName, runName)}
}

func (_c *MockClient_GetWorkflowRunStatus_Call) Run(run func(ctx context.Context, namespaceName string, runName string)) *MockClient_GetWorkflowRunStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetWorkflowRunStatus_Call) Return(_a0 *gen.WorkflowRunStatusResponse, _a1 error) *MockClient_GetWorkflowRunStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetWorkflowRunStatus_Call) RunAndReturn(run func(context.Context, string, string) (*gen.WorkflowRunStatusResponse, error)) *MockClient_GetWorkflowRunStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkflowSchema provides a mock function with given fields: ctx, namespaceName, workflowName
func (_m *MockClient) GetWorkflowSchema(ctx context.Context, namespaceName string, workflowName string) (*json.RawMessage, error) {
	ret := _m.Called(ctx, namespaceName, workflowName)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkflowSchema")
	}

	var r0 *json.RawMessage
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*json.RawMessage, error)); ok {
		return rf(ctx, namespaceName, workflowName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *json.RawMessage); ok {
		r0 = rf(ctx, namespaceName, workflowName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*json.RawMessage)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, workflowName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetWorkflowSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkflowSchema'
type MockClient_GetWorkflowSchema_Call struct {
	*mock.Call
}

// GetWorkflowSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - workflowName string
func (_e *MockClient_Expecter) GetWorkflowSchema(ctx interface{}, namespaceName interface{}, workflowName interface{}) *MockClient_GetWorkflowSchema_Call {
	return &MockClient_GetWorkflowSchema_Call{Call: _e.mock.On("GetWorkflowSchema", ctx, namespaceName, workflowName)}
}

func (_c *MockClient_GetWorkflowSchema_Call) Run(run func(ctx context.Context, namespaceName string, workflowName string)) *MockClient_GetWorkflowSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetWorkflowSchema_Call) Return(_a0 *json.RawMessage, _a1 error) *MockClient_GetWorkflowSchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetWorkflowSchema_Call) RunAndReturn(run func(context.Context, string, string) (*json.RawMessage, error)) *MockClient_GetWorkflowSchema_Call {
	_c.Call.Return(run)
	return _c
}

// ListComponents provides a mock function with given fields: ctx, namespaceName, projectName, params
func (_m *MockClient) ListComponents(ctx context.Context, namespaceName string, projectName string, params *gen.ListComponentsParams) (*gen.ComponentList, error) {
	ret := _m.Called(ctx, namespaceName, projectName, params)

	if len(ret) == 0 {
		panic("no return value specified for ListComponents")
	}

	var r0 *gen.ComponentList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *gen.ListComponentsParams) (*gen.ComponentList, error)); ok {
		return rf(ctx, namespaceName, projectName, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *gen.ListComponentsParams) *gen.ComponentList); ok {
		r0 = rf(ctx, namespaceName, projectName, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ComponentList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *gen.ListComponentsParams) error); ok {
		r1 = rf(ctx, namespaceName, projectName, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComponents'
type MockClient_ListComponents_Call struct {
	*mock.Call
}

// ListComponents is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectName string
//   - params *gen.ListComponentsParams
func (_e *MockClient_Expecter) ListComponents(ctx interface{}, namespaceName interface{}, projectName interface{}, params interface{}) *MockClient_ListComponents_Call {
	return &MockClient_ListComponents_Call{Call: _e.mock.On("ListComponents", ctx, namespaceName, projectName, params)}
}

func (_c *MockClient_ListComponents_Call) Run(run func(ctx context.Context, namespaceName string, projectName string, params *gen.ListComponentsParams)) *MockClient_ListComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*gen.ListComponentsParams))
	})
	return _c
}

func (_c *MockClient_ListComponents_Call) Return(_a0 *gen.ComponentList, _a1 error) *MockClient_ListComponents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListComponents_Call) RunAndReturn(run func(context.Context, string, string, *gen.ListComponentsParams) (*gen.ComponentList, error)) *MockClient_ListComponents_Call {
	_c.Call.Return(run)
	return _c
}

// ListReleaseBindings provides a mock function with given fields: ctx, namespaceName, params
func (_m *MockClient) ListReleaseBindings(ctx context.Context, namespaceName string, params *gen.ListReleaseBindingsParams) (*gen.ReleaseBindingList, error) {
	ret := _m.Called(ctx, namespaceName, params)

	if len(ret) == 0 {
		panic("no return value specified for ListReleaseBindings")
	}

	var r0 *gen.ReleaseBindingList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListReleaseBindingsParams) (*gen.ReleaseBindingList, error)); ok {
		return rf(ctx, namespaceName, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListReleaseBindingsParams) *gen.ReleaseBindingList); ok {
		r0 = rf(ctx, namespaceName, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ReleaseBindingList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *gen.ListReleaseBindingsParams) error); ok {
		r1 = rf(ctx, namespaceName, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListReleaseBindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReleaseBindings'
type MockClient_ListReleaseBindings_Call struct {
	*mock.Call
}

// ListReleaseBindings is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - params *gen.ListReleaseBindingsParams
func (_e *MockClient_Expecter) ListReleaseBindings(ctx interface{}, namespaceName interface{}, params interface{}) *MockClient_ListReleaseBindings_Call {
	return &MockClient_ListReleaseBindings_Call{Call: _e.mock.On("ListReleaseBindings", ctx, namespaceName, params)}
}

func (_c *MockClient_ListReleaseBindings_Call) Run(run func(ctx context.Context, namespaceName string, params *gen.ListReleaseBindingsParams)) *MockClient_ListReleaseBindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*gen.ListReleaseBindingsParams))
	})
	return _c
}

func (_c *MockClient_ListReleaseBindings_Call) Return(_a0 *gen.ReleaseBindingList, _a1 error) *MockClient_ListReleaseBindings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListReleaseBindings_Call) RunAndReturn(run func(context.Context, string, *gen.ListReleaseBindingsParams) (*gen.ReleaseBindingList, error)) *MockClient_ListReleaseBindings_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkflowRuns provides a mock function with given fields: ctx, namespaceName, params
func (_m *MockClient) ListWorkflowRuns(ctx context.Context, namespaceName string, params *gen.ListWorkflowRunsParams) (*gen.WorkflowRunList, error) {
	ret := _m.Called(ctx, namespaceName, params)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkflowRuns")
	}

	var r0 *gen.WorkflowRunList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListWorkflowRunsParams) (*gen.WorkflowRunList, error)); ok {
		return rf(ctx, namespaceName, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListWorkflowRunsParams) *gen.WorkflowRunList); ok {
		r0 = rf(ctx, namespaceName, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.WorkflowRunList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *gen.ListWorkflowRunsParams) error); ok {
		r1 = rf(ctx, namespaceName, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListWorkflowRuns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkflowRuns'
type MockClient_ListWorkflowRuns_Call struct {
	*mock.Call
}

// ListWorkflowRuns is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - params *gen.ListWorkflowRunsParams
func (_e *MockClient_Expecter) ListWorkflowRuns(ctx interface{}, namespaceName interface{}, params interface{}) *MockClient_ListWorkflowRuns_Call {
	return &MockClient_ListWorkflowRuns_Call{Call: _e.mock.On("ListWorkflowRuns", ctx, namespaceName, params)}
}

func (_c *MockClient_ListWorkflowRuns_Call) Run(run func(ctx context.Context, namespaceName string, params *gen.ListWorkflowRunsParams)) *MockClient_ListWorkflowRuns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*gen.ListWorkflowRunsParams))
	})
	return _c
}

func (_c *MockClient_ListWorkflowRuns_Call) Return(_a0 *gen.WorkflowRunList, _a1 error) *MockClient_ListWorkflowRuns_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListWorkflowRuns_Call) RunAndReturn(run func(context.Context, string, *gen.ListWorkflowRunsParams) (*gen.WorkflowRunList, error)) *MockClient_ListWorkflowRuns_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkflows provides a mock function with given fields: ctx, namespaceName, params
func (_m *MockClient) ListWorkflows(ctx context.Context, namespaceName string, params *gen.ListWorkflowsParams) (*gen.WorkflowList, error) {
	ret := _m.Called(ctx, namespaceName, params)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkflows")
	}

	var r0 *gen.WorkflowList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListWorkflowsParams) (*gen.WorkflowList, error)); ok {
		return rf(ctx, namespaceName, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListWorkflowsParams) *gen.WorkflowList); ok {
		r0 = rf(ctx, namespaceName, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.WorkflowList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *gen.ListWorkflowsParams) error); ok {
		r1 = rf(ctx, namespaceName, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListWorkflows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkflows'
type MockClient_ListWorkflows_Call struct {
	*mock.Call
}

// ListWorkflows is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - params *gen.ListWorkflowsParams
func (_e *MockClient_Expecter) ListWorkflows(ctx interface{}, namespaceName interface{}, params interface{}) *MockClient_ListWorkflows_Call {
	return &MockClient_ListWorkflows_Call{Call: _e.mock.On("ListWorkflows", ctx, namespaceName, params)}
}

func (_c *MockClient_ListWorkflows_Call) Run(run func(ctx context.Context, namespaceName string, params *gen.ListWorkflowsParams)) *MockClient_ListWorkflows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*gen.ListWorkflowsParams))
	})
	return _c
}

func (_c *MockClient_ListWorkflows_Call) Return(_a0 *gen.WorkflowList, _a1 error) *MockClient_ListWorkflows_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListWorkflows_Call) RunAndReturn(run func(context.Context, string, *gen.ListWorkflowsParams) (*gen.WorkflowList, error)) *MockClient_ListWorkflows_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReleaseBinding provides a mock function with given fields: ctx, namespaceName, bindingName, req
func (_m *MockClient) UpdateReleaseBinding(ctx context.Context, namespaceName string, bindingName string, req gen.ReleaseBinding) (*gen.ReleaseBinding, error) {
	ret := _m.Called(ctx, namespaceName, bindingName, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReleaseBinding")
	}

	var r0 *gen.ReleaseBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, gen.ReleaseBinding) (*gen.ReleaseBinding, error)); ok {
		return rf(ctx, namespaceName, bindingName, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, gen.ReleaseBinding) *gen.ReleaseBinding); ok {
		r0 = rf(ctx, namespaceName, bindingName, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ReleaseBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, gen.ReleaseBinding) error); ok {
		r1 = rf(ctx, namespaceName, bindingName, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_UpdateReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReleaseBinding'
type MockClient_UpdateReleaseBinding_Call struct {
	*mock.Call
}

// UpdateReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - bindingName string
//   - req gen.ReleaseBinding
func (_e *MockClient_Expecter) UpdateReleaseBinding(ctx interface{}, namespaceName interface{}, bindingName interface{}, req interface{}) *MockClient_UpdateReleaseBinding_Call {
	return &MockClient_UpdateReleaseBinding_Call{Call: _e.mock.On("UpdateReleaseBinding", ctx, namespaceName, bindingName, req)}
}

func (_c *MockClient_UpdateReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, bindingName string, req gen.ReleaseBinding)) *MockClient_UpdateReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(gen.ReleaseBinding))
	})
	return _c
}

func (_c *MockClient_UpdateReleaseBinding_Call) Return(_a0 *gen.ReleaseBinding, _a1 error) *MockClient_UpdateReleaseBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_UpdateReleaseBinding_Call) RunAndReturn(run func(context.Context, string, string, gen.ReleaseBinding) (*gen.ReleaseBinding, error)) *MockClient_UpdateReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
