// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockHealthChecker is an autogenerated mock type for the HealthChecker type
type MockHealthChecker struct {
	mock.Mock
}

type MockHealthChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHealthChecker) EXPECT() *MockHealthChecker_Expecter {
	return &MockHealthChecker_Expecter{mock: &_m.Mock}
}

// Check provides a mock function with given fields: ctx
func (_m *MockHealthChecker) Check(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockHealthChecker_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockHealthChecker_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHealthChecker_Expecter) Check(ctx interface{}) *MockHealthChecker_Check_Call {
	return &MockHealthChecker_Check_Call{Call: _e.mock.On("Check", ctx)}
}

func (_c *MockHealthChecker_Check_Call) Run(run func(ctx context.Context)) *MockHealthChecker_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockHealthChecker_Check_Call) Return(_a0 error) *MockHealthChecker_Check_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHealthChecker_Check_Call) RunAndReturn(run func(context.Context) error) *MockHealthChecker_Check_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHealthChecker creates a new instance of MockHealthChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHealthChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHealthChecker {
	mock := &MockHealthChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
