// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	types "github.com/openchoreo/openchoreo/internal/observer/types"
)

// MockMetricsQuerier is an autogenerated mock type for the MetricsQuerier type
type MockMetricsQuerier struct {
	mock.Mock
}

type MockMetricsQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricsQuerier) EXPECT() *MockMetricsQuerier_Expecter {
	return &MockMetricsQuerier_Expecter{mock: &_m.Mock}
}

// QueryMetrics provides a mock function with given fields: ctx, req
func (_m *MockMetricsQuerier) QueryMetrics(ctx context.Context, req *types.MetricsQueryRequest) (interface{}, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for QueryMetrics")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.MetricsQueryRequest) (interface{}, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.MetricsQueryRequest) interface{}); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.MetricsQueryRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetricsQuerier_QueryMetrics_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryMetrics'
type MockMetricsQuerier_QueryMetrics_Call struct {
	*mock.Call
}

// QueryMetrics is a helper method to define mock.On call
//   - ctx context.Context
//   - req *types.MetricsQueryRequest
func (_e *MockMetricsQuerier_Expecter) QueryMetrics(ctx interface{}, req interface{}) *MockMetricsQuerier_QueryMetrics_Call {
	return &MockMetricsQuerier_QueryMetrics_Call{Call: _e.mock.On("QueryMetrics", ctx, req)}
}

func (_c *MockMetricsQuerier_QueryMetrics_Call) Run(run func(ctx context.Context, req *types.MetricsQueryRequest)) *MockMetricsQuerier_QueryMetrics_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.MetricsQueryRequest))
	})
	return _c
}

func (_c *MockMetricsQuerier_QueryMetrics_Call) Return(_a0 interface{}, _a1 error) *MockMetricsQuerier_QueryMetrics_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetricsQuerier_QueryMetrics_Call) RunAndReturn(run func(context.Context, *types.MetricsQueryRequest) (interface{}, error)) *MockMetricsQuerier_QueryMetrics_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetricsQuerier creates a new instance of MockMetricsQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricsQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricsQuerier {
	mock := &MockMetricsQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
