apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: patient-management-service
  namespace: default
spec:
  owner:
    projectName: default

  componentType:
    kind: ClusterComponentType
    name: deployment/service

  autoDeploy: true

  workflow:
    kind: ClusterWorkflow
    name: ballerina-buildpack-builder
    parameters:
      repository:
        url: "https://github.com/openchoreo/sample-workloads"
        revision:
          branch: "main"
        appPath: "/service-ballerina-patient-management"

---
apiVersion: openchoreo.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: patient-management-service-build-01
  labels:
    openchoreo.dev/project: "default"
    openchoreo.dev/component: "patient-management-service"
spec:
  workflow:
    kind: ClusterWorkflow
    name: ballerina-buildpack-builder
    parameters:
      repository:
        url: "https://github.com/openchoreo/sample-workloads"
        revision:
          branch: "main"
        appPath: "/service-ballerina-patient-management"
