// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateResource provides a mock function with given fields: ctx, namespaceName, _a2
func (_m *MockService) CreateResource(ctx context.Context, namespaceName string, _a2 *v1alpha1.Resource) (*v1alpha1.Resource, error) {
	ret := _m.Called(ctx, namespaceName, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateResource")
	}

	var r0 *v1alpha1.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Resource) (*v1alpha1.Resource, error)); ok {
		return rf(ctx, namespaceName, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Resource) *v1alpha1.Resource); ok {
		r0 = rf(ctx, namespaceName, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.Resource) error); ok {
		r1 = rf(ctx, namespaceName, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResource'
type MockService_CreateResource_Call struct {
	*mock.Call
}

// CreateResource is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - _a2 *v1alpha1.Resource
func (_e *MockService_Expecter) CreateResource(ctx interface{}, namespaceName interface{}, _a2 interface{}) *MockService_CreateResource_Call {
	return &MockService_CreateResource_Call{Call: _e.mock.On("CreateResource", ctx, namespaceName, _a2)}
}

func (_c *MockService_CreateResource_Call) Run(run func(ctx context.Context, namespaceName string, _a2 *v1alpha1.Resource)) *MockService_CreateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.Resource))
	})
	return _c
}

func (_c *MockService_CreateResource_Call) Return(_a0 *v1alpha1.Resource, _a1 error) *MockService_CreateResource_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateResource_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.Resource) (*v1alpha1.Resource, error)) *MockService_CreateResource_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResource provides a mock function with given fields: ctx, namespaceName, resourceName
func (_m *MockService) DeleteResource(ctx context.Context, namespaceName string, resourceName string) error {
	ret := _m.Called(ctx, namespaceName, resourceName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResource")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, resourceName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResource'
type MockService_DeleteResource_Call struct {
	*mock.Call
}

// DeleteResource is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - resourceName string
func (_e *MockService_Expecter) DeleteResource(ctx interface{}, namespaceName interface{}, resourceName interface{}) *MockService_DeleteResource_Call {
	return &MockService_DeleteResource_Call{Call: _e.mock.On("DeleteResource", ctx, namespaceName, resourceName)}
}

func (_c *MockService_DeleteResource_Call) Run(run func(ctx context.Context, namespaceName string, resourceName string)) *MockService_DeleteResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteResource_Call) Return(_a0 error) *MockService_DeleteResource_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteResource_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetResource provides a mock function with given fields: ctx, namespaceName, resourceName
func (_m *MockService) GetResource(ctx context.Context, namespaceName string, resourceName string) (*v1alpha1.Resource, error) {
	ret := _m.Called(ctx, namespaceName, resourceName)

	if len(ret) == 0 {
		panic("no return value specified for GetResource")
	}

	var r0 *v1alpha1.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.Resource, error)); ok {
		return rf(ctx, namespaceName, resourceName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.Resource); ok {
		r0 = rf(ctx, namespaceName, resourceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, resourceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResource'
type MockService_GetResource_Call struct {
	*mock.Call
}

// GetResource is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - resourceName string
func (_e *MockService_Expecter) GetResource(ctx interface{}, namespaceName interface{}, resourceName interface{}) *MockService_GetResource_Call {
	return &MockService_GetResource_Call{Call: _e.mock.On("GetResource", ctx, namespaceName, resourceName)}
}

func (_c *MockService_GetResource_Call) Run(run func(ctx context.Context, namespaceName string, resourceName string)) *MockService_GetResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetResource_Call) Return(_a0 *v1alpha1.Resource, _a1 error) *MockService_GetResource_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetResource_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.Resource, error)) *MockService_GetResource_Call {
	_c.Call.Return(run)
	return _c
}

// ListResources provides a mock function with given fields: ctx, namespaceName, projectName, opts
func (_m *MockService) ListResources(ctx context.Context, namespaceName string, projectName string, opts services.ListOptions) (*services.ListResult[v1alpha1.Resource], error) {
	ret := _m.Called(ctx, namespaceName, projectName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListResources")
	}

	var r0 *services.ListResult[v1alpha1.Resource]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.Resource], error)); ok {
		return rf(ctx, namespaceName, projectName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) *services.ListResult[v1alpha1.Resource]); ok {
		r0 = rf(ctx, namespaceName, projectName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.Resource])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, projectName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResources'
type MockService_ListResources_Call struct {
	*mock.Call
}

// ListResources is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListResources(ctx interface{}, namespaceName interface{}, projectName interface{}, opts interface{}) *MockService_ListResources_Call {
	return &MockService_ListResources_Call{Call: _e.mock.On("ListResources", ctx, namespaceName, projectName, opts)}
}

func (_c *MockService_ListResources_Call) Run(run func(ctx context.Context, namespaceName string, projectName string, opts services.ListOptions)) *MockService_ListResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListResources_Call) Return(_a0 *services.ListResult[v1alpha1.Resource], _a1 error) *MockService_ListResources_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListResources_Call) RunAndReturn(run func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.Resource], error)) *MockService_ListResources_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResource provides a mock function with given fields: ctx, namespaceName, _a2
func (_m *MockService) UpdateResource(ctx context.Context, namespaceName string, _a2 *v1alpha1.Resource) (*v1alpha1.Resource, error) {
	ret := _m.Called(ctx, namespaceName, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResource")
	}

	var r0 *v1alpha1.Resource
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Resource) (*v1alpha1.Resource, error)); ok {
		return rf(ctx, namespaceName, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Resource) *v1alpha1.Resource); ok {
		r0 = rf(ctx, namespaceName, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Resource)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.Resource) error); ok {
		r1 = rf(ctx, namespaceName, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResource'
type MockService_UpdateResource_Call struct {
	*mock.Call
}

// UpdateResource is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - _a2 *v1alpha1.Resource
func (_e *MockService_Expecter) UpdateResource(ctx interface{}, namespaceName interface{}, _a2 interface{}) *MockService_UpdateResource_Call {
	return &MockService_UpdateResource_Call{Call: _e.mock.On("UpdateResource", ctx, namespaceName, _a2)}
}

func (_c *MockService_UpdateResource_Call) Run(run func(ctx context.Context, namespaceName string, _a2 *v1alpha1.Resource)) *MockService_UpdateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.Resource))
	})
	return _c
}

func (_c *MockService_UpdateResource_Call) Return(_a0 *v1alpha1.Resource, _a1 error) *MockService_UpdateResource_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateResource_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.Resource) (*v1alpha1.Resource, error)) *MockService_UpdateResource_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
