// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/openchoreo/openchoreo/internal/openchoreo-api/api/gen"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteComponentType provides a mock function with given fields: ctx, namespaceName, ctName
func (_m *MockClient) DeleteComponentType(ctx context.Context, namespaceName string, ctName string) error {
	ret := _m.Called(ctx, namespaceName, ctName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComponentType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, ctName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeleteComponentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComponentType'
type MockClient_DeleteComponentType_Call struct {
	*mock.Call
}

// DeleteComponentType is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - ctName string
func (_e *MockClient_Expecter) DeleteComponentType(ctx interface{}, namespaceName interface{}, ctName interface{}) *MockClient_DeleteComponentType_Call {
	return &MockClient_DeleteComponentType_Call{Call: _e.mock.On("DeleteComponentType", ctx, namespaceName, ctName)}
}

func (_c *MockClient_DeleteComponentType_Call) Run(run func(ctx context.Context, namespaceName string, ctName string)) *MockClient_DeleteComponentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_DeleteComponentType_Call) Return(_a0 error) *MockClient_DeleteComponentType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeleteComponentType_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_DeleteComponentType_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponentType provides a mock function with given fields: ctx, namespaceName, ctName
func (_m *MockClient) GetComponentType(ctx context.Context, namespaceName string, ctName string) (*gen.ComponentType, error) {
	ret := _m.Called(ctx, namespaceName, ctName)

	if len(ret) == 0 {
		panic("no return value specified for GetComponentType")
	}

	var r0 *gen.ComponentType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.ComponentType, error)); ok {
		return rf(ctx, namespaceName, ctName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.ComponentType); ok {
		r0 = rf(ctx, namespaceName, ctName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ComponentType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, ctName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetComponentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponentType'
type MockClient_GetComponentType_Call struct {
	*mock.Call
}

// GetComponentType is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - ctName string
func (_e *MockClient_Expecter) GetComponentType(ctx interface{}, namespaceName interface{}, ctName interface{}) *MockClient_GetComponentType_Call {
	return &MockClient_GetComponentType_Call{Call: _e.mock.On("GetComponentType", ctx, namespaceName, ctName)}
}

func (_c *MockClient_GetComponentType_Call) Run(run func(ctx context.Context, namespaceName string, ctName string)) *MockClient_GetComponentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetComponentType_Call) Return(_a0 *gen.ComponentType, _a1 error) *MockClient_GetComponentType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetComponentType_Call) RunAndReturn(run func(context.Context, string, string) (*gen.ComponentType, error)) *MockClient_GetComponentType_Call {
	_c.Call.Return(run)
	return _c
}

// ListComponentTypes provides a mock function with given fields: ctx, namespaceName, params
func (_m *MockClient) ListComponentTypes(ctx context.Context, namespaceName string, params *gen.ListComponentTypesParams) (*gen.ComponentTypeList, error) {
	ret := _m.Called(ctx, namespaceName, params)

	if len(ret) == 0 {
		panic("no return value specified for ListComponentTypes")
	}

	var r0 *gen.ComponentTypeList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListComponentTypesParams) (*gen.ComponentTypeList, error)); ok {
		return rf(ctx, namespaceName, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListComponentTypesParams) *gen.ComponentTypeList); ok {
		r0 = rf(ctx, namespaceName, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ComponentTypeList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *gen.ListComponentTypesParams) error); ok {
		r1 = rf(ctx, namespaceName, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListComponentTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComponentTypes'
type MockClient_ListComponentTypes_Call struct {
	*mock.Call
}

// ListComponentTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - params *gen.ListComponentTypesParams
func (_e *MockClient_Expecter) ListComponentTypes(ctx interface{}, namespaceName interface{}, params interface{}) *MockClient_ListComponentTypes_Call {
	return &MockClient_ListComponentTypes_Call{Call: _e.mock.On("ListComponentTypes", ctx, namespaceName, params)}
}

func (_c *MockClient_ListComponentTypes_Call) Run(run func(ctx context.Context, namespaceName string, params *gen.ListComponentTypesParams)) *MockClient_ListComponentTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*gen.ListComponentTypesParams))
	})
	return _c
}

func (_c *MockClient_ListComponentTypes_Call) Return(_a0 *gen.ComponentTypeList, _a1 error) *MockClient_ListComponentTypes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListComponentTypes_Call) RunAndReturn(run func(context.Context, string, *gen.ListComponentTypesParams) (*gen.ComponentTypeList, error)) *MockClient_ListComponentTypes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
