// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	secret "github.com/openchoreo/openchoreo/internal/openchoreo-api/services/secret"
	mock "github.com/stretchr/testify/mock"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateSecret provides a mock function with given fields: ctx, namespaceName, req
func (_m *MockService) CreateSecret(ctx context.Context, namespaceName string, req *secret.CreateSecretParams) (*secret.SecretInfo, error) {
	ret := _m.Called(ctx, namespaceName, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 *secret.SecretInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *secret.CreateSecretParams) (*secret.SecretInfo, error)); ok {
		return rf(ctx, namespaceName, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *secret.CreateSecretParams) *secret.SecretInfo); ok {
		r0 = rf(ctx, namespaceName, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secret.SecretInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *secret.CreateSecretParams) error); ok {
		r1 = rf(ctx, namespaceName, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockService_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - req *secret.CreateSecretParams
func (_e *MockService_Expecter) CreateSecret(ctx interface{}, namespaceName interface{}, req interface{}) *MockService_CreateSecret_Call {
	return &MockService_CreateSecret_Call{Call: _e.mock.On("CreateSecret", ctx, namespaceName, req)}
}

func (_c *MockService_CreateSecret_Call) Run(run func(ctx context.Context, namespaceName string, req *secret.CreateSecretParams)) *MockService_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*secret.CreateSecretParams))
	})
	return _c
}

func (_c *MockService_CreateSecret_Call) Return(_a0 *secret.SecretInfo, _a1 error) *MockService_CreateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateSecret_Call) RunAndReturn(run func(context.Context, string, *secret.CreateSecretParams) (*secret.SecretInfo, error)) *MockService_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function with given fields: ctx, namespaceName, secretName
func (_m *MockService) DeleteSecret(ctx context.Context, namespaceName string, secretName string) error {
	ret := _m.Called(ctx, namespaceName, secretName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, secretName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockService_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - secretName string
func (_e *MockService_Expecter) DeleteSecret(ctx interface{}, namespaceName interface{}, secretName interface{}) *MockService_DeleteSecret_Call {
	return &MockService_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, namespaceName, secretName)}
}

func (_c *MockService_DeleteSecret_Call) Run(run func(ctx context.Context, namespaceName string, secretName string)) *MockService_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteSecret_Call) Return(_a0 error) *MockService_DeleteSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteSecret_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
