// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"
	secret "github.com/openchoreo/openchoreo/internal/openchoreo-api/services/secret"
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/api/core/v1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateSecret provides a mock function with given fields: ctx, namespaceName, req
func (_m *MockService) CreateSecret(ctx context.Context, namespaceName string, req *secret.CreateSecretParams) (*v1.Secret, error) {
	ret := _m.Called(ctx, namespaceName, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 *v1.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *secret.CreateSecretParams) (*v1.Secret, error)); ok {
		return rf(ctx, namespaceName, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *secret.CreateSecretParams) *v1.Secret); ok {
		r0 = rf(ctx, namespaceName, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *secret.CreateSecretParams) error); ok {
		r1 = rf(ctx, namespaceName, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockService_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - req *secret.CreateSecretParams
func (_e *MockService_Expecter) CreateSecret(ctx interface{}, namespaceName interface{}, req interface{}) *MockService_CreateSecret_Call {
	return &MockService_CreateSecret_Call{Call: _e.mock.On("CreateSecret", ctx, namespaceName, req)}
}

func (_c *MockService_CreateSecret_Call) Run(run func(ctx context.Context, namespaceName string, req *secret.CreateSecretParams)) *MockService_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*secret.CreateSecretParams))
	})
	return _c
}

func (_c *MockService_CreateSecret_Call) Return(_a0 *v1.Secret, _a1 error) *MockService_CreateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateSecret_Call) RunAndReturn(run func(context.Context, string, *secret.CreateSecretParams) (*v1.Secret, error)) *MockService_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function with given fields: ctx, namespaceName, secretName
func (_m *MockService) DeleteSecret(ctx context.Context, namespaceName string, secretName string) error {
	ret := _m.Called(ctx, namespaceName, secretName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, secretName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockService_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - secretName string
func (_e *MockService_Expecter) DeleteSecret(ctx interface{}, namespaceName interface{}, secretName interface{}) *MockService_DeleteSecret_Call {
	return &MockService_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, namespaceName, secretName)}
}

func (_c *MockService_DeleteSecret_Call) Run(run func(ctx context.Context, namespaceName string, secretName string)) *MockService_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteSecret_Call) Return(_a0 error) *MockService_DeleteSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteSecret_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function with given fields: ctx, namespaceName, secretName
func (_m *MockService) GetSecret(ctx context.Context, namespaceName string, secretName string) (*v1.Secret, error) {
	ret := _m.Called(ctx, namespaceName, secretName)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *v1.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1.Secret, error)); ok {
		return rf(ctx, namespaceName, secretName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1.Secret); ok {
		r0 = rf(ctx, namespaceName, secretName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, secretName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockService_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - secretName string
func (_e *MockService_Expecter) GetSecret(ctx interface{}, namespaceName interface{}, secretName interface{}) *MockService_GetSecret_Call {
	return &MockService_GetSecret_Call{Call: _e.mock.On("GetSecret", ctx, namespaceName, secretName)}
}

func (_c *MockService_GetSecret_Call) Run(run func(ctx context.Context, namespaceName string, secretName string)) *MockService_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetSecret_Call) Return(_a0 *v1.Secret, _a1 error) *MockService_GetSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetSecret_Call) RunAndReturn(run func(context.Context, string, string) (*v1.Secret, error)) *MockService_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecrets provides a mock function with given fields: ctx, namespaceName, opts
func (_m *MockService) ListSecrets(ctx context.Context, namespaceName string, opts services.ListOptions) (*services.ListResult[v1.Secret], error) {
	ret := _m.Called(ctx, namespaceName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 *services.ListResult[v1.Secret]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) (*services.ListResult[v1.Secret], error)); ok {
		return rf(ctx, namespaceName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) *services.ListResult[v1.Secret]); ok {
		r0 = rf(ctx, namespaceName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1.Secret])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecrets'
type MockService_ListSecrets_Call struct {
	*mock.Call
}

// ListSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListSecrets(ctx interface{}, namespaceName interface{}, opts interface{}) *MockService_ListSecrets_Call {
	return &MockService_ListSecrets_Call{Call: _e.mock.On("ListSecrets", ctx, namespaceName, opts)}
}

func (_c *MockService_ListSecrets_Call) Run(run func(ctx context.Context, namespaceName string, opts services.ListOptions)) *MockService_ListSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListSecrets_Call) Return(_a0 *services.ListResult[v1.Secret], _a1 error) *MockService_ListSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListSecrets_Call) RunAndReturn(run func(context.Context, string, services.ListOptions) (*services.ListResult[v1.Secret], error)) *MockService_ListSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecret provides a mock function with given fields: ctx, namespaceName, secretName, req
func (_m *MockService) UpdateSecret(ctx context.Context, namespaceName string, secretName string, req *secret.UpdateSecretParams) (*v1.Secret, error) {
	ret := _m.Called(ctx, namespaceName, secretName, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 *v1.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *secret.UpdateSecretParams) (*v1.Secret, error)); ok {
		return rf(ctx, namespaceName, secretName, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *secret.UpdateSecretParams) *v1.Secret); ok {
		r0 = rf(ctx, namespaceName, secretName, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *secret.UpdateSecretParams) error); ok {
		r1 = rf(ctx, namespaceName, secretName, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type MockService_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - secretName string
//   - req *secret.UpdateSecretParams
func (_e *MockService_Expecter) UpdateSecret(ctx interface{}, namespaceName interface{}, secretName interface{}, req interface{}) *MockService_UpdateSecret_Call {
	return &MockService_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret", ctx, namespaceName, secretName, req)}
}

func (_c *MockService_UpdateSecret_Call) Run(run func(ctx context.Context, namespaceName string, secretName string, req *secret.UpdateSecretParams)) *MockService_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*secret.UpdateSecretParams))
	})
	return _c
}

func (_c *MockService_UpdateSecret_Call) Return(_a0 *v1.Secret, _a1 error) *MockService_UpdateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateSecret_Call) RunAndReturn(run func(context.Context, string, string, *secret.UpdateSecretParams) (*v1.Secret, error)) *MockService_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
