// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateResourceType provides a mock function with given fields: ctx, namespaceName, rt
func (_m *MockService) CreateResourceType(ctx context.Context, namespaceName string, rt *v1alpha1.ResourceType) (*v1alpha1.ResourceType, error) {
	ret := _m.Called(ctx, namespaceName, rt)

	if len(ret) == 0 {
		panic("no return value specified for CreateResourceType")
	}

	var r0 *v1alpha1.ResourceType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ResourceType) (*v1alpha1.ResourceType, error)); ok {
		return rf(ctx, namespaceName, rt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ResourceType) *v1alpha1.ResourceType); ok {
		r0 = rf(ctx, namespaceName, rt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ResourceType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ResourceType) error); ok {
		r1 = rf(ctx, namespaceName, rt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateResourceType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResourceType'
type MockService_CreateResourceType_Call struct {
	*mock.Call
}

// CreateResourceType is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - rt *v1alpha1.ResourceType
func (_e *MockService_Expecter) CreateResourceType(ctx interface{}, namespaceName interface{}, rt interface{}) *MockService_CreateResourceType_Call {
	return &MockService_CreateResourceType_Call{Call: _e.mock.On("CreateResourceType", ctx, namespaceName, rt)}
}

func (_c *MockService_CreateResourceType_Call) Run(run func(ctx context.Context, namespaceName string, rt *v1alpha1.ResourceType)) *MockService_CreateResourceType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ResourceType))
	})
	return _c
}

func (_c *MockService_CreateResourceType_Call) Return(_a0 *v1alpha1.ResourceType, _a1 error) *MockService_CreateResourceType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateResourceType_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ResourceType) (*v1alpha1.ResourceType, error)) *MockService_CreateResourceType_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResourceType provides a mock function with given fields: ctx, namespaceName, rtName
func (_m *MockService) DeleteResourceType(ctx context.Context, namespaceName string, rtName string) error {
	ret := _m.Called(ctx, namespaceName, rtName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResourceType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, rtName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteResourceType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResourceType'
type MockService_DeleteResourceType_Call struct {
	*mock.Call
}

// DeleteResourceType is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - rtName string
func (_e *MockService_Expecter) DeleteResourceType(ctx interface{}, namespaceName interface{}, rtName interface{}) *MockService_DeleteResourceType_Call {
	return &MockService_DeleteResourceType_Call{Call: _e.mock.On("DeleteResourceType", ctx, namespaceName, rtName)}
}

func (_c *MockService_DeleteResourceType_Call) Run(run func(ctx context.Context, namespaceName string, rtName string)) *MockService_DeleteResourceType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteResourceType_Call) Return(_a0 error) *MockService_DeleteResourceType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteResourceType_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteResourceType_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceType provides a mock function with given fields: ctx, namespaceName, rtName
func (_m *MockService) GetResourceType(ctx context.Context, namespaceName string, rtName string) (*v1alpha1.ResourceType, error) {
	ret := _m.Called(ctx, namespaceName, rtName)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceType")
	}

	var r0 *v1alpha1.ResourceType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.ResourceType, error)); ok {
		return rf(ctx, namespaceName, rtName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.ResourceType); ok {
		r0 = rf(ctx, namespaceName, rtName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ResourceType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, rtName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetResourceType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceType'
type MockService_GetResourceType_Call struct {
	*mock.Call
}

// GetResourceType is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - rtName string
func (_e *MockService_Expecter) GetResourceType(ctx interface{}, namespaceName interface{}, rtName interface{}) *MockService_GetResourceType_Call {
	return &MockService_GetResourceType_Call{Call: _e.mock.On("GetResourceType", ctx, namespaceName, rtName)}
}

func (_c *MockService_GetResourceType_Call) Run(run func(ctx context.Context, namespaceName string, rtName string)) *MockService_GetResourceType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetResourceType_Call) Return(_a0 *v1alpha1.ResourceType, _a1 error) *MockService_GetResourceType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetResourceType_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.ResourceType, error)) *MockService_GetResourceType_Call {
	_c.Call.Return(run)
	return _c
}

// GetResourceTypeSchema provides a mock function with given fields: ctx, namespaceName, rtName
func (_m *MockService) GetResourceTypeSchema(ctx context.Context, namespaceName string, rtName string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, namespaceName, rtName)

	if len(ret) == 0 {
		panic("no return value specified for GetResourceTypeSchema")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (map[string]interface{}, error)); ok {
		return rf(ctx, namespaceName, rtName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) map[string]interface{}); ok {
		r0 = rf(ctx, namespaceName, rtName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, rtName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetResourceTypeSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResourceTypeSchema'
type MockService_GetResourceTypeSchema_Call struct {
	*mock.Call
}

// GetResourceTypeSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - rtName string
func (_e *MockService_Expecter) GetResourceTypeSchema(ctx interface{}, namespaceName interface{}, rtName interface{}) *MockService_GetResourceTypeSchema_Call {
	return &MockService_GetResourceTypeSchema_Call{Call: _e.mock.On("GetResourceTypeSchema", ctx, namespaceName, rtName)}
}

func (_c *MockService_GetResourceTypeSchema_Call) Run(run func(ctx context.Context, namespaceName string, rtName string)) *MockService_GetResourceTypeSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetResourceTypeSchema_Call) Return(_a0 map[string]interface{}, _a1 error) *MockService_GetResourceTypeSchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetResourceTypeSchema_Call) RunAndReturn(run func(context.Context, string, string) (map[string]interface{}, error)) *MockService_GetResourceTypeSchema_Call {
	_c.Call.Return(run)
	return _c
}

// ListResourceTypes provides a mock function with given fields: ctx, namespaceName, opts
func (_m *MockService) ListResourceTypes(ctx context.Context, namespaceName string, opts services.ListOptions) (*services.ListResult[v1alpha1.ResourceType], error) {
	ret := _m.Called(ctx, namespaceName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListResourceTypes")
	}

	var r0 *services.ListResult[v1alpha1.ResourceType]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.ResourceType], error)); ok {
		return rf(ctx, namespaceName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) *services.ListResult[v1alpha1.ResourceType]); ok {
		r0 = rf(ctx, namespaceName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.ResourceType])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListResourceTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListResourceTypes'
type MockService_ListResourceTypes_Call struct {
	*mock.Call
}

// ListResourceTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListResourceTypes(ctx interface{}, namespaceName interface{}, opts interface{}) *MockService_ListResourceTypes_Call {
	return &MockService_ListResourceTypes_Call{Call: _e.mock.On("ListResourceTypes", ctx, namespaceName, opts)}
}

func (_c *MockService_ListResourceTypes_Call) Run(run func(ctx context.Context, namespaceName string, opts services.ListOptions)) *MockService_ListResourceTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListResourceTypes_Call) Return(_a0 *services.ListResult[v1alpha1.ResourceType], _a1 error) *MockService_ListResourceTypes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListResourceTypes_Call) RunAndReturn(run func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.ResourceType], error)) *MockService_ListResourceTypes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateResourceType provides a mock function with given fields: ctx, namespaceName, rt
func (_m *MockService) UpdateResourceType(ctx context.Context, namespaceName string, rt *v1alpha1.ResourceType) (*v1alpha1.ResourceType, error) {
	ret := _m.Called(ctx, namespaceName, rt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateResourceType")
	}

	var r0 *v1alpha1.ResourceType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ResourceType) (*v1alpha1.ResourceType, error)); ok {
		return rf(ctx, namespaceName, rt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ResourceType) *v1alpha1.ResourceType); ok {
		r0 = rf(ctx, namespaceName, rt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ResourceType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ResourceType) error); ok {
		r1 = rf(ctx, namespaceName, rt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateResourceType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateResourceType'
type MockService_UpdateResourceType_Call struct {
	*mock.Call
}

// UpdateResourceType is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - rt *v1alpha1.ResourceType
func (_e *MockService_Expecter) UpdateResourceType(ctx interface{}, namespaceName interface{}, rt interface{}) *MockService_UpdateResourceType_Call {
	return &MockService_UpdateResourceType_Call{Call: _e.mock.On("UpdateResourceType", ctx, namespaceName, rt)}
}

func (_c *MockService_UpdateResourceType_Call) Run(run func(ctx context.Context, namespaceName string, rt *v1alpha1.ResourceType)) *MockService_UpdateResourceType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ResourceType))
	})
	return _c
}

func (_c *MockService_UpdateResourceType_Call) Return(_a0 *v1alpha1.ResourceType, _a1 error) *MockService_UpdateResourceType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateResourceType_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ResourceType) (*v1alpha1.ResourceType, error)) *MockService_UpdateResourceType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
