// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	client "sigs.k8s.io/controller-runtime/pkg/client"

	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockObservabilityPlaneClientProvider is an autogenerated mock type for the ObservabilityPlaneClientProvider type
type MockObservabilityPlaneClientProvider struct {
	mock.Mock
}

type MockObservabilityPlaneClientProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObservabilityPlaneClientProvider) EXPECT() *MockObservabilityPlaneClientProvider_Expecter {
	return &MockObservabilityPlaneClientProvider_Expecter{mock: &_m.Mock}
}

// ClusterObservabilityPlaneClient provides a mock function with given fields: cop
func (_m *MockObservabilityPlaneClientProvider) ClusterObservabilityPlaneClient(cop *v1alpha1.ClusterObservabilityPlane) (client.Client, error) {
	ret := _m.Called(cop)

	if len(ret) == 0 {
		panic("no return value specified for ClusterObservabilityPlaneClient")
	}

	var r0 client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.ClusterObservabilityPlane) (client.Client, error)); ok {
		return rf(cop)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.ClusterObservabilityPlane) client.Client); ok {
		r0 = rf(cop)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.ClusterObservabilityPlane) error); ok {
		r1 = rf(cop)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObservabilityPlaneClientProvider_ClusterObservabilityPlaneClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterObservabilityPlaneClient'
type MockObservabilityPlaneClientProvider_ClusterObservabilityPlaneClient_Call struct {
	*mock.Call
}

// ClusterObservabilityPlaneClient is a helper method to define mock.On call
//   - cop *v1alpha1.ClusterObservabilityPlane
func (_e *MockObservabilityPlaneClientProvider_Expecter) ClusterObservabilityPlaneClient(cop interface{}) *MockObservabilityPlaneClientProvider_ClusterObservabilityPlaneClient_Call {
	return &MockObservabilityPlaneClientProvider_ClusterObservabilityPlaneClient_Call{Call: _e.mock.On("ClusterObservabilityPlaneClient", cop)}
}

func (_c *MockObservabilityPlaneClientProvider_ClusterObservabilityPlaneClient_Call) Run(run func(cop *v1alpha1.ClusterObservabilityPlane)) *MockObservabilityPlaneClientProvider_ClusterObservabilityPlaneClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1alpha1.ClusterObservabilityPlane))
	})
	return _c
}

func (_c *MockObservabilityPlaneClientProvider_ClusterObservabilityPlaneClient_Call) Return(_a0 client.Client, _a1 error) *MockObservabilityPlaneClientProvider_ClusterObservabilityPlaneClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObservabilityPlaneClientProvider_ClusterObservabilityPlaneClient_Call) RunAndReturn(run func(*v1alpha1.ClusterObservabilityPlane) (client.Client, error)) *MockObservabilityPlaneClientProvider_ClusterObservabilityPlaneClient_Call {
	_c.Call.Return(run)
	return _c
}

// ObservabilityPlaneClient provides a mock function with given fields: op
func (_m *MockObservabilityPlaneClientProvider) ObservabilityPlaneClient(op *v1alpha1.ObservabilityPlane) (client.Client, error) {
	ret := _m.Called(op)

	if len(ret) == 0 {
		panic("no return value specified for ObservabilityPlaneClient")
	}

	var r0 client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.ObservabilityPlane) (client.Client, error)); ok {
		return rf(op)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.ObservabilityPlane) client.Client); ok {
		r0 = rf(op)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.ObservabilityPlane) error); ok {
		r1 = rf(op)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockObservabilityPlaneClientProvider_ObservabilityPlaneClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObservabilityPlaneClient'
type MockObservabilityPlaneClientProvider_ObservabilityPlaneClient_Call struct {
	*mock.Call
}

// ObservabilityPlaneClient is a helper method to define mock.On call
//   - op *v1alpha1.ObservabilityPlane
func (_e *MockObservabilityPlaneClientProvider_Expecter) ObservabilityPlaneClient(op interface{}) *MockObservabilityPlaneClientProvider_ObservabilityPlaneClient_Call {
	return &MockObservabilityPlaneClientProvider_ObservabilityPlaneClient_Call{Call: _e.mock.On("ObservabilityPlaneClient", op)}
}

func (_c *MockObservabilityPlaneClientProvider_ObservabilityPlaneClient_Call) Run(run func(op *v1alpha1.ObservabilityPlane)) *MockObservabilityPlaneClientProvider_ObservabilityPlaneClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1alpha1.ObservabilityPlane))
	})
	return _c
}

func (_c *MockObservabilityPlaneClientProvider_ObservabilityPlaneClient_Call) Return(_a0 client.Client, _a1 error) *MockObservabilityPlaneClientProvider_ObservabilityPlaneClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockObservabilityPlaneClientProvider_ObservabilityPlaneClient_Call) RunAndReturn(run func(*v1alpha1.ObservabilityPlane) (client.Client, error)) *MockObservabilityPlaneClientProvider_ObservabilityPlaneClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockObservabilityPlaneClientProvider creates a new instance of MockObservabilityPlaneClientProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObservabilityPlaneClientProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObservabilityPlaneClientProvider {
	mock := &MockObservabilityPlaneClientProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
