// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	client "sigs.k8s.io/controller-runtime/pkg/client"

	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockPlaneClientProvider is an autogenerated mock type for the PlaneClientProvider type
type MockPlaneClientProvider struct {
	mock.Mock
}

type MockPlaneClientProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlaneClientProvider) EXPECT() *MockPlaneClientProvider_Expecter {
	return &MockPlaneClientProvider_Expecter{mock: &_m.Mock}
}

// ClusterDataPlaneClient provides a mock function with given fields: cdp
func (_m *MockPlaneClientProvider) ClusterDataPlaneClient(cdp *v1alpha1.ClusterDataPlane) (client.Client, error) {
	ret := _m.Called(cdp)

	if len(ret) == 0 {
		panic("no return value specified for ClusterDataPlaneClient")
	}

	var r0 client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.ClusterDataPlane) (client.Client, error)); ok {
		return rf(cdp)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.ClusterDataPlane) client.Client); ok {
		r0 = rf(cdp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.ClusterDataPlane) error); ok {
		r1 = rf(cdp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaneClientProvider_ClusterDataPlaneClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterDataPlaneClient'
type MockPlaneClientProvider_ClusterDataPlaneClient_Call struct {
	*mock.Call
}

// ClusterDataPlaneClient is a helper method to define mock.On call
//   - cdp *v1alpha1.ClusterDataPlane
func (_e *MockPlaneClientProvider_Expecter) ClusterDataPlaneClient(cdp interface{}) *MockPlaneClientProvider_ClusterDataPlaneClient_Call {
	return &MockPlaneClientProvider_ClusterDataPlaneClient_Call{Call: _e.mock.On("ClusterDataPlaneClient", cdp)}
}

func (_c *MockPlaneClientProvider_ClusterDataPlaneClient_Call) Run(run func(cdp *v1alpha1.ClusterDataPlane)) *MockPlaneClientProvider_ClusterDataPlaneClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1alpha1.ClusterDataPlane))
	})
	return _c
}

func (_c *MockPlaneClientProvider_ClusterDataPlaneClient_Call) Return(_a0 client.Client, _a1 error) *MockPlaneClientProvider_ClusterDataPlaneClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaneClientProvider_ClusterDataPlaneClient_Call) RunAndReturn(run func(*v1alpha1.ClusterDataPlane) (client.Client, error)) *MockPlaneClientProvider_ClusterDataPlaneClient_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterObservabilityPlaneClient provides a mock function with given fields: cop
func (_m *MockPlaneClientProvider) ClusterObservabilityPlaneClient(cop *v1alpha1.ClusterObservabilityPlane) (client.Client, error) {
	ret := _m.Called(cop)

	if len(ret) == 0 {
		panic("no return value specified for ClusterObservabilityPlaneClient")
	}

	var r0 client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.ClusterObservabilityPlane) (client.Client, error)); ok {
		return rf(cop)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.ClusterObservabilityPlane) client.Client); ok {
		r0 = rf(cop)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.ClusterObservabilityPlane) error); ok {
		r1 = rf(cop)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaneClientProvider_ClusterObservabilityPlaneClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterObservabilityPlaneClient'
type MockPlaneClientProvider_ClusterObservabilityPlaneClient_Call struct {
	*mock.Call
}

// ClusterObservabilityPlaneClient is a helper method to define mock.On call
//   - cop *v1alpha1.ClusterObservabilityPlane
func (_e *MockPlaneClientProvider_Expecter) ClusterObservabilityPlaneClient(cop interface{}) *MockPlaneClientProvider_ClusterObservabilityPlaneClient_Call {
	return &MockPlaneClientProvider_ClusterObservabilityPlaneClient_Call{Call: _e.mock.On("ClusterObservabilityPlaneClient", cop)}
}

func (_c *MockPlaneClientProvider_ClusterObservabilityPlaneClient_Call) Run(run func(cop *v1alpha1.ClusterObservabilityPlane)) *MockPlaneClientProvider_ClusterObservabilityPlaneClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1alpha1.ClusterObservabilityPlane))
	})
	return _c
}

func (_c *MockPlaneClientProvider_ClusterObservabilityPlaneClient_Call) Return(_a0 client.Client, _a1 error) *MockPlaneClientProvider_ClusterObservabilityPlaneClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaneClientProvider_ClusterObservabilityPlaneClient_Call) RunAndReturn(run func(*v1alpha1.ClusterObservabilityPlane) (client.Client, error)) *MockPlaneClientProvider_ClusterObservabilityPlaneClient_Call {
	_c.Call.Return(run)
	return _c
}

// ClusterWorkflowPlaneClient provides a mock function with given fields: cwp
func (_m *MockPlaneClientProvider) ClusterWorkflowPlaneClient(cwp *v1alpha1.ClusterWorkflowPlane) (client.Client, error) {
	ret := _m.Called(cwp)

	if len(ret) == 0 {
		panic("no return value specified for ClusterWorkflowPlaneClient")
	}

	var r0 client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.ClusterWorkflowPlane) (client.Client, error)); ok {
		return rf(cwp)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.ClusterWorkflowPlane) client.Client); ok {
		r0 = rf(cwp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.ClusterWorkflowPlane) error); ok {
		r1 = rf(cwp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaneClientProvider_ClusterWorkflowPlaneClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClusterWorkflowPlaneClient'
type MockPlaneClientProvider_ClusterWorkflowPlaneClient_Call struct {
	*mock.Call
}

// ClusterWorkflowPlaneClient is a helper method to define mock.On call
//   - cwp *v1alpha1.ClusterWorkflowPlane
func (_e *MockPlaneClientProvider_Expecter) ClusterWorkflowPlaneClient(cwp interface{}) *MockPlaneClientProvider_ClusterWorkflowPlaneClient_Call {
	return &MockPlaneClientProvider_ClusterWorkflowPlaneClient_Call{Call: _e.mock.On("ClusterWorkflowPlaneClient", cwp)}
}

func (_c *MockPlaneClientProvider_ClusterWorkflowPlaneClient_Call) Run(run func(cwp *v1alpha1.ClusterWorkflowPlane)) *MockPlaneClientProvider_ClusterWorkflowPlaneClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1alpha1.ClusterWorkflowPlane))
	})
	return _c
}

func (_c *MockPlaneClientProvider_ClusterWorkflowPlaneClient_Call) Return(_a0 client.Client, _a1 error) *MockPlaneClientProvider_ClusterWorkflowPlaneClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaneClientProvider_ClusterWorkflowPlaneClient_Call) RunAndReturn(run func(*v1alpha1.ClusterWorkflowPlane) (client.Client, error)) *MockPlaneClientProvider_ClusterWorkflowPlaneClient_Call {
	_c.Call.Return(run)
	return _c
}

// DataPlaneClient provides a mock function with given fields: dp
func (_m *MockPlaneClientProvider) DataPlaneClient(dp *v1alpha1.DataPlane) (client.Client, error) {
	ret := _m.Called(dp)

	if len(ret) == 0 {
		panic("no return value specified for DataPlaneClient")
	}

	var r0 client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.DataPlane) (client.Client, error)); ok {
		return rf(dp)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.DataPlane) client.Client); ok {
		r0 = rf(dp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.DataPlane) error); ok {
		r1 = rf(dp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaneClientProvider_DataPlaneClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DataPlaneClient'
type MockPlaneClientProvider_DataPlaneClient_Call struct {
	*mock.Call
}

// DataPlaneClient is a helper method to define mock.On call
//   - dp *v1alpha1.DataPlane
func (_e *MockPlaneClientProvider_Expecter) DataPlaneClient(dp interface{}) *MockPlaneClientProvider_DataPlaneClient_Call {
	return &MockPlaneClientProvider_DataPlaneClient_Call{Call: _e.mock.On("DataPlaneClient", dp)}
}

func (_c *MockPlaneClientProvider_DataPlaneClient_Call) Run(run func(dp *v1alpha1.DataPlane)) *MockPlaneClientProvider_DataPlaneClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1alpha1.DataPlane))
	})
	return _c
}

func (_c *MockPlaneClientProvider_DataPlaneClient_Call) Return(_a0 client.Client, _a1 error) *MockPlaneClientProvider_DataPlaneClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaneClientProvider_DataPlaneClient_Call) RunAndReturn(run func(*v1alpha1.DataPlane) (client.Client, error)) *MockPlaneClientProvider_DataPlaneClient_Call {
	_c.Call.Return(run)
	return _c
}

// ObservabilityPlaneClient provides a mock function with given fields: op
func (_m *MockPlaneClientProvider) ObservabilityPlaneClient(op *v1alpha1.ObservabilityPlane) (client.Client, error) {
	ret := _m.Called(op)

	if len(ret) == 0 {
		panic("no return value specified for ObservabilityPlaneClient")
	}

	var r0 client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.ObservabilityPlane) (client.Client, error)); ok {
		return rf(op)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.ObservabilityPlane) client.Client); ok {
		r0 = rf(op)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.ObservabilityPlane) error); ok {
		r1 = rf(op)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaneClientProvider_ObservabilityPlaneClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ObservabilityPlaneClient'
type MockPlaneClientProvider_ObservabilityPlaneClient_Call struct {
	*mock.Call
}

// ObservabilityPlaneClient is a helper method to define mock.On call
//   - op *v1alpha1.ObservabilityPlane
func (_e *MockPlaneClientProvider_Expecter) ObservabilityPlaneClient(op interface{}) *MockPlaneClientProvider_ObservabilityPlaneClient_Call {
	return &MockPlaneClientProvider_ObservabilityPlaneClient_Call{Call: _e.mock.On("ObservabilityPlaneClient", op)}
}

func (_c *MockPlaneClientProvider_ObservabilityPlaneClient_Call) Run(run func(op *v1alpha1.ObservabilityPlane)) *MockPlaneClientProvider_ObservabilityPlaneClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1alpha1.ObservabilityPlane))
	})
	return _c
}

func (_c *MockPlaneClientProvider_ObservabilityPlaneClient_Call) Return(_a0 client.Client, _a1 error) *MockPlaneClientProvider_ObservabilityPlaneClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaneClientProvider_ObservabilityPlaneClient_Call) RunAndReturn(run func(*v1alpha1.ObservabilityPlane) (client.Client, error)) *MockPlaneClientProvider_ObservabilityPlaneClient_Call {
	_c.Call.Return(run)
	return _c
}

// WorkflowPlaneClient provides a mock function with given fields: wp
func (_m *MockPlaneClientProvider) WorkflowPlaneClient(wp *v1alpha1.WorkflowPlane) (client.Client, error) {
	ret := _m.Called(wp)

	if len(ret) == 0 {
		panic("no return value specified for WorkflowPlaneClient")
	}

	var r0 client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1alpha1.WorkflowPlane) (client.Client, error)); ok {
		return rf(wp)
	}
	if rf, ok := ret.Get(0).(func(*v1alpha1.WorkflowPlane) client.Client); ok {
		r0 = rf(wp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(*v1alpha1.WorkflowPlane) error); ok {
		r1 = rf(wp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlaneClientProvider_WorkflowPlaneClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WorkflowPlaneClient'
type MockPlaneClientProvider_WorkflowPlaneClient_Call struct {
	*mock.Call
}

// WorkflowPlaneClient is a helper method to define mock.On call
//   - wp *v1alpha1.WorkflowPlane
func (_e *MockPlaneClientProvider_Expecter) WorkflowPlaneClient(wp interface{}) *MockPlaneClientProvider_WorkflowPlaneClient_Call {
	return &MockPlaneClientProvider_WorkflowPlaneClient_Call{Call: _e.mock.On("WorkflowPlaneClient", wp)}
}

func (_c *MockPlaneClientProvider_WorkflowPlaneClient_Call) Run(run func(wp *v1alpha1.WorkflowPlane)) *MockPlaneClientProvider_WorkflowPlaneClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*v1alpha1.WorkflowPlane))
	})
	return _c
}

func (_c *MockPlaneClientProvider_WorkflowPlaneClient_Call) Return(_a0 client.Client, _a1 error) *MockPlaneClientProvider_WorkflowPlaneClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlaneClientProvider_WorkflowPlaneClient_Call) RunAndReturn(run func(*v1alpha1.WorkflowPlane) (client.Client, error)) *MockPlaneClientProvider_WorkflowPlaneClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlaneClientProvider creates a new instance of MockPlaneClientProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlaneClientProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlaneClientProvider {
	mock := &MockPlaneClientProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
