// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateDataPlane provides a mock function with given fields: ctx, namespaceName, dp
func (_m *MockService) CreateDataPlane(ctx context.Context, namespaceName string, dp *v1alpha1.DataPlane) (*v1alpha1.DataPlane, error) {
	ret := _m.Called(ctx, namespaceName, dp)

	if len(ret) == 0 {
		panic("no return value specified for CreateDataPlane")
	}

	var r0 *v1alpha1.DataPlane
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.DataPlane) (*v1alpha1.DataPlane, error)); ok {
		return rf(ctx, namespaceName, dp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.DataPlane) *v1alpha1.DataPlane); ok {
		r0 = rf(ctx, namespaceName, dp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.DataPlane)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.DataPlane) error); ok {
		r1 = rf(ctx, namespaceName, dp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateDataPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDataPlane'
type MockService_CreateDataPlane_Call struct {
	*mock.Call
}

// CreateDataPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - dp *v1alpha1.DataPlane
func (_e *MockService_Expecter) CreateDataPlane(ctx interface{}, namespaceName interface{}, dp interface{}) *MockService_CreateDataPlane_Call {
	return &MockService_CreateDataPlane_Call{Call: _e.mock.On("CreateDataPlane", ctx, namespaceName, dp)}
}

func (_c *MockService_CreateDataPlane_Call) Run(run func(ctx context.Context, namespaceName string, dp *v1alpha1.DataPlane)) *MockService_CreateDataPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.DataPlane))
	})
	return _c
}

func (_c *MockService_CreateDataPlane_Call) Return(_a0 *v1alpha1.DataPlane, _a1 error) *MockService_CreateDataPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateDataPlane_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.DataPlane) (*v1alpha1.DataPlane, error)) *MockService_CreateDataPlane_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDataPlane provides a mock function with given fields: ctx, namespaceName, dpName
func (_m *MockService) DeleteDataPlane(ctx context.Context, namespaceName string, dpName string) error {
	ret := _m.Called(ctx, namespaceName, dpName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDataPlane")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, dpName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteDataPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDataPlane'
type MockService_DeleteDataPlane_Call struct {
	*mock.Call
}

// DeleteDataPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - dpName string
func (_e *MockService_Expecter) DeleteDataPlane(ctx interface{}, namespaceName interface{}, dpName interface{}) *MockService_DeleteDataPlane_Call {
	return &MockService_DeleteDataPlane_Call{Call: _e.mock.On("DeleteDataPlane", ctx, namespaceName, dpName)}
}

func (_c *MockService_DeleteDataPlane_Call) Run(run func(ctx context.Context, namespaceName string, dpName string)) *MockService_DeleteDataPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteDataPlane_Call) Return(_a0 error) *MockService_DeleteDataPlane_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteDataPlane_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteDataPlane_Call {
	_c.Call.Return(run)
	return _c
}

// GetDataPlane provides a mock function with given fields: ctx, namespaceName, dpName
func (_m *MockService) GetDataPlane(ctx context.Context, namespaceName string, dpName string) (*v1alpha1.DataPlane, error) {
	ret := _m.Called(ctx, namespaceName, dpName)

	if len(ret) == 0 {
		panic("no return value specified for GetDataPlane")
	}

	var r0 *v1alpha1.DataPlane
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.DataPlane, error)); ok {
		return rf(ctx, namespaceName, dpName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.DataPlane); ok {
		r0 = rf(ctx, namespaceName, dpName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.DataPlane)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, dpName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetDataPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataPlane'
type MockService_GetDataPlane_Call struct {
	*mock.Call
}

// GetDataPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - dpName string
func (_e *MockService_Expecter) GetDataPlane(ctx interface{}, namespaceName interface{}, dpName interface{}) *MockService_GetDataPlane_Call {
	return &MockService_GetDataPlane_Call{Call: _e.mock.On("GetDataPlane", ctx, namespaceName, dpName)}
}

func (_c *MockService_GetDataPlane_Call) Run(run func(ctx context.Context, namespaceName string, dpName string)) *MockService_GetDataPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetDataPlane_Call) Return(_a0 *v1alpha1.DataPlane, _a1 error) *MockService_GetDataPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetDataPlane_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.DataPlane, error)) *MockService_GetDataPlane_Call {
	_c.Call.Return(run)
	return _c
}

// ListDataPlanes provides a mock function with given fields: ctx, namespaceName, opts
func (_m *MockService) ListDataPlanes(ctx context.Context, namespaceName string, opts services.ListOptions) (*services.ListResult[v1alpha1.DataPlane], error) {
	ret := _m.Called(ctx, namespaceName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListDataPlanes")
	}

	var r0 *services.ListResult[v1alpha1.DataPlane]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.DataPlane], error)); ok {
		return rf(ctx, namespaceName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) *services.ListResult[v1alpha1.DataPlane]); ok {
		r0 = rf(ctx, namespaceName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.DataPlane])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListDataPlanes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDataPlanes'
type MockService_ListDataPlanes_Call struct {
	*mock.Call
}

// ListDataPlanes is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListDataPlanes(ctx interface{}, namespaceName interface{}, opts interface{}) *MockService_ListDataPlanes_Call {
	return &MockService_ListDataPlanes_Call{Call: _e.mock.On("ListDataPlanes", ctx, namespaceName, opts)}
}

func (_c *MockService_ListDataPlanes_Call) Run(run func(ctx context.Context, namespaceName string, opts services.ListOptions)) *MockService_ListDataPlanes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListDataPlanes_Call) Return(_a0 *services.ListResult[v1alpha1.DataPlane], _a1 error) *MockService_ListDataPlanes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListDataPlanes_Call) RunAndReturn(run func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.DataPlane], error)) *MockService_ListDataPlanes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDataPlane provides a mock function with given fields: ctx, namespaceName, dp
func (_m *MockService) UpdateDataPlane(ctx context.Context, namespaceName string, dp *v1alpha1.DataPlane) (*v1alpha1.DataPlane, error) {
	ret := _m.Called(ctx, namespaceName, dp)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataPlane")
	}

	var r0 *v1alpha1.DataPlane
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.DataPlane) (*v1alpha1.DataPlane, error)); ok {
		return rf(ctx, namespaceName, dp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.DataPlane) *v1alpha1.DataPlane); ok {
		r0 = rf(ctx, namespaceName, dp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.DataPlane)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.DataPlane) error); ok {
		r1 = rf(ctx, namespaceName, dp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateDataPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDataPlane'
type MockService_UpdateDataPlane_Call struct {
	*mock.Call
}

// UpdateDataPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - dp *v1alpha1.DataPlane
func (_e *MockService_Expecter) UpdateDataPlane(ctx interface{}, namespaceName interface{}, dp interface{}) *MockService_UpdateDataPlane_Call {
	return &MockService_UpdateDataPlane_Call{Call: _e.mock.On("UpdateDataPlane", ctx, namespaceName, dp)}
}

func (_c *MockService_UpdateDataPlane_Call) Run(run func(ctx context.Context, namespaceName string, dp *v1alpha1.DataPlane)) *MockService_UpdateDataPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.DataPlane))
	})
	return _c
}

func (_c *MockService_UpdateDataPlane_Call) Return(_a0 *v1alpha1.DataPlane, _a1 error) *MockService_UpdateDataPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateDataPlane_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.DataPlane) (*v1alpha1.DataPlane, error)) *MockService_UpdateDataPlane_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
