// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/openchoreo/openchoreo/internal/openchoreo-api/api/gen"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteObservabilityPlane provides a mock function with given fields: ctx, namespaceName, observabilityPlaneName
func (_m *MockClient) DeleteObservabilityPlane(ctx context.Context, namespaceName string, observabilityPlaneName string) error {
	ret := _m.Called(ctx, namespaceName, observabilityPlaneName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObservabilityPlane")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, observabilityPlaneName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeleteObservabilityPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObservabilityPlane'
type MockClient_DeleteObservabilityPlane_Call struct {
	*mock.Call
}

// DeleteObservabilityPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - observabilityPlaneName string
func (_e *MockClient_Expecter) DeleteObservabilityPlane(ctx interface{}, namespaceName interface{}, observabilityPlaneName interface{}) *MockClient_DeleteObservabilityPlane_Call {
	return &MockClient_DeleteObservabilityPlane_Call{Call: _e.mock.On("DeleteObservabilityPlane", ctx, namespaceName, observabilityPlaneName)}
}

func (_c *MockClient_DeleteObservabilityPlane_Call) Run(run func(ctx context.Context, namespaceName string, observabilityPlaneName string)) *MockClient_DeleteObservabilityPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_DeleteObservabilityPlane_Call) Return(_a0 error) *MockClient_DeleteObservabilityPlane_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeleteObservabilityPlane_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_DeleteObservabilityPlane_Call {
	_c.Call.Return(run)
	return _c
}

// GetObservabilityPlane provides a mock function with given fields: ctx, namespaceName, observabilityPlaneName
func (_m *MockClient) GetObservabilityPlane(ctx context.Context, namespaceName string, observabilityPlaneName string) (*gen.ObservabilityPlane, error) {
	ret := _m.Called(ctx, namespaceName, observabilityPlaneName)

	if len(ret) == 0 {
		panic("no return value specified for GetObservabilityPlane")
	}

	var r0 *gen.ObservabilityPlane
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.ObservabilityPlane, error)); ok {
		return rf(ctx, namespaceName, observabilityPlaneName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.ObservabilityPlane); ok {
		r0 = rf(ctx, namespaceName, observabilityPlaneName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ObservabilityPlane)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, observabilityPlaneName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetObservabilityPlane_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObservabilityPlane'
type MockClient_GetObservabilityPlane_Call struct {
	*mock.Call
}

// GetObservabilityPlane is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - observabilityPlaneName string
func (_e *MockClient_Expecter) GetObservabilityPlane(ctx interface{}, namespaceName interface{}, observabilityPlaneName interface{}) *MockClient_GetObservabilityPlane_Call {
	return &MockClient_GetObservabilityPlane_Call{Call: _e.mock.On("GetObservabilityPlane", ctx, namespaceName, observabilityPlaneName)}
}

func (_c *MockClient_GetObservabilityPlane_Call) Run(run func(ctx context.Context, namespaceName string, observabilityPlaneName string)) *MockClient_GetObservabilityPlane_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetObservabilityPlane_Call) Return(_a0 *gen.ObservabilityPlane, _a1 error) *MockClient_GetObservabilityPlane_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetObservabilityPlane_Call) RunAndReturn(run func(context.Context, string, string) (*gen.ObservabilityPlane, error)) *MockClient_GetObservabilityPlane_Call {
	_c.Call.Return(run)
	return _c
}

// ListObservabilityPlanes provides a mock function with given fields: ctx, namespaceName, params
func (_m *MockClient) ListObservabilityPlanes(ctx context.Context, namespaceName string, params *gen.ListObservabilityPlanesParams) (*gen.ObservabilityPlaneList, error) {
	ret := _m.Called(ctx, namespaceName, params)

	if len(ret) == 0 {
		panic("no return value specified for ListObservabilityPlanes")
	}

	var r0 *gen.ObservabilityPlaneList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListObservabilityPlanesParams) (*gen.ObservabilityPlaneList, error)); ok {
		return rf(ctx, namespaceName, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListObservabilityPlanesParams) *gen.ObservabilityPlaneList); ok {
		r0 = rf(ctx, namespaceName, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ObservabilityPlaneList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *gen.ListObservabilityPlanesParams) error); ok {
		r1 = rf(ctx, namespaceName, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListObservabilityPlanes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObservabilityPlanes'
type MockClient_ListObservabilityPlanes_Call struct {
	*mock.Call
}

// ListObservabilityPlanes is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - params *gen.ListObservabilityPlanesParams
func (_e *MockClient_Expecter) ListObservabilityPlanes(ctx interface{}, namespaceName interface{}, params interface{}) *MockClient_ListObservabilityPlanes_Call {
	return &MockClient_ListObservabilityPlanes_Call{Call: _e.mock.On("ListObservabilityPlanes", ctx, namespaceName, params)}
}

func (_c *MockClient_ListObservabilityPlanes_Call) Run(run func(ctx context.Context, namespaceName string, params *gen.ListObservabilityPlanesParams)) *MockClient_ListObservabilityPlanes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*gen.ListObservabilityPlanesParams))
	})
	return _c
}

func (_c *MockClient_ListObservabilityPlanes_Call) Return(_a0 *gen.ObservabilityPlaneList, _a1 error) *MockClient_ListObservabilityPlanes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListObservabilityPlanes_Call) RunAndReturn(run func(context.Context, string, *gen.ListObservabilityPlanesParams) (*gen.ObservabilityPlaneList, error)) *MockClient_ListObservabilityPlanes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
