# permissions for end users to edit clusterresourcetypes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openchoreo
    app.kubernetes.io/managed-by: kustomize
  name: clusterresourcetype-editor-role
rules:
- apiGroups:
  - openchoreo.dev
  resources:
  - clusterresourcetypes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openchoreo.dev
  resources:
  - clusterresourcetypes/status
  verbs:
  - get
