// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"
	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateWorkload provides a mock function with given fields: ctx, namespaceName, w
func (_m *MockService) CreateWorkload(ctx context.Context, namespaceName string, w *v1alpha1.Workload) (*v1alpha1.Workload, error) {
	ret := _m.Called(ctx, namespaceName, w)

	if len(ret) == 0 {
		panic("no return value specified for CreateWorkload")
	}

	var r0 *v1alpha1.Workload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Workload) (*v1alpha1.Workload, error)); ok {
		return rf(ctx, namespaceName, w)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Workload) *v1alpha1.Workload); ok {
		r0 = rf(ctx, namespaceName, w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Workload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.Workload) error); ok {
		r1 = rf(ctx, namespaceName, w)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWorkload'
type MockService_CreateWorkload_Call struct {
	*mock.Call
}

// CreateWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - w *v1alpha1.Workload
func (_e *MockService_Expecter) CreateWorkload(ctx interface{}, namespaceName interface{}, w interface{}) *MockService_CreateWorkload_Call {
	return &MockService_CreateWorkload_Call{Call: _e.mock.On("CreateWorkload", ctx, namespaceName, w)}
}

func (_c *MockService_CreateWorkload_Call) Run(run func(ctx context.Context, namespaceName string, w *v1alpha1.Workload)) *MockService_CreateWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.Workload))
	})
	return _c
}

func (_c *MockService_CreateWorkload_Call) Return(_a0 *v1alpha1.Workload, _a1 error) *MockService_CreateWorkload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateWorkload_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.Workload) (*v1alpha1.Workload, error)) *MockService_CreateWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWorkload provides a mock function with given fields: ctx, namespaceName, workloadName
func (_m *MockService) DeleteWorkload(ctx context.Context, namespaceName string, workloadName string) error {
	ret := _m.Called(ctx, namespaceName, workloadName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWorkload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, workloadName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWorkload'
type MockService_DeleteWorkload_Call struct {
	*mock.Call
}

// DeleteWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - workloadName string
func (_e *MockService_Expecter) DeleteWorkload(ctx interface{}, namespaceName interface{}, workloadName interface{}) *MockService_DeleteWorkload_Call {
	return &MockService_DeleteWorkload_Call{Call: _e.mock.On("DeleteWorkload", ctx, namespaceName, workloadName)}
}

func (_c *MockService_DeleteWorkload_Call) Run(run func(ctx context.Context, namespaceName string, workloadName string)) *MockService_DeleteWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteWorkload_Call) Return(_a0 error) *MockService_DeleteWorkload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteWorkload_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkload provides a mock function with given fields: ctx, namespaceName, workloadName
func (_m *MockService) GetWorkload(ctx context.Context, namespaceName string, workloadName string) (*v1alpha1.Workload, error) {
	ret := _m.Called(ctx, namespaceName, workloadName)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkload")
	}

	var r0 *v1alpha1.Workload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.Workload, error)); ok {
		return rf(ctx, namespaceName, workloadName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.Workload); ok {
		r0 = rf(ctx, namespaceName, workloadName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Workload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, workloadName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkload'
type MockService_GetWorkload_Call struct {
	*mock.Call
}

// GetWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - workloadName string
func (_e *MockService_Expecter) GetWorkload(ctx interface{}, namespaceName interface{}, workloadName interface{}) *MockService_GetWorkload_Call {
	return &MockService_GetWorkload_Call{Call: _e.mock.On("GetWorkload", ctx, namespaceName, workloadName)}
}

func (_c *MockService_GetWorkload_Call) Run(run func(ctx context.Context, namespaceName string, workloadName string)) *MockService_GetWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetWorkload_Call) Return(_a0 *v1alpha1.Workload, _a1 error) *MockService_GetWorkload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetWorkload_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.Workload, error)) *MockService_GetWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// GetWorkloadSchema provides a mock function with given fields: ctx
func (_m *MockService) GetWorkloadSchema(ctx context.Context) (*v1.JSONSchemaProps, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetWorkloadSchema")
	}

	var r0 *v1.JSONSchemaProps
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*v1.JSONSchemaProps, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *v1.JSONSchemaProps); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.JSONSchemaProps)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetWorkloadSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWorkloadSchema'
type MockService_GetWorkloadSchema_Call struct {
	*mock.Call
}

// GetWorkloadSchema is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) GetWorkloadSchema(ctx interface{}) *MockService_GetWorkloadSchema_Call {
	return &MockService_GetWorkloadSchema_Call{Call: _e.mock.On("GetWorkloadSchema", ctx)}
}

func (_c *MockService_GetWorkloadSchema_Call) Run(run func(ctx context.Context)) *MockService_GetWorkloadSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockService_GetWorkloadSchema_Call) Return(_a0 *v1.JSONSchemaProps, _a1 error) *MockService_GetWorkloadSchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetWorkloadSchema_Call) RunAndReturn(run func(context.Context) (*v1.JSONSchemaProps, error)) *MockService_GetWorkloadSchema_Call {
	_c.Call.Return(run)
	return _c
}

// ListWorkloads provides a mock function with given fields: ctx, namespaceName, componentName, opts
func (_m *MockService) ListWorkloads(ctx context.Context, namespaceName string, componentName string, opts services.ListOptions) (*services.ListResult[v1alpha1.Workload], error) {
	ret := _m.Called(ctx, namespaceName, componentName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListWorkloads")
	}

	var r0 *services.ListResult[v1alpha1.Workload]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.Workload], error)); ok {
		return rf(ctx, namespaceName, componentName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) *services.ListResult[v1alpha1.Workload]); ok {
		r0 = rf(ctx, namespaceName, componentName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.Workload])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, componentName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListWorkloads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWorkloads'
type MockService_ListWorkloads_Call struct {
	*mock.Call
}

// ListWorkloads is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListWorkloads(ctx interface{}, namespaceName interface{}, componentName interface{}, opts interface{}) *MockService_ListWorkloads_Call {
	return &MockService_ListWorkloads_Call{Call: _e.mock.On("ListWorkloads", ctx, namespaceName, componentName, opts)}
}

func (_c *MockService_ListWorkloads_Call) Run(run func(ctx context.Context, namespaceName string, componentName string, opts services.ListOptions)) *MockService_ListWorkloads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListWorkloads_Call) Return(_a0 *services.ListResult[v1alpha1.Workload], _a1 error) *MockService_ListWorkloads_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListWorkloads_Call) RunAndReturn(run func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.Workload], error)) *MockService_ListWorkloads_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWorkload provides a mock function with given fields: ctx, namespaceName, w
func (_m *MockService) UpdateWorkload(ctx context.Context, namespaceName string, w *v1alpha1.Workload) (*v1alpha1.Workload, error) {
	ret := _m.Called(ctx, namespaceName, w)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWorkload")
	}

	var r0 *v1alpha1.Workload
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Workload) (*v1alpha1.Workload, error)); ok {
		return rf(ctx, namespaceName, w)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Workload) *v1alpha1.Workload); ok {
		r0 = rf(ctx, namespaceName, w)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Workload)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.Workload) error); ok {
		r1 = rf(ctx, namespaceName, w)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateWorkload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWorkload'
type MockService_UpdateWorkload_Call struct {
	*mock.Call
}

// UpdateWorkload is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - w *v1alpha1.Workload
func (_e *MockService_Expecter) UpdateWorkload(ctx interface{}, namespaceName interface{}, w interface{}) *MockService_UpdateWorkload_Call {
	return &MockService_UpdateWorkload_Call{Call: _e.mock.On("UpdateWorkload", ctx, namespaceName, w)}
}

func (_c *MockService_UpdateWorkload_Call) Run(run func(ctx context.Context, namespaceName string, w *v1alpha1.Workload)) *MockService_UpdateWorkload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.Workload))
	})
	return _c
}

func (_c *MockService_UpdateWorkload_Call) Return(_a0 *v1alpha1.Workload, _a1 error) *MockService_UpdateWorkload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateWorkload_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.Workload) (*v1alpha1.Workload, error)) *MockService_UpdateWorkload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
