// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"
	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateComponentRelease provides a mock function with given fields: ctx, namespaceName, cr
func (_m *MockService) CreateComponentRelease(ctx context.Context, namespaceName string, cr *v1alpha1.ComponentRelease) (*v1alpha1.ComponentRelease, error) {
	ret := _m.Called(ctx, namespaceName, cr)

	if len(ret) == 0 {
		panic("no return value specified for CreateComponentRelease")
	}

	var r0 *v1alpha1.ComponentRelease
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ComponentRelease) (*v1alpha1.ComponentRelease, error)); ok {
		return rf(ctx, namespaceName, cr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ComponentRelease) *v1alpha1.ComponentRelease); ok {
		r0 = rf(ctx, namespaceName, cr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ComponentRelease)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ComponentRelease) error); ok {
		r1 = rf(ctx, namespaceName, cr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateComponentRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComponentRelease'
type MockService_CreateComponentRelease_Call struct {
	*mock.Call
}

// CreateComponentRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - cr *v1alpha1.ComponentRelease
func (_e *MockService_Expecter) CreateComponentRelease(ctx interface{}, namespaceName interface{}, cr interface{}) *MockService_CreateComponentRelease_Call {
	return &MockService_CreateComponentRelease_Call{Call: _e.mock.On("CreateComponentRelease", ctx, namespaceName, cr)}
}

func (_c *MockService_CreateComponentRelease_Call) Run(run func(ctx context.Context, namespaceName string, cr *v1alpha1.ComponentRelease)) *MockService_CreateComponentRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ComponentRelease))
	})
	return _c
}

func (_c *MockService_CreateComponentRelease_Call) Return(_a0 *v1alpha1.ComponentRelease, _a1 error) *MockService_CreateComponentRelease_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateComponentRelease_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ComponentRelease) (*v1alpha1.ComponentRelease, error)) *MockService_CreateComponentRelease_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComponentRelease provides a mock function with given fields: ctx, namespaceName, componentReleaseName
func (_m *MockService) DeleteComponentRelease(ctx context.Context, namespaceName string, componentReleaseName string) error {
	ret := _m.Called(ctx, namespaceName, componentReleaseName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComponentRelease")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, componentReleaseName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteComponentRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComponentRelease'
type MockService_DeleteComponentRelease_Call struct {
	*mock.Call
}

// DeleteComponentRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentReleaseName string
func (_e *MockService_Expecter) DeleteComponentRelease(ctx interface{}, namespaceName interface{}, componentReleaseName interface{}) *MockService_DeleteComponentRelease_Call {
	return &MockService_DeleteComponentRelease_Call{Call: _e.mock.On("DeleteComponentRelease", ctx, namespaceName, componentReleaseName)}
}

func (_c *MockService_DeleteComponentRelease_Call) Run(run func(ctx context.Context, namespaceName string, componentReleaseName string)) *MockService_DeleteComponentRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteComponentRelease_Call) Return(_a0 error) *MockService_DeleteComponentRelease_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteComponentRelease_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteComponentRelease_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponentRelease provides a mock function with given fields: ctx, namespaceName, componentReleaseName
func (_m *MockService) GetComponentRelease(ctx context.Context, namespaceName string, componentReleaseName string) (*v1alpha1.ComponentRelease, error) {
	ret := _m.Called(ctx, namespaceName, componentReleaseName)

	if len(ret) == 0 {
		panic("no return value specified for GetComponentRelease")
	}

	var r0 *v1alpha1.ComponentRelease
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.ComponentRelease, error)); ok {
		return rf(ctx, namespaceName, componentReleaseName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.ComponentRelease); ok {
		r0 = rf(ctx, namespaceName, componentReleaseName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ComponentRelease)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, componentReleaseName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetComponentRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponentRelease'
type MockService_GetComponentRelease_Call struct {
	*mock.Call
}

// GetComponentRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentReleaseName string
func (_e *MockService_Expecter) GetComponentRelease(ctx interface{}, namespaceName interface{}, componentReleaseName interface{}) *MockService_GetComponentRelease_Call {
	return &MockService_GetComponentRelease_Call{Call: _e.mock.On("GetComponentRelease", ctx, namespaceName, componentReleaseName)}
}

func (_c *MockService_GetComponentRelease_Call) Run(run func(ctx context.Context, namespaceName string, componentReleaseName string)) *MockService_GetComponentRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetComponentRelease_Call) Return(_a0 *v1alpha1.ComponentRelease, _a1 error) *MockService_GetComponentRelease_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetComponentRelease_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.ComponentRelease, error)) *MockService_GetComponentRelease_Call {
	_c.Call.Return(run)
	return _c
}

// ListComponentReleases provides a mock function with given fields: ctx, namespaceName, componentName, opts
func (_m *MockService) ListComponentReleases(ctx context.Context, namespaceName string, componentName string, opts services.ListOptions) (*services.ListResult[v1alpha1.ComponentRelease], error) {
	ret := _m.Called(ctx, namespaceName, componentName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListComponentReleases")
	}

	var r0 *services.ListResult[v1alpha1.ComponentRelease]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.ComponentRelease], error)); ok {
		return rf(ctx, namespaceName, componentName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) *services.ListResult[v1alpha1.ComponentRelease]); ok {
		r0 = rf(ctx, namespaceName, componentName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.ComponentRelease])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, componentName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListComponentReleases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComponentReleases'
type MockService_ListComponentReleases_Call struct {
	*mock.Call
}

// ListComponentReleases is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListComponentReleases(ctx interface{}, namespaceName interface{}, componentName interface{}, opts interface{}) *MockService_ListComponentReleases_Call {
	return &MockService_ListComponentReleases_Call{Call: _e.mock.On("ListComponentReleases", ctx, namespaceName, componentName, opts)}
}

func (_c *MockService_ListComponentReleases_Call) Run(run func(ctx context.Context, namespaceName string, componentName string, opts services.ListOptions)) *MockService_ListComponentReleases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListComponentReleases_Call) Return(_a0 *services.ListResult[v1alpha1.ComponentRelease], _a1 error) *MockService_ListComponentReleases_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListComponentReleases_Call) RunAndReturn(run func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.ComponentRelease], error)) *MockService_ListComponentReleases_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
