apiVersion: openchoreo.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: github-stats-report-run-01
spec:
  workflow:
    kind: ClusterWorkflow
    name: github-stats-report
    parameters:
      source:
        org: "openchoreo"
        repo: "openchoreo"
      output:
        format: "table"

