---
# ReleaseBinding for frontend component with env variable misconfiguration
apiVersion: openchoreo.dev/v1alpha1
kind: ReleaseBinding
metadata:
  name: frontend-development
  namespace: default
spec:
  owner:
    projectName: gcp-microservice-demo
    componentName: frontend
  environment: development
  # override env variable PRODUCT_CATALOG_SERVICE_ADDR to http://localhost:8080 instead productcatalog:80
  workloadOverrides:
    container:
      env:
        - key: PRODUCT_CATALOG_SERVICE_ADDR
          value: "http://localhost:8080"
  componentTypeEnvironmentConfigs:                                       # Added to rollout restart the frontend service (Due to https://github.com/openchoreo/openchoreo/issues/1634)
    resources:
      requests:
        cpu: "60m"
      limits:
        cpu: "250m"
  traitEnvironmentConfigs:
    frontend-rpc-unavailable-error-log-alert:
      enabled: true                                                 # Alert rules can be enabled/disabled per environment. Default is true.
      actions:
        notifications:
          channels:
            - "email-notification-channel-development"             # Notification channels can be specified per environment. If not specified, the default notification channel for the environment will be used.
        incident:
          enabled: true                                            # Incident creation can be enabled/disabled per environment. Default is false.
          triggerAiRca: false                                      # AI root cause analysis can be enabled/disabled per environment. Default is false.

---
# ReleaseBinding for recommendation component with cpu limit misconfiguration
apiVersion: openchoreo.dev/v1alpha1
kind: ReleaseBinding
metadata:
  name: recommendation-development
  namespace: default
spec:
  owner:
    projectName: gcp-microservice-demo
    componentName: recommendation
  environment: development
  # override cpu request and limit to 10m instead 100m
  componentTypeEnvironmentConfigs:
    resources:
      requests:
        cpu: "10m"
      limits:
        cpu: "10m"
  traitEnvironmentConfigs:
    recommendation-high-cpu-alert:
      enabled: true
      actions:
        notifications:
          channels:
            - "webhook-notification-channel-development"
        incident:
          enabled: true
          triggerAiRca: true

---
# ReleaseBinding for cart component with memory limit misconfiguration
apiVersion: openchoreo.dev/v1alpha1
kind: ReleaseBinding
metadata:
  name: cart-development
  namespace: default
spec:
  owner:
    projectName: gcp-microservice-demo
    componentName: cart
  environment: development
  # override memory request to 100Mi and limit to 150Mi instead of 256Mi
  componentTypeEnvironmentConfigs:
    resources:
      requests:
        memory: "100Mi"
      limits:
        memory: "150Mi"
  # No traitEnvironmentConfigs are specified here. Using the defaults.
