// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"
	mock "github.com/stretchr/testify/mock"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateClusterTrait provides a mock function with given fields: ctx, ct
func (_m *MockService) CreateClusterTrait(ctx context.Context, ct *v1alpha1.ClusterTrait) (*v1alpha1.ClusterTrait, error) {
	ret := _m.Called(ctx, ct)

	if len(ret) == 0 {
		panic("no return value specified for CreateClusterTrait")
	}

	var r0 *v1alpha1.ClusterTrait
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterTrait) (*v1alpha1.ClusterTrait, error)); ok {
		return rf(ctx, ct)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterTrait) *v1alpha1.ClusterTrait); ok {
		r0 = rf(ctx, ct)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ClusterTrait)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.ClusterTrait) error); ok {
		r1 = rf(ctx, ct)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateClusterTrait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClusterTrait'
type MockService_CreateClusterTrait_Call struct {
	*mock.Call
}

// CreateClusterTrait is a helper method to define mock.On call
//   - ctx context.Context
//   - ct *v1alpha1.ClusterTrait
func (_e *MockService_Expecter) CreateClusterTrait(ctx interface{}, ct interface{}) *MockService_CreateClusterTrait_Call {
	return &MockService_CreateClusterTrait_Call{Call: _e.mock.On("CreateClusterTrait", ctx, ct)}
}

func (_c *MockService_CreateClusterTrait_Call) Run(run func(ctx context.Context, ct *v1alpha1.ClusterTrait)) *MockService_CreateClusterTrait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.ClusterTrait))
	})
	return _c
}

func (_c *MockService_CreateClusterTrait_Call) Return(_a0 *v1alpha1.ClusterTrait, _a1 error) *MockService_CreateClusterTrait_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateClusterTrait_Call) RunAndReturn(run func(context.Context, *v1alpha1.ClusterTrait) (*v1alpha1.ClusterTrait, error)) *MockService_CreateClusterTrait_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClusterTrait provides a mock function with given fields: ctx, clusterTraitName
func (_m *MockService) DeleteClusterTrait(ctx context.Context, clusterTraitName string) error {
	ret := _m.Called(ctx, clusterTraitName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClusterTrait")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, clusterTraitName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteClusterTrait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClusterTrait'
type MockService_DeleteClusterTrait_Call struct {
	*mock.Call
}

// DeleteClusterTrait is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterTraitName string
func (_e *MockService_Expecter) DeleteClusterTrait(ctx interface{}, clusterTraitName interface{}) *MockService_DeleteClusterTrait_Call {
	return &MockService_DeleteClusterTrait_Call{Call: _e.mock.On("DeleteClusterTrait", ctx, clusterTraitName)}
}

func (_c *MockService_DeleteClusterTrait_Call) Run(run func(ctx context.Context, clusterTraitName string)) *MockService_DeleteClusterTrait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_DeleteClusterTrait_Call) Return(_a0 error) *MockService_DeleteClusterTrait_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteClusterTrait_Call) RunAndReturn(run func(context.Context, string) error) *MockService_DeleteClusterTrait_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterTrait provides a mock function with given fields: ctx, clusterTraitName
func (_m *MockService) GetClusterTrait(ctx context.Context, clusterTraitName string) (*v1alpha1.ClusterTrait, error) {
	ret := _m.Called(ctx, clusterTraitName)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterTrait")
	}

	var r0 *v1alpha1.ClusterTrait
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*v1alpha1.ClusterTrait, error)); ok {
		return rf(ctx, clusterTraitName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *v1alpha1.ClusterTrait); ok {
		r0 = rf(ctx, clusterTraitName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ClusterTrait)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterTraitName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetClusterTrait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterTrait'
type MockService_GetClusterTrait_Call struct {
	*mock.Call
}

// GetClusterTrait is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterTraitName string
func (_e *MockService_Expecter) GetClusterTrait(ctx interface{}, clusterTraitName interface{}) *MockService_GetClusterTrait_Call {
	return &MockService_GetClusterTrait_Call{Call: _e.mock.On("GetClusterTrait", ctx, clusterTraitName)}
}

func (_c *MockService_GetClusterTrait_Call) Run(run func(ctx context.Context, clusterTraitName string)) *MockService_GetClusterTrait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetClusterTrait_Call) Return(_a0 *v1alpha1.ClusterTrait, _a1 error) *MockService_GetClusterTrait_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetClusterTrait_Call) RunAndReturn(run func(context.Context, string) (*v1alpha1.ClusterTrait, error)) *MockService_GetClusterTrait_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterTraitSchema provides a mock function with given fields: ctx, clusterTraitName
func (_m *MockService) GetClusterTraitSchema(ctx context.Context, clusterTraitName string) (map[string]interface{}, error) {
	ret := _m.Called(ctx, clusterTraitName)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterTraitSchema")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (map[string]interface{}, error)); ok {
		return rf(ctx, clusterTraitName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]interface{}); ok {
		r0 = rf(ctx, clusterTraitName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, clusterTraitName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetClusterTraitSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterTraitSchema'
type MockService_GetClusterTraitSchema_Call struct {
	*mock.Call
}

// GetClusterTraitSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - clusterTraitName string
func (_e *MockService_Expecter) GetClusterTraitSchema(ctx interface{}, clusterTraitName interface{}) *MockService_GetClusterTraitSchema_Call {
	return &MockService_GetClusterTraitSchema_Call{Call: _e.mock.On("GetClusterTraitSchema", ctx, clusterTraitName)}
}

func (_c *MockService_GetClusterTraitSchema_Call) Run(run func(ctx context.Context, clusterTraitName string)) *MockService_GetClusterTraitSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockService_GetClusterTraitSchema_Call) Return(_a0 map[string]interface{}, _a1 error) *MockService_GetClusterTraitSchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetClusterTraitSchema_Call) RunAndReturn(run func(context.Context, string) (map[string]interface{}, error)) *MockService_GetClusterTraitSchema_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusterTraits provides a mock function with given fields: ctx, opts
func (_m *MockService) ListClusterTraits(ctx context.Context, opts services.ListOptions) (*services.ListResult[v1alpha1.ClusterTrait], error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListClusterTraits")
	}

	var r0 *services.ListResult[v1alpha1.ClusterTrait]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, services.ListOptions) (*services.ListResult[v1alpha1.ClusterTrait], error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, services.ListOptions) *services.ListResult[v1alpha1.ClusterTrait]); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.ClusterTrait])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, services.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListClusterTraits_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusterTraits'
type MockService_ListClusterTraits_Call struct {
	*mock.Call
}

// ListClusterTraits is a helper method to define mock.On call
//   - ctx context.Context
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListClusterTraits(ctx interface{}, opts interface{}) *MockService_ListClusterTraits_Call {
	return &MockService_ListClusterTraits_Call{Call: _e.mock.On("ListClusterTraits", ctx, opts)}
}

func (_c *MockService_ListClusterTraits_Call) Run(run func(ctx context.Context, opts services.ListOptions)) *MockService_ListClusterTraits_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListClusterTraits_Call) Return(_a0 *services.ListResult[v1alpha1.ClusterTrait], _a1 error) *MockService_ListClusterTraits_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListClusterTraits_Call) RunAndReturn(run func(context.Context, services.ListOptions) (*services.ListResult[v1alpha1.ClusterTrait], error)) *MockService_ListClusterTraits_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClusterTrait provides a mock function with given fields: ctx, ct
func (_m *MockService) UpdateClusterTrait(ctx context.Context, ct *v1alpha1.ClusterTrait) (*v1alpha1.ClusterTrait, error) {
	ret := _m.Called(ctx, ct)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClusterTrait")
	}

	var r0 *v1alpha1.ClusterTrait
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterTrait) (*v1alpha1.ClusterTrait, error)); ok {
		return rf(ctx, ct)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1alpha1.ClusterTrait) *v1alpha1.ClusterTrait); ok {
		r0 = rf(ctx, ct)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ClusterTrait)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1alpha1.ClusterTrait) error); ok {
		r1 = rf(ctx, ct)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateClusterTrait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClusterTrait'
type MockService_UpdateClusterTrait_Call struct {
	*mock.Call
}

// UpdateClusterTrait is a helper method to define mock.On call
//   - ctx context.Context
//   - ct *v1alpha1.ClusterTrait
func (_e *MockService_Expecter) UpdateClusterTrait(ctx interface{}, ct interface{}) *MockService_UpdateClusterTrait_Call {
	return &MockService_UpdateClusterTrait_Call{Call: _e.mock.On("UpdateClusterTrait", ctx, ct)}
}

func (_c *MockService_UpdateClusterTrait_Call) Run(run func(ctx context.Context, ct *v1alpha1.ClusterTrait)) *MockService_UpdateClusterTrait_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1alpha1.ClusterTrait))
	})
	return _c
}

func (_c *MockService_UpdateClusterTrait_Call) Return(_a0 *v1alpha1.ClusterTrait, _a1 error) *MockService_UpdateClusterTrait_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateClusterTrait_Call) RunAndReturn(run func(context.Context, *v1alpha1.ClusterTrait) (*v1alpha1.ClusterTrait, error)) *MockService_UpdateClusterTrait_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
