// Copyright 2025 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ClusterTraitSpec defines the desired state of ClusterTrait.
type ClusterTraitSpec struct {
	// Schema defines trait parameters
	// +optional
	Schema TraitSchema `json:"schema,omitempty"`

	// Creates defines new Kubernetes resources to create when this trait is applied
	// +optional
	Creates []TraitCreate `json:"creates,omitempty"`

	// Patches defines modifications to existing resources generated by the ComponentType
	// +optional
	Patches []TraitPatch `json:"patches,omitempty"`
}

// ClusterTraitStatus defines the observed state of ClusterTrait.
type ClusterTraitStatus struct {
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:scope=Cluster,shortName=ctrait;ctraits
// +kubebuilder:printcolumn:name="Age",type="date",JSONPath=".metadata.creationTimestamp"

// ClusterTrait is the Schema for the clustertraits API.
// ClusterTrait is a cluster-scoped version of Trait that can be
// referenced by Components across all namespaces.
type ClusterTrait struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   ClusterTraitSpec   `json:"spec,omitempty"`
	Status ClusterTraitStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClusterTraitList contains a list of ClusterTrait.
type ClusterTraitList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ClusterTrait `json:"items"`
}

func init() {
	SchemeBuilder.Register(&ClusterTrait{}, &ClusterTraitList{})
}
