apiVersion: openchoreo.dev/v1alpha1
kind: DeploymentPipeline
metadata:
  annotations:
    openchoreo.dev/description: Deployment pipeline with dev, qa, pre-prod, and prod environments
    openchoreo.dev/display-name: Deployment Pipeline
  labels:
    openchoreo.dev/name: default
  name: default
  namespace: default
spec:
  promotionPaths:
    - sourceEnvironmentRef:
        name: development
      targetEnvironmentRefs:
        - name: qa
    - sourceEnvironmentRef:
        name: qa
      targetEnvironmentRefs:
        - name: preproduction
    - sourceEnvironmentRef:
        name: preproduction
      targetEnvironmentRefs:
        - name: production
