// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/openchoreo/openchoreo/internal/rca-agent/service"
	mock "github.com/stretchr/testify/mock"
)

// MockAgentService is an autogenerated mock type for the AgentService type
type MockAgentService struct {
	mock.Mock
}

type MockAgentService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAgentService) EXPECT() *MockAgentService_Expecter {
	return &MockAgentService_Expecter{mock: &_m.Mock}
}

// ResolveComponentScope provides a mock function with given fields: ctx, namespace, project, component, environment
func (_m *MockAgentService) ResolveComponentScope(ctx context.Context, namespace string, project string, component string, environment string) (*service.Scope, error) {
	ret := _m.Called(ctx, namespace, project, component, environment)

	if len(ret) == 0 {
		panic("no return value specified for ResolveComponentScope")
	}

	var r0 *service.Scope
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*service.Scope, error)); ok {
		return rf(ctx, namespace, project, component, environment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *service.Scope); ok {
		r0 = rf(ctx, namespace, project, component, environment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Scope)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, namespace, project, component, environment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentService_ResolveComponentScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveComponentScope'
type MockAgentService_ResolveComponentScope_Call struct {
	*mock.Call
}

// ResolveComponentScope is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - project string
//   - component string
//   - environment string
func (_e *MockAgentService_Expecter) ResolveComponentScope(ctx interface{}, namespace interface{}, project interface{}, component interface{}, environment interface{}) *MockAgentService_ResolveComponentScope_Call {
	return &MockAgentService_ResolveComponentScope_Call{Call: _e.mock.On("ResolveComponentScope", ctx, namespace, project, component, environment)}
}

func (_c *MockAgentService_ResolveComponentScope_Call) Run(run func(ctx context.Context, namespace string, project string, component string, environment string)) *MockAgentService_ResolveComponentScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockAgentService_ResolveComponentScope_Call) Return(_a0 *service.Scope, _a1 error) *MockAgentService_ResolveComponentScope_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentService_ResolveComponentScope_Call) RunAndReturn(run func(context.Context, string, string, string, string) (*service.Scope, error)) *MockAgentService_ResolveComponentScope_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveProjectScope provides a mock function with given fields: ctx, namespace, project, environment
func (_m *MockAgentService) ResolveProjectScope(ctx context.Context, namespace string, project string, environment string) (*service.Scope, error) {
	ret := _m.Called(ctx, namespace, project, environment)

	if len(ret) == 0 {
		panic("no return value specified for ResolveProjectScope")
	}

	var r0 *service.Scope
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*service.Scope, error)); ok {
		return rf(ctx, namespace, project, environment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *service.Scope); ok {
		r0 = rf(ctx, namespace, project, environment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Scope)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, namespace, project, environment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAgentService_ResolveProjectScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveProjectScope'
type MockAgentService_ResolveProjectScope_Call struct {
	*mock.Call
}

// ResolveProjectScope is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - project string
//   - environment string
func (_e *MockAgentService_Expecter) ResolveProjectScope(ctx interface{}, namespace interface{}, project interface{}, environment interface{}) *MockAgentService_ResolveProjectScope_Call {
	return &MockAgentService_ResolveProjectScope_Call{Call: _e.mock.On("ResolveProjectScope", ctx, namespace, project, environment)}
}

func (_c *MockAgentService_ResolveProjectScope_Call) Run(run func(ctx context.Context, namespace string, project string, environment string)) *MockAgentService_ResolveProjectScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockAgentService_ResolveProjectScope_Call) Return(_a0 *service.Scope, _a1 error) *MockAgentService_ResolveProjectScope_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAgentService_ResolveProjectScope_Call) RunAndReturn(run func(context.Context, string, string, string) (*service.Scope, error)) *MockAgentService_ResolveProjectScope_Call {
	_c.Call.Return(run)
	return _c
}

// RunAnalysis provides a mock function with given fields: params
func (_m *MockAgentService) RunAnalysis(params *service.AnalysisParams) {
	_m.Called(params)
}

// MockAgentService_RunAnalysis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunAnalysis'
type MockAgentService_RunAnalysis_Call struct {
	*mock.Call
}

// RunAnalysis is a helper method to define mock.On call
//   - params *service.AnalysisParams
func (_e *MockAgentService_Expecter) RunAnalysis(params interface{}) *MockAgentService_RunAnalysis_Call {
	return &MockAgentService_RunAnalysis_Call{Call: _e.mock.On("RunAnalysis", params)}
}

func (_c *MockAgentService_RunAnalysis_Call) Run(run func(params *service.AnalysisParams)) *MockAgentService_RunAnalysis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*service.AnalysisParams))
	})
	return _c
}

func (_c *MockAgentService_RunAnalysis_Call) Return() *MockAgentService_RunAnalysis_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAgentService_RunAnalysis_Call) RunAndReturn(run func(*service.AnalysisParams)) *MockAgentService_RunAnalysis_Call {
	_c.Run(run)
	return _c
}

// StreamChat provides a mock function with given fields: ctx, bearerToken, params
func (_m *MockAgentService) StreamChat(ctx context.Context, bearerToken string, params *service.ChatParams) <-chan service.ChatEvent {
	ret := _m.Called(ctx, bearerToken, params)

	if len(ret) == 0 {
		panic("no return value specified for StreamChat")
	}

	var r0 <-chan service.ChatEvent
	if rf, ok := ret.Get(0).(func(context.Context, string, *service.ChatParams) <-chan service.ChatEvent); ok {
		r0 = rf(ctx, bearerToken, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan service.ChatEvent)
		}
	}

	return r0
}

// MockAgentService_StreamChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamChat'
type MockAgentService_StreamChat_Call struct {
	*mock.Call
}

// StreamChat is a helper method to define mock.On call
//   - ctx context.Context
//   - bearerToken string
//   - params *service.ChatParams
func (_e *MockAgentService_Expecter) StreamChat(ctx interface{}, bearerToken interface{}, params interface{}) *MockAgentService_StreamChat_Call {
	return &MockAgentService_StreamChat_Call{Call: _e.mock.On("StreamChat", ctx, bearerToken, params)}
}

func (_c *MockAgentService_StreamChat_Call) Run(run func(ctx context.Context, bearerToken string, params *service.ChatParams)) *MockAgentService_StreamChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*service.ChatParams))
	})
	return _c
}

func (_c *MockAgentService_StreamChat_Call) Return(_a0 <-chan service.ChatEvent) *MockAgentService_StreamChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAgentService_StreamChat_Call) RunAndReturn(run func(context.Context, string, *service.ChatParams) <-chan service.ChatEvent) *MockAgentService_StreamChat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAgentService creates a new instance of MockAgentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAgentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAgentService {
	mock := &MockAgentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
