// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateProject provides a mock function with given fields: ctx, namespaceName, _a2
func (_m *MockService) CreateProject(ctx context.Context, namespaceName string, _a2 *v1alpha1.Project) (*v1alpha1.Project, error) {
	ret := _m.Called(ctx, namespaceName, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateProject")
	}

	var r0 *v1alpha1.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Project) (*v1alpha1.Project, error)); ok {
		return rf(ctx, namespaceName, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Project) *v1alpha1.Project); ok {
		r0 = rf(ctx, namespaceName, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.Project) error); ok {
		r1 = rf(ctx, namespaceName, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateProject'
type MockService_CreateProject_Call struct {
	*mock.Call
}

// CreateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - _a2 *v1alpha1.Project
func (_e *MockService_Expecter) CreateProject(ctx interface{}, namespaceName interface{}, _a2 interface{}) *MockService_CreateProject_Call {
	return &MockService_CreateProject_Call{Call: _e.mock.On("CreateProject", ctx, namespaceName, _a2)}
}

func (_c *MockService_CreateProject_Call) Run(run func(ctx context.Context, namespaceName string, _a2 *v1alpha1.Project)) *MockService_CreateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.Project))
	})
	return _c
}

func (_c *MockService_CreateProject_Call) Return(_a0 *v1alpha1.Project, _a1 error) *MockService_CreateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateProject_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.Project) (*v1alpha1.Project, error)) *MockService_CreateProject_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteProject provides a mock function with given fields: ctx, namespaceName, projectName
func (_m *MockService) DeleteProject(ctx context.Context, namespaceName string, projectName string) error {
	ret := _m.Called(ctx, namespaceName, projectName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, projectName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockService_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectName string
func (_e *MockService_Expecter) DeleteProject(ctx interface{}, namespaceName interface{}, projectName interface{}) *MockService_DeleteProject_Call {
	return &MockService_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, namespaceName, projectName)}
}

func (_c *MockService_DeleteProject_Call) Run(run func(ctx context.Context, namespaceName string, projectName string)) *MockService_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteProject_Call) Return(_a0 error) *MockService_DeleteProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteProject_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetProject provides a mock function with given fields: ctx, namespaceName, projectName
func (_m *MockService) GetProject(ctx context.Context, namespaceName string, projectName string) (*v1alpha1.Project, error) {
	ret := _m.Called(ctx, namespaceName, projectName)

	if len(ret) == 0 {
		panic("no return value specified for GetProject")
	}

	var r0 *v1alpha1.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.Project, error)); ok {
		return rf(ctx, namespaceName, projectName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.Project); ok {
		r0 = rf(ctx, namespaceName, projectName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, projectName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProject'
type MockService_GetProject_Call struct {
	*mock.Call
}

// GetProject is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectName string
func (_e *MockService_Expecter) GetProject(ctx interface{}, namespaceName interface{}, projectName interface{}) *MockService_GetProject_Call {
	return &MockService_GetProject_Call{Call: _e.mock.On("GetProject", ctx, namespaceName, projectName)}
}

func (_c *MockService_GetProject_Call) Run(run func(ctx context.Context, namespaceName string, projectName string)) *MockService_GetProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetProject_Call) Return(_a0 *v1alpha1.Project, _a1 error) *MockService_GetProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetProject_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.Project, error)) *MockService_GetProject_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjects provides a mock function with given fields: ctx, namespaceName, opts
func (_m *MockService) ListProjects(ctx context.Context, namespaceName string, opts services.ListOptions) (*services.ListResult[v1alpha1.Project], error) {
	ret := _m.Called(ctx, namespaceName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListProjects")
	}

	var r0 *services.ListResult[v1alpha1.Project]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.Project], error)); ok {
		return rf(ctx, namespaceName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) *services.ListResult[v1alpha1.Project]); ok {
		r0 = rf(ctx, namespaceName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.Project])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjects'
type MockService_ListProjects_Call struct {
	*mock.Call
}

// ListProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListProjects(ctx interface{}, namespaceName interface{}, opts interface{}) *MockService_ListProjects_Call {
	return &MockService_ListProjects_Call{Call: _e.mock.On("ListProjects", ctx, namespaceName, opts)}
}

func (_c *MockService_ListProjects_Call) Run(run func(ctx context.Context, namespaceName string, opts services.ListOptions)) *MockService_ListProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListProjects_Call) Return(_a0 *services.ListResult[v1alpha1.Project], _a1 error) *MockService_ListProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListProjects_Call) RunAndReturn(run func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.Project], error)) *MockService_ListProjects_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProject provides a mock function with given fields: ctx, namespaceName, _a2
func (_m *MockService) UpdateProject(ctx context.Context, namespaceName string, _a2 *v1alpha1.Project) (*v1alpha1.Project, error) {
	ret := _m.Called(ctx, namespaceName, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProject")
	}

	var r0 *v1alpha1.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Project) (*v1alpha1.Project, error)); ok {
		return rf(ctx, namespaceName, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Project) *v1alpha1.Project); ok {
		r0 = rf(ctx, namespaceName, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.Project) error); ok {
		r1 = rf(ctx, namespaceName, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProject'
type MockService_UpdateProject_Call struct {
	*mock.Call
}

// UpdateProject is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - _a2 *v1alpha1.Project
func (_e *MockService_Expecter) UpdateProject(ctx interface{}, namespaceName interface{}, _a2 interface{}) *MockService_UpdateProject_Call {
	return &MockService_UpdateProject_Call{Call: _e.mock.On("UpdateProject", ctx, namespaceName, _a2)}
}

func (_c *MockService_UpdateProject_Call) Run(run func(ctx context.Context, namespaceName string, _a2 *v1alpha1.Project)) *MockService_UpdateProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.Project))
	})
	return _c
}

func (_c *MockService_UpdateProject_Call) Return(_a0 *v1alpha1.Project, _a1 error) *MockService_UpdateProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateProject_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.Project) (*v1alpha1.Project, error)) *MockService_UpdateProject_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
