// Copyright 2026 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

package component

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"

	"github.com/openchoreo/openchoreo/internal/occ/resources/client/mocks"
	"github.com/openchoreo/openchoreo/internal/occ/testutil"
)

// Shared schemas used across scaffold tests.
var (
	minimalCTSchema    = json.RawMessage(`{"type":"object","properties":{"port":{"type":"integer","default":8080}}}`)
	minimalTraitSchema = json.RawMessage(`{"type":"object","properties":{"replicas":{"type":"integer","default":1}}}`)
	minimalWFSchema    = json.RawMessage(`{"type":"object","properties":{"branch":{"type":"string","default":"main"}}}`)
)

// scaffoldHeader is the common YAML header prefix for all scaffold outputs.
const scaffoldHeader = "# Generated by occ scaffold component\n" +
	"# Component: my-comp\n" +
	"# Type: deployment/web-app\n"

const scaffoldBody = "apiVersion: openchoreo.dev/v1alpha1\n" +
	"kind: Component\n" +
	"metadata:\n" +
	"  name: my-comp\n" +
	"  namespace: ns\n" +
	"spec:\n" +
	"  owner:\n" +
	"    projectName: my-project\n"

const wantScaffoldYAML = scaffoldHeader +
	scaffoldBody +
	"  componentType:\n" +
	"    kind: ComponentType\n" +
	"    name: deployment/web-app\n" +
	"  # autoDeploy: true\n" +
	"  parameters:\n" +
	"    # port: 8080\n"

const wantScaffoldWithTrait = scaffoldHeader +
	"# Traits: ingress\n" +
	scaffoldBody +
	"  componentType:\n" +
	"    kind: ComponentType\n" +
	"    name: deployment/web-app\n" +
	"  # autoDeploy: true\n" +
	"  parameters:\n" +
	"    # port: 8080\n" +
	"  traits:\n" +
	"    - kind: Trait\n" +
	"      name: ingress\n" +
	"      instanceName: <ingress-instance>\n" +
	"      parameters:\n" +
	"        # replicas: 1\n"

const wantScaffoldWithClusterTrait = scaffoldHeader +
	"# Traits: ingress\n" +
	scaffoldBody +
	"  componentType:\n" +
	"    kind: ComponentType\n" +
	"    name: deployment/web-app\n" +
	"  # autoDeploy: true\n" +
	"  parameters:\n" +
	"    # port: 8080\n" +
	"  traits:\n" +
	"    - kind: ClusterTrait\n" +
	"      name: ingress\n" +
	"      instanceName: <ingress-instance>\n" +
	"      parameters:\n" +
	"        # replicas: 1\n"

const wantScaffoldWithWorkflow = scaffoldHeader +
	"# Workflow: build-wf\n" +
	scaffoldBody +
	"  componentType:\n" +
	"    kind: ComponentType\n" +
	"    name: deployment/web-app\n" +
	"  # autoDeploy: true\n" +
	"  parameters:\n" +
	"    # port: 8080\n" +
	"  workflow:\n" +
	"    kind: Workflow\n" +
	"    name: build-wf\n" +
	"    parameters:\n" +
	"      # branch: main\n"

const wantScaffoldWithClusterWorkflow = scaffoldHeader +
	"# Workflow: build-wf\n" +
	scaffoldBody +
	"  componentType:\n" +
	"    kind: ComponentType\n" +
	"    name: deployment/web-app\n" +
	"  # autoDeploy: true\n" +
	"  parameters:\n" +
	"    # port: 8080\n" +
	"  workflow:\n" +
	"    kind: ClusterWorkflow\n" +
	"    name: build-wf\n" +
	"    parameters:\n" +
	"      # branch: main\n"

const wantScaffoldWithClusterCT = scaffoldHeader +
	scaffoldBody +
	"  componentType:\n" +
	"    kind: ClusterComponentType\n" +
	"    name: deployment/web-app\n" +
	"  # autoDeploy: true\n" +
	"  parameters:\n" +
	"    # port: 8080\n"

const wantScaffoldAllCluster = scaffoldHeader +
	"# Traits: ingress\n" +
	"# Workflow: build-wf\n" +
	scaffoldBody +
	"  componentType:\n" +
	"    kind: ClusterComponentType\n" +
	"    name: deployment/web-app\n" +
	"  # autoDeploy: true\n" +
	"  parameters:\n" +
	"    # port: 8080\n" +
	"  traits:\n" +
	"    - kind: ClusterTrait\n" +
	"      name: ingress\n" +
	"      instanceName: <ingress-instance>\n" +
	"      parameters:\n" +
	"        # replicas: 1\n" +
	"  workflow:\n" +
	"    kind: ClusterWorkflow\n" +
	"    name: build-wf\n" +
	"    parameters:\n" +
	"      # branch: main\n"

// --- Scaffold: happy path printed to stdout ---

func TestScaffold_Success_Stdout(t *testing.T) {
	mc := mocks.NewMockInterface(t)
	mc.EXPECT().GetComponentTypeSchema(mock.Anything, "ns", "web-app").Return(&minimalCTSchema, nil)

	cp := New(mc)
	out := testutil.CaptureStdout(t, func() {
		require.NoError(t, cp.Scaffold(ScaffoldParams{
			ComponentName: "my-comp",
			Namespace:     "ns",
			ProjectName:   "my-project",
			ComponentType: "deployment/web-app",
			SkipOptional:  true,
			SkipComments:  true,
		}))
	})
	assert.Equal(t, wantScaffoldYAML, out)
}

// --- Scaffold: happy path written to OutputPath ---

func TestScaffold_Success_OutputPath(t *testing.T) {
	mc := mocks.NewMockInterface(t)
	mc.EXPECT().GetComponentTypeSchema(mock.Anything, "ns", "web-app").Return(&minimalCTSchema, nil)

	outFile := filepath.Join(t.TempDir(), "component.yaml")

	cp := New(mc)
	out := testutil.CaptureStdout(t, func() {
		require.NoError(t, cp.Scaffold(ScaffoldParams{
			ComponentName: "my-comp",
			Namespace:     "ns",
			ProjectName:   "my-project",
			ComponentType: "deployment/web-app",
			SkipOptional:  true,
			SkipComments:  true,
			OutputPath:    outFile,
		}))
	})
	assert.Equal(t, fmt.Sprintf("Component YAML written to %s\n", outFile), out)

	data, err := os.ReadFile(outFile)
	require.NoError(t, err)
	assert.Equal(t, wantScaffoldYAML, string(data))
}

// --- Scaffold: with namespace-scoped Trait ---

func TestScaffold_WithTrait(t *testing.T) {
	mc := mocks.NewMockInterface(t)
	mc.EXPECT().GetComponentTypeSchema(mock.Anything, "ns", "web-app").Return(&minimalCTSchema, nil)
	mc.EXPECT().GetTraitSchema(mock.Anything, "ns", "ingress").Return(&minimalTraitSchema, nil)

	cp := New(mc)
	out := testutil.CaptureStdout(t, func() {
		require.NoError(t, cp.Scaffold(ScaffoldParams{
			ComponentName: "my-comp",
			Namespace:     "ns",
			ProjectName:   "my-project",
			ComponentType: "deployment/web-app",
			Traits:        []string{"ingress"},
			SkipOptional:  true,
			SkipComments:  true,
		}))
	})
	assert.Equal(t, wantScaffoldWithTrait, out)
}

// --- Scaffold: with ClusterTrait ---

func TestScaffold_WithClusterTrait(t *testing.T) {
	mc := mocks.NewMockInterface(t)
	mc.EXPECT().GetComponentTypeSchema(mock.Anything, "ns", "web-app").Return(&minimalCTSchema, nil)
	mc.EXPECT().GetClusterTraitSchema(mock.Anything, "ingress").Return(&minimalTraitSchema, nil)

	cp := New(mc)
	out := testutil.CaptureStdout(t, func() {
		require.NoError(t, cp.Scaffold(ScaffoldParams{
			ComponentName: "my-comp",
			Namespace:     "ns",
			ProjectName:   "my-project",
			ComponentType: "deployment/web-app",
			ClusterTraits: []string{"ingress"},
			SkipOptional:  true,
			SkipComments:  true,
		}))
	})
	assert.Equal(t, wantScaffoldWithClusterTrait, out)
}

// --- Scaffold: with namespace-scoped Workflow ---

func TestScaffold_WithWorkflow(t *testing.T) {
	mc := mocks.NewMockInterface(t)
	mc.EXPECT().GetComponentTypeSchema(mock.Anything, "ns", "web-app").Return(&minimalCTSchema, nil)
	mc.EXPECT().GetWorkflowSchema(mock.Anything, "ns", "build-wf").Return(&minimalWFSchema, nil)

	cp := New(mc)
	out := testutil.CaptureStdout(t, func() {
		require.NoError(t, cp.Scaffold(ScaffoldParams{
			ComponentName: "my-comp",
			Namespace:     "ns",
			ProjectName:   "my-project",
			ComponentType: "deployment/web-app",
			WorkflowName:  "build-wf",
			SkipOptional:  true,
			SkipComments:  true,
		}))
	})
	assert.Equal(t, wantScaffoldWithWorkflow, out)
}

// --- Scaffold: with ClusterWorkflow ---

func TestScaffold_WithClusterWorkflow(t *testing.T) {
	mc := mocks.NewMockInterface(t)
	mc.EXPECT().GetComponentTypeSchema(mock.Anything, "ns", "web-app").Return(&minimalCTSchema, nil)
	mc.EXPECT().GetClusterWorkflowSchema(mock.Anything, "build-wf").Return(&minimalWFSchema, nil)

	cp := New(mc)
	out := testutil.CaptureStdout(t, func() {
		require.NoError(t, cp.Scaffold(ScaffoldParams{
			ComponentName:       "my-comp",
			Namespace:           "ns",
			ProjectName:         "my-project",
			ComponentType:       "deployment/web-app",
			ClusterWorkflowName: "build-wf",
			SkipOptional:        true,
			SkipComments:        true,
		}))
	})
	assert.Equal(t, wantScaffoldWithClusterWorkflow, out)
}

// --- Scaffold: with ClusterComponentType ---

func TestScaffold_WithClusterComponentType(t *testing.T) {
	mc := mocks.NewMockInterface(t)
	mc.EXPECT().GetClusterComponentTypeSchema(mock.Anything, "web-app").Return(&minimalCTSchema, nil)

	cp := New(mc)
	out := testutil.CaptureStdout(t, func() {
		require.NoError(t, cp.Scaffold(ScaffoldParams{
			ComponentName:        "my-comp",
			Namespace:            "ns",
			ProjectName:          "my-project",
			ClusterComponentType: "deployment/web-app",
			SkipOptional:         true,
			SkipComments:         true,
		}))
	})
	assert.Equal(t, wantScaffoldWithClusterCT, out)
}

// --- Scaffold: ClusterComponentType + ClusterTrait + ClusterWorkflow ---

func TestScaffold_AllClusterScoped(t *testing.T) {
	mc := mocks.NewMockInterface(t)
	mc.EXPECT().GetClusterComponentTypeSchema(mock.Anything, "web-app").Return(&minimalCTSchema, nil)
	mc.EXPECT().GetClusterTraitSchema(mock.Anything, "ingress").Return(&minimalTraitSchema, nil)
	mc.EXPECT().GetClusterWorkflowSchema(mock.Anything, "build-wf").Return(&minimalWFSchema, nil)

	cp := New(mc)
	out := testutil.CaptureStdout(t, func() {
		require.NoError(t, cp.Scaffold(ScaffoldParams{
			ComponentName:        "my-comp",
			Namespace:            "ns",
			ProjectName:          "my-project",
			ClusterComponentType: "deployment/web-app",
			ClusterTraits:        []string{"ingress"},
			ClusterWorkflowName:  "build-wf",
			SkipOptional:         true,
			SkipComments:         true,
		}))
	})
	assert.Equal(t, wantScaffoldAllCluster, out)
}

// --- fetchScaffoldSchemas: trait schema error ---

func TestFetchScaffoldSchemas_TraitSchemaError(t *testing.T) {
	mc := mocks.NewMockInterface(t)
	mc.EXPECT().GetComponentTypeSchema(mock.Anything, "ns", "web-app").Return(&minimalCTSchema, nil)
	mc.EXPECT().GetTraitSchema(mock.Anything, "ns", "bad-trait").Return(nil, fmt.Errorf("trait not found"))

	res := &scaffoldResolution{
		componentTypeName: "web-app",
		traitNames:        []string{"bad-trait"},
		traitKinds:        map[string]string{"bad-trait": "Trait"},
	}
	_, _, _, err := fetchScaffoldSchemas(context.Background(), mc, "ns", res)
	assert.ErrorContains(t, err, "trait not found")
}

// --- fetchScaffoldSchemas: workflow schema error ---

func TestFetchScaffoldSchemas_WorkflowSchemaError(t *testing.T) {
	mc := mocks.NewMockInterface(t)
	mc.EXPECT().GetComponentTypeSchema(mock.Anything, "ns", "web-app").Return(&minimalCTSchema, nil)
	mc.EXPECT().GetWorkflowSchema(mock.Anything, "ns", "build-wf").Return(nil, fmt.Errorf("workflow schema not found"))

	res := &scaffoldResolution{
		componentTypeName: "web-app",
		workflowName:      "build-wf",
	}
	_, _, _, err := fetchScaffoldSchemas(context.Background(), mc, "ns", res)
	assert.ErrorContains(t, err, "workflow schema not found")
}
