// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	component "github.com/openchoreo/openchoreo/internal/openchoreo-api/services/component"

	mock "github.com/stretchr/testify/mock"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"

	v1 "k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateComponent provides a mock function with given fields: ctx, namespaceName, _a2
func (_m *MockService) CreateComponent(ctx context.Context, namespaceName string, _a2 *v1alpha1.Component) (*v1alpha1.Component, error) {
	ret := _m.Called(ctx, namespaceName, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CreateComponent")
	}

	var r0 *v1alpha1.Component
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Component) (*v1alpha1.Component, error)); ok {
		return rf(ctx, namespaceName, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Component) *v1alpha1.Component); ok {
		r0 = rf(ctx, namespaceName, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Component)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.Component) error); ok {
		r1 = rf(ctx, namespaceName, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComponent'
type MockService_CreateComponent_Call struct {
	*mock.Call
}

// CreateComponent is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - _a2 *v1alpha1.Component
func (_e *MockService_Expecter) CreateComponent(ctx interface{}, namespaceName interface{}, _a2 interface{}) *MockService_CreateComponent_Call {
	return &MockService_CreateComponent_Call{Call: _e.mock.On("CreateComponent", ctx, namespaceName, _a2)}
}

func (_c *MockService_CreateComponent_Call) Run(run func(ctx context.Context, namespaceName string, _a2 *v1alpha1.Component)) *MockService_CreateComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.Component))
	})
	return _c
}

func (_c *MockService_CreateComponent_Call) Return(_a0 *v1alpha1.Component, _a1 error) *MockService_CreateComponent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateComponent_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.Component) (*v1alpha1.Component, error)) *MockService_CreateComponent_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComponent provides a mock function with given fields: ctx, namespaceName, componentName
func (_m *MockService) DeleteComponent(ctx context.Context, namespaceName string, componentName string) error {
	ret := _m.Called(ctx, namespaceName, componentName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComponent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, componentName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComponent'
type MockService_DeleteComponent_Call struct {
	*mock.Call
}

// DeleteComponent is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentName string
func (_e *MockService_Expecter) DeleteComponent(ctx interface{}, namespaceName interface{}, componentName interface{}) *MockService_DeleteComponent_Call {
	return &MockService_DeleteComponent_Call{Call: _e.mock.On("DeleteComponent", ctx, namespaceName, componentName)}
}

func (_c *MockService_DeleteComponent_Call) Run(run func(ctx context.Context, namespaceName string, componentName string)) *MockService_DeleteComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteComponent_Call) Return(_a0 error) *MockService_DeleteComponent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteComponent_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteComponent_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRelease provides a mock function with given fields: ctx, namespaceName, componentName, req
func (_m *MockService) GenerateRelease(ctx context.Context, namespaceName string, componentName string, req *component.GenerateReleaseRequest) (*v1alpha1.ComponentRelease, error) {
	ret := _m.Called(ctx, namespaceName, componentName, req)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRelease")
	}

	var r0 *v1alpha1.ComponentRelease
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *component.GenerateReleaseRequest) (*v1alpha1.ComponentRelease, error)); ok {
		return rf(ctx, namespaceName, componentName, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *component.GenerateReleaseRequest) *v1alpha1.ComponentRelease); ok {
		r0 = rf(ctx, namespaceName, componentName, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ComponentRelease)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *component.GenerateReleaseRequest) error); ok {
		r1 = rf(ctx, namespaceName, componentName, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GenerateRelease_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRelease'
type MockService_GenerateRelease_Call struct {
	*mock.Call
}

// GenerateRelease is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentName string
//   - req *component.GenerateReleaseRequest
func (_e *MockService_Expecter) GenerateRelease(ctx interface{}, namespaceName interface{}, componentName interface{}, req interface{}) *MockService_GenerateRelease_Call {
	return &MockService_GenerateRelease_Call{Call: _e.mock.On("GenerateRelease", ctx, namespaceName, componentName, req)}
}

func (_c *MockService_GenerateRelease_Call) Run(run func(ctx context.Context, namespaceName string, componentName string, req *component.GenerateReleaseRequest)) *MockService_GenerateRelease_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(*component.GenerateReleaseRequest))
	})
	return _c
}

func (_c *MockService_GenerateRelease_Call) Return(_a0 *v1alpha1.ComponentRelease, _a1 error) *MockService_GenerateRelease_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GenerateRelease_Call) RunAndReturn(run func(context.Context, string, string, *component.GenerateReleaseRequest) (*v1alpha1.ComponentRelease, error)) *MockService_GenerateRelease_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponent provides a mock function with given fields: ctx, namespaceName, componentName
func (_m *MockService) GetComponent(ctx context.Context, namespaceName string, componentName string) (*v1alpha1.Component, error) {
	ret := _m.Called(ctx, namespaceName, componentName)

	if len(ret) == 0 {
		panic("no return value specified for GetComponent")
	}

	var r0 *v1alpha1.Component
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.Component, error)); ok {
		return rf(ctx, namespaceName, componentName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.Component); ok {
		r0 = rf(ctx, namespaceName, componentName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Component)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, componentName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponent'
type MockService_GetComponent_Call struct {
	*mock.Call
}

// GetComponent is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentName string
func (_e *MockService_Expecter) GetComponent(ctx interface{}, namespaceName interface{}, componentName interface{}) *MockService_GetComponent_Call {
	return &MockService_GetComponent_Call{Call: _e.mock.On("GetComponent", ctx, namespaceName, componentName)}
}

func (_c *MockService_GetComponent_Call) Run(run func(ctx context.Context, namespaceName string, componentName string)) *MockService_GetComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetComponent_Call) Return(_a0 *v1alpha1.Component, _a1 error) *MockService_GetComponent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetComponent_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.Component, error)) *MockService_GetComponent_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponentReleaseSchema provides a mock function with given fields: ctx, namespaceName, releaseName, componentName
func (_m *MockService) GetComponentReleaseSchema(ctx context.Context, namespaceName string, releaseName string, componentName string) (*v1.JSONSchemaProps, error) {
	ret := _m.Called(ctx, namespaceName, releaseName, componentName)

	if len(ret) == 0 {
		panic("no return value specified for GetComponentReleaseSchema")
	}

	var r0 *v1.JSONSchemaProps
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*v1.JSONSchemaProps, error)); ok {
		return rf(ctx, namespaceName, releaseName, componentName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *v1.JSONSchemaProps); ok {
		r0 = rf(ctx, namespaceName, releaseName, componentName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.JSONSchemaProps)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, namespaceName, releaseName, componentName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetComponentReleaseSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponentReleaseSchema'
type MockService_GetComponentReleaseSchema_Call struct {
	*mock.Call
}

// GetComponentReleaseSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - releaseName string
//   - componentName string
func (_e *MockService_Expecter) GetComponentReleaseSchema(ctx interface{}, namespaceName interface{}, releaseName interface{}, componentName interface{}) *MockService_GetComponentReleaseSchema_Call {
	return &MockService_GetComponentReleaseSchema_Call{Call: _e.mock.On("GetComponentReleaseSchema", ctx, namespaceName, releaseName, componentName)}
}

func (_c *MockService_GetComponentReleaseSchema_Call) Run(run func(ctx context.Context, namespaceName string, releaseName string, componentName string)) *MockService_GetComponentReleaseSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockService_GetComponentReleaseSchema_Call) Return(_a0 *v1.JSONSchemaProps, _a1 error) *MockService_GetComponentReleaseSchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetComponentReleaseSchema_Call) RunAndReturn(run func(context.Context, string, string, string) (*v1.JSONSchemaProps, error)) *MockService_GetComponentReleaseSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetComponentSchema provides a mock function with given fields: ctx, namespaceName, componentName
func (_m *MockService) GetComponentSchema(ctx context.Context, namespaceName string, componentName string) (*v1.JSONSchemaProps, error) {
	ret := _m.Called(ctx, namespaceName, componentName)

	if len(ret) == 0 {
		panic("no return value specified for GetComponentSchema")
	}

	var r0 *v1.JSONSchemaProps
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1.JSONSchemaProps, error)); ok {
		return rf(ctx, namespaceName, componentName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1.JSONSchemaProps); ok {
		r0 = rf(ctx, namespaceName, componentName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.JSONSchemaProps)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, componentName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetComponentSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComponentSchema'
type MockService_GetComponentSchema_Call struct {
	*mock.Call
}

// GetComponentSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentName string
func (_e *MockService_Expecter) GetComponentSchema(ctx interface{}, namespaceName interface{}, componentName interface{}) *MockService_GetComponentSchema_Call {
	return &MockService_GetComponentSchema_Call{Call: _e.mock.On("GetComponentSchema", ctx, namespaceName, componentName)}
}

func (_c *MockService_GetComponentSchema_Call) Run(run func(ctx context.Context, namespaceName string, componentName string)) *MockService_GetComponentSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetComponentSchema_Call) Return(_a0 *v1.JSONSchemaProps, _a1 error) *MockService_GetComponentSchema_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetComponentSchema_Call) RunAndReturn(run func(context.Context, string, string) (*v1.JSONSchemaProps, error)) *MockService_GetComponentSchema_Call {
	_c.Call.Return(run)
	return _c
}

// ListComponents provides a mock function with given fields: ctx, namespaceName, projectName, opts
func (_m *MockService) ListComponents(ctx context.Context, namespaceName string, projectName string, opts services.ListOptions) (*services.ListResult[v1alpha1.Component], error) {
	ret := _m.Called(ctx, namespaceName, projectName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListComponents")
	}

	var r0 *services.ListResult[v1alpha1.Component]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.Component], error)); ok {
		return rf(ctx, namespaceName, projectName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) *services.ListResult[v1alpha1.Component]); ok {
		r0 = rf(ctx, namespaceName, projectName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.Component])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, projectName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListComponents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComponents'
type MockService_ListComponents_Call struct {
	*mock.Call
}

// ListComponents is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListComponents(ctx interface{}, namespaceName interface{}, projectName interface{}, opts interface{}) *MockService_ListComponents_Call {
	return &MockService_ListComponents_Call{Call: _e.mock.On("ListComponents", ctx, namespaceName, projectName, opts)}
}

func (_c *MockService_ListComponents_Call) Run(run func(ctx context.Context, namespaceName string, projectName string, opts services.ListOptions)) *MockService_ListComponents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListComponents_Call) Return(_a0 *services.ListResult[v1alpha1.Component], _a1 error) *MockService_ListComponents_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListComponents_Call) RunAndReturn(run func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.Component], error)) *MockService_ListComponents_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComponent provides a mock function with given fields: ctx, namespaceName, _a2
func (_m *MockService) UpdateComponent(ctx context.Context, namespaceName string, _a2 *v1alpha1.Component) (*v1alpha1.Component, error) {
	ret := _m.Called(ctx, namespaceName, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComponent")
	}

	var r0 *v1alpha1.Component
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Component) (*v1alpha1.Component, error)); ok {
		return rf(ctx, namespaceName, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.Component) *v1alpha1.Component); ok {
		r0 = rf(ctx, namespaceName, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.Component)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.Component) error); ok {
		r1 = rf(ctx, namespaceName, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateComponent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComponent'
type MockService_UpdateComponent_Call struct {
	*mock.Call
}

// UpdateComponent is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - _a2 *v1alpha1.Component
func (_e *MockService_Expecter) UpdateComponent(ctx interface{}, namespaceName interface{}, _a2 interface{}) *MockService_UpdateComponent_Call {
	return &MockService_UpdateComponent_Call{Call: _e.mock.On("UpdateComponent", ctx, namespaceName, _a2)}
}

func (_c *MockService_UpdateComponent_Call) Run(run func(ctx context.Context, namespaceName string, _a2 *v1alpha1.Component)) *MockService_UpdateComponent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.Component))
	})
	return _c
}

func (_c *MockService_UpdateComponent_Call) Return(_a0 *v1alpha1.Component, _a1 error) *MockService_UpdateComponent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateComponent_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.Component) (*v1alpha1.Component, error)) *MockService_UpdateComponent_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
