// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/openchoreo/openchoreo/internal/openchoreo-api/api/gen"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteObservabilityAlertsNotificationChannel provides a mock function with given fields: ctx, namespaceName, channelName
func (_m *MockClient) DeleteObservabilityAlertsNotificationChannel(ctx context.Context, namespaceName string, channelName string) error {
	ret := _m.Called(ctx, namespaceName, channelName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObservabilityAlertsNotificationChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, channelName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeleteObservabilityAlertsNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObservabilityAlertsNotificationChannel'
type MockClient_DeleteObservabilityAlertsNotificationChannel_Call struct {
	*mock.Call
}

// DeleteObservabilityAlertsNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - channelName string
func (_e *MockClient_Expecter) DeleteObservabilityAlertsNotificationChannel(ctx interface{}, namespaceName interface{}, channelName interface{}) *MockClient_DeleteObservabilityAlertsNotificationChannel_Call {
	return &MockClient_DeleteObservabilityAlertsNotificationChannel_Call{Call: _e.mock.On("DeleteObservabilityAlertsNotificationChannel", ctx, namespaceName, channelName)}
}

func (_c *MockClient_DeleteObservabilityAlertsNotificationChannel_Call) Run(run func(ctx context.Context, namespaceName string, channelName string)) *MockClient_DeleteObservabilityAlertsNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_DeleteObservabilityAlertsNotificationChannel_Call) Return(_a0 error) *MockClient_DeleteObservabilityAlertsNotificationChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeleteObservabilityAlertsNotificationChannel_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_DeleteObservabilityAlertsNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetObservabilityAlertsNotificationChannel provides a mock function with given fields: ctx, namespaceName, channelName
func (_m *MockClient) GetObservabilityAlertsNotificationChannel(ctx context.Context, namespaceName string, channelName string) (*gen.ObservabilityAlertsNotificationChannel, error) {
	ret := _m.Called(ctx, namespaceName, channelName)

	if len(ret) == 0 {
		panic("no return value specified for GetObservabilityAlertsNotificationChannel")
	}

	var r0 *gen.ObservabilityAlertsNotificationChannel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.ObservabilityAlertsNotificationChannel, error)); ok {
		return rf(ctx, namespaceName, channelName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.ObservabilityAlertsNotificationChannel); ok {
		r0 = rf(ctx, namespaceName, channelName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ObservabilityAlertsNotificationChannel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, channelName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetObservabilityAlertsNotificationChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObservabilityAlertsNotificationChannel'
type MockClient_GetObservabilityAlertsNotificationChannel_Call struct {
	*mock.Call
}

// GetObservabilityAlertsNotificationChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - channelName string
func (_e *MockClient_Expecter) GetObservabilityAlertsNotificationChannel(ctx interface{}, namespaceName interface{}, channelName interface{}) *MockClient_GetObservabilityAlertsNotificationChannel_Call {
	return &MockClient_GetObservabilityAlertsNotificationChannel_Call{Call: _e.mock.On("GetObservabilityAlertsNotificationChannel", ctx, namespaceName, channelName)}
}

func (_c *MockClient_GetObservabilityAlertsNotificationChannel_Call) Run(run func(ctx context.Context, namespaceName string, channelName string)) *MockClient_GetObservabilityAlertsNotificationChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetObservabilityAlertsNotificationChannel_Call) Return(_a0 *gen.ObservabilityAlertsNotificationChannel, _a1 error) *MockClient_GetObservabilityAlertsNotificationChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetObservabilityAlertsNotificationChannel_Call) RunAndReturn(run func(context.Context, string, string) (*gen.ObservabilityAlertsNotificationChannel, error)) *MockClient_GetObservabilityAlertsNotificationChannel_Call {
	_c.Call.Return(run)
	return _c
}

// ListObservabilityAlertsNotificationChannels provides a mock function with given fields: ctx, namespaceName, params
func (_m *MockClient) ListObservabilityAlertsNotificationChannels(ctx context.Context, namespaceName string, params *gen.ListObservabilityAlertsNotificationChannelsParams) (*gen.ObservabilityAlertsNotificationChannelList, error) {
	ret := _m.Called(ctx, namespaceName, params)

	if len(ret) == 0 {
		panic("no return value specified for ListObservabilityAlertsNotificationChannels")
	}

	var r0 *gen.ObservabilityAlertsNotificationChannelList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListObservabilityAlertsNotificationChannelsParams) (*gen.ObservabilityAlertsNotificationChannelList, error)); ok {
		return rf(ctx, namespaceName, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListObservabilityAlertsNotificationChannelsParams) *gen.ObservabilityAlertsNotificationChannelList); ok {
		r0 = rf(ctx, namespaceName, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ObservabilityAlertsNotificationChannelList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *gen.ListObservabilityAlertsNotificationChannelsParams) error); ok {
		r1 = rf(ctx, namespaceName, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListObservabilityAlertsNotificationChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObservabilityAlertsNotificationChannels'
type MockClient_ListObservabilityAlertsNotificationChannels_Call struct {
	*mock.Call
}

// ListObservabilityAlertsNotificationChannels is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - params *gen.ListObservabilityAlertsNotificationChannelsParams
func (_e *MockClient_Expecter) ListObservabilityAlertsNotificationChannels(ctx interface{}, namespaceName interface{}, params interface{}) *MockClient_ListObservabilityAlertsNotificationChannels_Call {
	return &MockClient_ListObservabilityAlertsNotificationChannels_Call{Call: _e.mock.On("ListObservabilityAlertsNotificationChannels", ctx, namespaceName, params)}
}

func (_c *MockClient_ListObservabilityAlertsNotificationChannels_Call) Run(run func(ctx context.Context, namespaceName string, params *gen.ListObservabilityAlertsNotificationChannelsParams)) *MockClient_ListObservabilityAlertsNotificationChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*gen.ListObservabilityAlertsNotificationChannelsParams))
	})
	return _c
}

func (_c *MockClient_ListObservabilityAlertsNotificationChannels_Call) Return(_a0 *gen.ObservabilityAlertsNotificationChannelList, _a1 error) *MockClient_ListObservabilityAlertsNotificationChannels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListObservabilityAlertsNotificationChannels_Call) RunAndReturn(run func(context.Context, string, *gen.ListObservabilityAlertsNotificationChannelsParams) (*gen.ObservabilityAlertsNotificationChannelList, error)) *MockClient_ListObservabilityAlertsNotificationChannels_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
