// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateReleaseBinding provides a mock function with given fields: ctx, namespaceName, rb
func (_m *MockService) CreateReleaseBinding(ctx context.Context, namespaceName string, rb *v1alpha1.ReleaseBinding) (*v1alpha1.ReleaseBinding, error) {
	ret := _m.Called(ctx, namespaceName, rb)

	if len(ret) == 0 {
		panic("no return value specified for CreateReleaseBinding")
	}

	var r0 *v1alpha1.ReleaseBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ReleaseBinding) (*v1alpha1.ReleaseBinding, error)); ok {
		return rf(ctx, namespaceName, rb)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ReleaseBinding) *v1alpha1.ReleaseBinding); ok {
		r0 = rf(ctx, namespaceName, rb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ReleaseBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ReleaseBinding) error); ok {
		r1 = rf(ctx, namespaceName, rb)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateReleaseBinding'
type MockService_CreateReleaseBinding_Call struct {
	*mock.Call
}

// CreateReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - rb *v1alpha1.ReleaseBinding
func (_e *MockService_Expecter) CreateReleaseBinding(ctx interface{}, namespaceName interface{}, rb interface{}) *MockService_CreateReleaseBinding_Call {
	return &MockService_CreateReleaseBinding_Call{Call: _e.mock.On("CreateReleaseBinding", ctx, namespaceName, rb)}
}

func (_c *MockService_CreateReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, rb *v1alpha1.ReleaseBinding)) *MockService_CreateReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ReleaseBinding))
	})
	return _c
}

func (_c *MockService_CreateReleaseBinding_Call) Return(_a0 *v1alpha1.ReleaseBinding, _a1 error) *MockService_CreateReleaseBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateReleaseBinding_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ReleaseBinding) (*v1alpha1.ReleaseBinding, error)) *MockService_CreateReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteReleaseBinding provides a mock function with given fields: ctx, namespaceName, releaseBindingName
func (_m *MockService) DeleteReleaseBinding(ctx context.Context, namespaceName string, releaseBindingName string) error {
	ret := _m.Called(ctx, namespaceName, releaseBindingName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteReleaseBinding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, releaseBindingName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteReleaseBinding'
type MockService_DeleteReleaseBinding_Call struct {
	*mock.Call
}

// DeleteReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - releaseBindingName string
func (_e *MockService_Expecter) DeleteReleaseBinding(ctx interface{}, namespaceName interface{}, releaseBindingName interface{}) *MockService_DeleteReleaseBinding_Call {
	return &MockService_DeleteReleaseBinding_Call{Call: _e.mock.On("DeleteReleaseBinding", ctx, namespaceName, releaseBindingName)}
}

func (_c *MockService_DeleteReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, releaseBindingName string)) *MockService_DeleteReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteReleaseBinding_Call) Return(_a0 error) *MockService_DeleteReleaseBinding_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteReleaseBinding_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// GetReleaseBinding provides a mock function with given fields: ctx, namespaceName, releaseBindingName
func (_m *MockService) GetReleaseBinding(ctx context.Context, namespaceName string, releaseBindingName string) (*v1alpha1.ReleaseBinding, error) {
	ret := _m.Called(ctx, namespaceName, releaseBindingName)

	if len(ret) == 0 {
		panic("no return value specified for GetReleaseBinding")
	}

	var r0 *v1alpha1.ReleaseBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.ReleaseBinding, error)); ok {
		return rf(ctx, namespaceName, releaseBindingName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.ReleaseBinding); ok {
		r0 = rf(ctx, namespaceName, releaseBindingName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ReleaseBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, releaseBindingName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReleaseBinding'
type MockService_GetReleaseBinding_Call struct {
	*mock.Call
}

// GetReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - releaseBindingName string
func (_e *MockService_Expecter) GetReleaseBinding(ctx interface{}, namespaceName interface{}, releaseBindingName interface{}) *MockService_GetReleaseBinding_Call {
	return &MockService_GetReleaseBinding_Call{Call: _e.mock.On("GetReleaseBinding", ctx, namespaceName, releaseBindingName)}
}

func (_c *MockService_GetReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, releaseBindingName string)) *MockService_GetReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetReleaseBinding_Call) Return(_a0 *v1alpha1.ReleaseBinding, _a1 error) *MockService_GetReleaseBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetReleaseBinding_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.ReleaseBinding, error)) *MockService_GetReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// ListReleaseBindings provides a mock function with given fields: ctx, namespaceName, componentName, opts
func (_m *MockService) ListReleaseBindings(ctx context.Context, namespaceName string, componentName string, opts services.ListOptions) (*services.ListResult[v1alpha1.ReleaseBinding], error) {
	ret := _m.Called(ctx, namespaceName, componentName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListReleaseBindings")
	}

	var r0 *services.ListResult[v1alpha1.ReleaseBinding]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.ReleaseBinding], error)); ok {
		return rf(ctx, namespaceName, componentName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, services.ListOptions) *services.ListResult[v1alpha1.ReleaseBinding]); ok {
		r0 = rf(ctx, namespaceName, componentName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.ReleaseBinding])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, componentName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListReleaseBindings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReleaseBindings'
type MockService_ListReleaseBindings_Call struct {
	*mock.Call
}

// ListReleaseBindings is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - componentName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListReleaseBindings(ctx interface{}, namespaceName interface{}, componentName interface{}, opts interface{}) *MockService_ListReleaseBindings_Call {
	return &MockService_ListReleaseBindings_Call{Call: _e.mock.On("ListReleaseBindings", ctx, namespaceName, componentName, opts)}
}

func (_c *MockService_ListReleaseBindings_Call) Run(run func(ctx context.Context, namespaceName string, componentName string, opts services.ListOptions)) *MockService_ListReleaseBindings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListReleaseBindings_Call) Return(_a0 *services.ListResult[v1alpha1.ReleaseBinding], _a1 error) *MockService_ListReleaseBindings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListReleaseBindings_Call) RunAndReturn(run func(context.Context, string, string, services.ListOptions) (*services.ListResult[v1alpha1.ReleaseBinding], error)) *MockService_ListReleaseBindings_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateReleaseBinding provides a mock function with given fields: ctx, namespaceName, rb
func (_m *MockService) UpdateReleaseBinding(ctx context.Context, namespaceName string, rb *v1alpha1.ReleaseBinding) (*v1alpha1.ReleaseBinding, error) {
	ret := _m.Called(ctx, namespaceName, rb)

	if len(ret) == 0 {
		panic("no return value specified for UpdateReleaseBinding")
	}

	var r0 *v1alpha1.ReleaseBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ReleaseBinding) (*v1alpha1.ReleaseBinding, error)); ok {
		return rf(ctx, namespaceName, rb)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.ReleaseBinding) *v1alpha1.ReleaseBinding); ok {
		r0 = rf(ctx, namespaceName, rb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.ReleaseBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.ReleaseBinding) error); ok {
		r1 = rf(ctx, namespaceName, rb)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateReleaseBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateReleaseBinding'
type MockService_UpdateReleaseBinding_Call struct {
	*mock.Call
}

// UpdateReleaseBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - rb *v1alpha1.ReleaseBinding
func (_e *MockService_Expecter) UpdateReleaseBinding(ctx interface{}, namespaceName interface{}, rb interface{}) *MockService_UpdateReleaseBinding_Call {
	return &MockService_UpdateReleaseBinding_Call{Call: _e.mock.On("UpdateReleaseBinding", ctx, namespaceName, rb)}
}

func (_c *MockService_UpdateReleaseBinding_Call) Run(run func(ctx context.Context, namespaceName string, rb *v1alpha1.ReleaseBinding)) *MockService_UpdateReleaseBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.ReleaseBinding))
	})
	return _c
}

func (_c *MockService_UpdateReleaseBinding_Call) Return(_a0 *v1alpha1.ReleaseBinding, _a1 error) *MockService_UpdateReleaseBinding_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateReleaseBinding_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.ReleaseBinding) (*v1alpha1.ReleaseBinding, error)) *MockService_UpdateReleaseBinding_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
