// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	services "github.com/openchoreo/openchoreo/internal/openchoreo-api/services"

	v1alpha1 "github.com/openchoreo/openchoreo/api/v1alpha1"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// CreateDeploymentPipeline provides a mock function with given fields: ctx, namespaceName, dp
func (_m *MockService) CreateDeploymentPipeline(ctx context.Context, namespaceName string, dp *v1alpha1.DeploymentPipeline) (*v1alpha1.DeploymentPipeline, error) {
	ret := _m.Called(ctx, namespaceName, dp)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeploymentPipeline")
	}

	var r0 *v1alpha1.DeploymentPipeline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.DeploymentPipeline) (*v1alpha1.DeploymentPipeline, error)); ok {
		return rf(ctx, namespaceName, dp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.DeploymentPipeline) *v1alpha1.DeploymentPipeline); ok {
		r0 = rf(ctx, namespaceName, dp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.DeploymentPipeline)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.DeploymentPipeline) error); ok {
		r1 = rf(ctx, namespaceName, dp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_CreateDeploymentPipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDeploymentPipeline'
type MockService_CreateDeploymentPipeline_Call struct {
	*mock.Call
}

// CreateDeploymentPipeline is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - dp *v1alpha1.DeploymentPipeline
func (_e *MockService_Expecter) CreateDeploymentPipeline(ctx interface{}, namespaceName interface{}, dp interface{}) *MockService_CreateDeploymentPipeline_Call {
	return &MockService_CreateDeploymentPipeline_Call{Call: _e.mock.On("CreateDeploymentPipeline", ctx, namespaceName, dp)}
}

func (_c *MockService_CreateDeploymentPipeline_Call) Run(run func(ctx context.Context, namespaceName string, dp *v1alpha1.DeploymentPipeline)) *MockService_CreateDeploymentPipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.DeploymentPipeline))
	})
	return _c
}

func (_c *MockService_CreateDeploymentPipeline_Call) Return(_a0 *v1alpha1.DeploymentPipeline, _a1 error) *MockService_CreateDeploymentPipeline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_CreateDeploymentPipeline_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.DeploymentPipeline) (*v1alpha1.DeploymentPipeline, error)) *MockService_CreateDeploymentPipeline_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDeploymentPipeline provides a mock function with given fields: ctx, namespaceName, deploymentPipelineName
func (_m *MockService) DeleteDeploymentPipeline(ctx context.Context, namespaceName string, deploymentPipelineName string) error {
	ret := _m.Called(ctx, namespaceName, deploymentPipelineName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDeploymentPipeline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, deploymentPipelineName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockService_DeleteDeploymentPipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDeploymentPipeline'
type MockService_DeleteDeploymentPipeline_Call struct {
	*mock.Call
}

// DeleteDeploymentPipeline is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - deploymentPipelineName string
func (_e *MockService_Expecter) DeleteDeploymentPipeline(ctx interface{}, namespaceName interface{}, deploymentPipelineName interface{}) *MockService_DeleteDeploymentPipeline_Call {
	return &MockService_DeleteDeploymentPipeline_Call{Call: _e.mock.On("DeleteDeploymentPipeline", ctx, namespaceName, deploymentPipelineName)}
}

func (_c *MockService_DeleteDeploymentPipeline_Call) Run(run func(ctx context.Context, namespaceName string, deploymentPipelineName string)) *MockService_DeleteDeploymentPipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_DeleteDeploymentPipeline_Call) Return(_a0 error) *MockService_DeleteDeploymentPipeline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockService_DeleteDeploymentPipeline_Call) RunAndReturn(run func(context.Context, string, string) error) *MockService_DeleteDeploymentPipeline_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeploymentPipeline provides a mock function with given fields: ctx, namespaceName, deploymentPipelineName
func (_m *MockService) GetDeploymentPipeline(ctx context.Context, namespaceName string, deploymentPipelineName string) (*v1alpha1.DeploymentPipeline, error) {
	ret := _m.Called(ctx, namespaceName, deploymentPipelineName)

	if len(ret) == 0 {
		panic("no return value specified for GetDeploymentPipeline")
	}

	var r0 *v1alpha1.DeploymentPipeline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*v1alpha1.DeploymentPipeline, error)); ok {
		return rf(ctx, namespaceName, deploymentPipelineName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *v1alpha1.DeploymentPipeline); ok {
		r0 = rf(ctx, namespaceName, deploymentPipelineName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.DeploymentPipeline)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, deploymentPipelineName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_GetDeploymentPipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeploymentPipeline'
type MockService_GetDeploymentPipeline_Call struct {
	*mock.Call
}

// GetDeploymentPipeline is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - deploymentPipelineName string
func (_e *MockService_Expecter) GetDeploymentPipeline(ctx interface{}, namespaceName interface{}, deploymentPipelineName interface{}) *MockService_GetDeploymentPipeline_Call {
	return &MockService_GetDeploymentPipeline_Call{Call: _e.mock.On("GetDeploymentPipeline", ctx, namespaceName, deploymentPipelineName)}
}

func (_c *MockService_GetDeploymentPipeline_Call) Run(run func(ctx context.Context, namespaceName string, deploymentPipelineName string)) *MockService_GetDeploymentPipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockService_GetDeploymentPipeline_Call) Return(_a0 *v1alpha1.DeploymentPipeline, _a1 error) *MockService_GetDeploymentPipeline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_GetDeploymentPipeline_Call) RunAndReturn(run func(context.Context, string, string) (*v1alpha1.DeploymentPipeline, error)) *MockService_GetDeploymentPipeline_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeploymentPipelines provides a mock function with given fields: ctx, namespaceName, opts
func (_m *MockService) ListDeploymentPipelines(ctx context.Context, namespaceName string, opts services.ListOptions) (*services.ListResult[v1alpha1.DeploymentPipeline], error) {
	ret := _m.Called(ctx, namespaceName, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListDeploymentPipelines")
	}

	var r0 *services.ListResult[v1alpha1.DeploymentPipeline]
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.DeploymentPipeline], error)); ok {
		return rf(ctx, namespaceName, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, services.ListOptions) *services.ListResult[v1alpha1.DeploymentPipeline]); ok {
		r0 = rf(ctx, namespaceName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.ListResult[v1alpha1.DeploymentPipeline])
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, services.ListOptions) error); ok {
		r1 = rf(ctx, namespaceName, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_ListDeploymentPipelines_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeploymentPipelines'
type MockService_ListDeploymentPipelines_Call struct {
	*mock.Call
}

// ListDeploymentPipelines is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - opts services.ListOptions
func (_e *MockService_Expecter) ListDeploymentPipelines(ctx interface{}, namespaceName interface{}, opts interface{}) *MockService_ListDeploymentPipelines_Call {
	return &MockService_ListDeploymentPipelines_Call{Call: _e.mock.On("ListDeploymentPipelines", ctx, namespaceName, opts)}
}

func (_c *MockService_ListDeploymentPipelines_Call) Run(run func(ctx context.Context, namespaceName string, opts services.ListOptions)) *MockService_ListDeploymentPipelines_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(services.ListOptions))
	})
	return _c
}

func (_c *MockService_ListDeploymentPipelines_Call) Return(_a0 *services.ListResult[v1alpha1.DeploymentPipeline], _a1 error) *MockService_ListDeploymentPipelines_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_ListDeploymentPipelines_Call) RunAndReturn(run func(context.Context, string, services.ListOptions) (*services.ListResult[v1alpha1.DeploymentPipeline], error)) *MockService_ListDeploymentPipelines_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDeploymentPipeline provides a mock function with given fields: ctx, namespaceName, dp
func (_m *MockService) UpdateDeploymentPipeline(ctx context.Context, namespaceName string, dp *v1alpha1.DeploymentPipeline) (*v1alpha1.DeploymentPipeline, error) {
	ret := _m.Called(ctx, namespaceName, dp)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDeploymentPipeline")
	}

	var r0 *v1alpha1.DeploymentPipeline
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.DeploymentPipeline) (*v1alpha1.DeploymentPipeline, error)); ok {
		return rf(ctx, namespaceName, dp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *v1alpha1.DeploymentPipeline) *v1alpha1.DeploymentPipeline); ok {
		r0 = rf(ctx, namespaceName, dp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1alpha1.DeploymentPipeline)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *v1alpha1.DeploymentPipeline) error); ok {
		r1 = rf(ctx, namespaceName, dp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockService_UpdateDeploymentPipeline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDeploymentPipeline'
type MockService_UpdateDeploymentPipeline_Call struct {
	*mock.Call
}

// UpdateDeploymentPipeline is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - dp *v1alpha1.DeploymentPipeline
func (_e *MockService_Expecter) UpdateDeploymentPipeline(ctx interface{}, namespaceName interface{}, dp interface{}) *MockService_UpdateDeploymentPipeline_Call {
	return &MockService_UpdateDeploymentPipeline_Call{Call: _e.mock.On("UpdateDeploymentPipeline", ctx, namespaceName, dp)}
}

func (_c *MockService_UpdateDeploymentPipeline_Call) Run(run func(ctx context.Context, namespaceName string, dp *v1alpha1.DeploymentPipeline)) *MockService_UpdateDeploymentPipeline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*v1alpha1.DeploymentPipeline))
	})
	return _c
}

func (_c *MockService_UpdateDeploymentPipeline_Call) Return(_a0 *v1alpha1.DeploymentPipeline, _a1 error) *MockService_UpdateDeploymentPipeline_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockService_UpdateDeploymentPipeline_Call) RunAndReturn(run func(context.Context, string, *v1alpha1.DeploymentPipeline) (*v1alpha1.DeploymentPipeline, error)) *MockService_UpdateDeploymentPipeline_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
