// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/openchoreo/openchoreo/internal/openchoreo-api/api/gen"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteProject provides a mock function with given fields: ctx, namespaceName, projectName
func (_m *MockClient) DeleteProject(ctx context.Context, namespaceName string, projectName string) error {
	ret := _m.Called(ctx, namespaceName, projectName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProject")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, namespaceName, projectName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeleteProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteProject'
type MockClient_DeleteProject_Call struct {
	*mock.Call
}

// DeleteProject is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectName string
func (_e *MockClient_Expecter) DeleteProject(ctx interface{}, namespaceName interface{}, projectName interface{}) *MockClient_DeleteProject_Call {
	return &MockClient_DeleteProject_Call{Call: _e.mock.On("DeleteProject", ctx, namespaceName, projectName)}
}

func (_c *MockClient_DeleteProject_Call) Run(run func(ctx context.Context, namespaceName string, projectName string)) *MockClient_DeleteProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_DeleteProject_Call) Return(_a0 error) *MockClient_DeleteProject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeleteProject_Call) RunAndReturn(run func(context.Context, string, string) error) *MockClient_DeleteProject_Call {
	_c.Call.Return(run)
	return _c
}

// GetProject provides a mock function with given fields: ctx, namespaceName, projectName
func (_m *MockClient) GetProject(ctx context.Context, namespaceName string, projectName string) (*gen.Project, error) {
	ret := _m.Called(ctx, namespaceName, projectName)

	if len(ret) == 0 {
		panic("no return value specified for GetProject")
	}

	var r0 *gen.Project
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*gen.Project, error)); ok {
		return rf(ctx, namespaceName, projectName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *gen.Project); ok {
		r0 = rf(ctx, namespaceName, projectName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Project)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, namespaceName, projectName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProject'
type MockClient_GetProject_Call struct {
	*mock.Call
}

// GetProject is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - projectName string
func (_e *MockClient_Expecter) GetProject(ctx interface{}, namespaceName interface{}, projectName interface{}) *MockClient_GetProject_Call {
	return &MockClient_GetProject_Call{Call: _e.mock.On("GetProject", ctx, namespaceName, projectName)}
}

func (_c *MockClient_GetProject_Call) Run(run func(ctx context.Context, namespaceName string, projectName string)) *MockClient_GetProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockClient_GetProject_Call) Return(_a0 *gen.Project, _a1 error) *MockClient_GetProject_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetProject_Call) RunAndReturn(run func(context.Context, string, string) (*gen.Project, error)) *MockClient_GetProject_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjects provides a mock function with given fields: ctx, namespaceName, params
func (_m *MockClient) ListProjects(ctx context.Context, namespaceName string, params *gen.ListProjectsParams) (*gen.ProjectList, error) {
	ret := _m.Called(ctx, namespaceName, params)

	if len(ret) == 0 {
		panic("no return value specified for ListProjects")
	}

	var r0 *gen.ProjectList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListProjectsParams) (*gen.ProjectList, error)); ok {
		return rf(ctx, namespaceName, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *gen.ListProjectsParams) *gen.ProjectList); ok {
		r0 = rf(ctx, namespaceName, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ProjectList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *gen.ListProjectsParams) error); ok {
		r1 = rf(ctx, namespaceName, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListProjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjects'
type MockClient_ListProjects_Call struct {
	*mock.Call
}

// ListProjects is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
//   - params *gen.ListProjectsParams
func (_e *MockClient_Expecter) ListProjects(ctx interface{}, namespaceName interface{}, params interface{}) *MockClient_ListProjects_Call {
	return &MockClient_ListProjects_Call{Call: _e.mock.On("ListProjects", ctx, namespaceName, params)}
}

func (_c *MockClient_ListProjects_Call) Run(run func(ctx context.Context, namespaceName string, params *gen.ListProjectsParams)) *MockClient_ListProjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*gen.ListProjectsParams))
	})
	return _c
}

func (_c *MockClient_ListProjects_Call) Return(_a0 *gen.ProjectList, _a1 error) *MockClient_ListProjects_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListProjects_Call) RunAndReturn(run func(context.Context, string, *gen.ListProjectsParams) (*gen.ProjectList, error)) *MockClient_ListProjects_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
