// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/openchoreo/openchoreo/internal/openchoreo-api/api/gen"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteNamespace provides a mock function with given fields: ctx, namespaceName
func (_m *MockClient) DeleteNamespace(ctx context.Context, namespaceName string) error {
	ret := _m.Called(ctx, namespaceName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteNamespace")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, namespaceName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeleteNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNamespace'
type MockClient_DeleteNamespace_Call struct {
	*mock.Call
}

// DeleteNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
func (_e *MockClient_Expecter) DeleteNamespace(ctx interface{}, namespaceName interface{}) *MockClient_DeleteNamespace_Call {
	return &MockClient_DeleteNamespace_Call{Call: _e.mock.On("DeleteNamespace", ctx, namespaceName)}
}

func (_c *MockClient_DeleteNamespace_Call) Run(run func(ctx context.Context, namespaceName string)) *MockClient_DeleteNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_DeleteNamespace_Call) Return(_a0 error) *MockClient_DeleteNamespace_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeleteNamespace_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_DeleteNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// GetNamespace provides a mock function with given fields: ctx, namespaceName
func (_m *MockClient) GetNamespace(ctx context.Context, namespaceName string) (*gen.Namespace, error) {
	ret := _m.Called(ctx, namespaceName)

	if len(ret) == 0 {
		panic("no return value specified for GetNamespace")
	}

	var r0 *gen.Namespace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gen.Namespace, error)); ok {
		return rf(ctx, namespaceName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gen.Namespace); ok {
		r0 = rf(ctx, namespaceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.Namespace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, namespaceName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetNamespace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNamespace'
type MockClient_GetNamespace_Call struct {
	*mock.Call
}

// GetNamespace is a helper method to define mock.On call
//   - ctx context.Context
//   - namespaceName string
func (_e *MockClient_Expecter) GetNamespace(ctx interface{}, namespaceName interface{}) *MockClient_GetNamespace_Call {
	return &MockClient_GetNamespace_Call{Call: _e.mock.On("GetNamespace", ctx, namespaceName)}
}

func (_c *MockClient_GetNamespace_Call) Run(run func(ctx context.Context, namespaceName string)) *MockClient_GetNamespace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetNamespace_Call) Return(_a0 *gen.Namespace, _a1 error) *MockClient_GetNamespace_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetNamespace_Call) RunAndReturn(run func(context.Context, string) (*gen.Namespace, error)) *MockClient_GetNamespace_Call {
	_c.Call.Return(run)
	return _c
}

// ListNamespaces provides a mock function with given fields: ctx, params
func (_m *MockClient) ListNamespaces(ctx context.Context, params *gen.ListNamespacesParams) (*gen.NamespaceList, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListNamespaces")
	}

	var r0 *gen.NamespaceList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ListNamespacesParams) (*gen.NamespaceList, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ListNamespacesParams) *gen.NamespaceList); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.NamespaceList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.ListNamespacesParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListNamespaces_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNamespaces'
type MockClient_ListNamespaces_Call struct {
	*mock.Call
}

// ListNamespaces is a helper method to define mock.On call
//   - ctx context.Context
//   - params *gen.ListNamespacesParams
func (_e *MockClient_Expecter) ListNamespaces(ctx interface{}, params interface{}) *MockClient_ListNamespaces_Call {
	return &MockClient_ListNamespaces_Call{Call: _e.mock.On("ListNamespaces", ctx, params)}
}

func (_c *MockClient_ListNamespaces_Call) Run(run func(ctx context.Context, params *gen.ListNamespacesParams)) *MockClient_ListNamespaces_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gen.ListNamespacesParams))
	})
	return _c
}

func (_c *MockClient_ListNamespaces_Call) Return(_a0 *gen.NamespaceList, _a1 error) *MockClient_ListNamespaces_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListNamespaces_Call) RunAndReturn(run func(context.Context, *gen.ListNamespacesParams) (*gen.NamespaceList, error)) *MockClient_ListNamespaces_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
