// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	core "github.com/openchoreo/openchoreo/internal/authz/core"
	mock "github.com/stretchr/testify/mock"
)

// MockPDP is an autogenerated mock type for the PDP type
type MockPDP struct {
	mock.Mock
}

type MockPDP_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPDP) EXPECT() *MockPDP_Expecter {
	return &MockPDP_Expecter{mock: &_m.Mock}
}

// BatchEvaluate provides a mock function with given fields: ctx, request
func (_m *MockPDP) BatchEvaluate(ctx context.Context, request *core.BatchEvaluateRequest) (*core.BatchEvaluateResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for BatchEvaluate")
	}

	var r0 *core.BatchEvaluateResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.BatchEvaluateRequest) (*core.BatchEvaluateResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *core.BatchEvaluateRequest) *core.BatchEvaluateResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.BatchEvaluateResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *core.BatchEvaluateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPDP_BatchEvaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchEvaluate'
type MockPDP_BatchEvaluate_Call struct {
	*mock.Call
}

// BatchEvaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.BatchEvaluateRequest
func (_e *MockPDP_Expecter) BatchEvaluate(ctx interface{}, request interface{}) *MockPDP_BatchEvaluate_Call {
	return &MockPDP_BatchEvaluate_Call{Call: _e.mock.On("BatchEvaluate", ctx, request)}
}

func (_c *MockPDP_BatchEvaluate_Call) Run(run func(ctx context.Context, request *core.BatchEvaluateRequest)) *MockPDP_BatchEvaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*core.BatchEvaluateRequest))
	})
	return _c
}

func (_c *MockPDP_BatchEvaluate_Call) Return(_a0 *core.BatchEvaluateResponse, _a1 error) *MockPDP_BatchEvaluate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPDP_BatchEvaluate_Call) RunAndReturn(run func(context.Context, *core.BatchEvaluateRequest) (*core.BatchEvaluateResponse, error)) *MockPDP_BatchEvaluate_Call {
	_c.Call.Return(run)
	return _c
}

// Evaluate provides a mock function with given fields: ctx, request
func (_m *MockPDP) Evaluate(ctx context.Context, request *core.EvaluateRequest) (*core.Decision, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 *core.Decision
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.EvaluateRequest) (*core.Decision, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *core.EvaluateRequest) *core.Decision); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Decision)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *core.EvaluateRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPDP_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type MockPDP_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.EvaluateRequest
func (_e *MockPDP_Expecter) Evaluate(ctx interface{}, request interface{}) *MockPDP_Evaluate_Call {
	return &MockPDP_Evaluate_Call{Call: _e.mock.On("Evaluate", ctx, request)}
}

func (_c *MockPDP_Evaluate_Call) Run(run func(ctx context.Context, request *core.EvaluateRequest)) *MockPDP_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*core.EvaluateRequest))
	})
	return _c
}

func (_c *MockPDP_Evaluate_Call) Return(_a0 *core.Decision, _a1 error) *MockPDP_Evaluate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPDP_Evaluate_Call) RunAndReturn(run func(context.Context, *core.EvaluateRequest) (*core.Decision, error)) *MockPDP_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}

// GetSubjectProfile provides a mock function with given fields: ctx, request
func (_m *MockPDP) GetSubjectProfile(ctx context.Context, request *core.ProfileRequest) (*core.UserCapabilitiesResponse, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for GetSubjectProfile")
	}

	var r0 *core.UserCapabilitiesResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *core.ProfileRequest) (*core.UserCapabilitiesResponse, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *core.ProfileRequest) *core.UserCapabilitiesResponse); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.UserCapabilitiesResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *core.ProfileRequest) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPDP_GetSubjectProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSubjectProfile'
type MockPDP_GetSubjectProfile_Call struct {
	*mock.Call
}

// GetSubjectProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - request *core.ProfileRequest
func (_e *MockPDP_Expecter) GetSubjectProfile(ctx interface{}, request interface{}) *MockPDP_GetSubjectProfile_Call {
	return &MockPDP_GetSubjectProfile_Call{Call: _e.mock.On("GetSubjectProfile", ctx, request)}
}

func (_c *MockPDP_GetSubjectProfile_Call) Run(run func(ctx context.Context, request *core.ProfileRequest)) *MockPDP_GetSubjectProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*core.ProfileRequest))
	})
	return _c
}

func (_c *MockPDP_GetSubjectProfile_Call) Return(_a0 *core.UserCapabilitiesResponse, _a1 error) *MockPDP_GetSubjectProfile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPDP_GetSubjectProfile_Call) RunAndReturn(run func(context.Context, *core.ProfileRequest) (*core.UserCapabilitiesResponse, error)) *MockPDP_GetSubjectProfile_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPDP creates a new instance of MockPDP. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPDP(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPDP {
	mock := &MockPDP{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
