# Helm values for OpenChoreo Data Plane in k3d multi-cluster setup

clusterAgent:
  serverUrl: "wss://cluster-gateway.openchoreo.localhost:8443/ws"

gateway:
  httpPort: 19080
  httpsPort: 19443
  tls:
    enabled: false

kube-prometheus-stack:
  enabled: true
  prometheus:
    prometheusSpec:
      remoteWrite:
      - url: "http://host.k3d.internal:11084/api/v1/write"
