apiVersion: openchoreo.dev/v1alpha1
kind: Component
metadata:
  name: snip-api-service
  namespace: default
spec:
  owner:
    projectName: url-shortener

  componentType:
    kind: ClusterComponentType
    name: deployment/service

  autoDeploy: true

  workflow:
    kind: ClusterWorkflow
    name: dockerfile-builder
    parameters:
      repository:
        url: "https://github.com/openchoreo/sample-workloads"
        revision:
          branch: "main"
        appPath: "/project-url-shortener/api-service"
      docker:
        context: "/project-url-shortener/api-service"
        filePath: "/project-url-shortener/api-service/Dockerfile"

---
apiVersion: openchoreo.dev/v1alpha1
kind: WorkflowRun
metadata:
  name: snip-api-service-build-01
  labels:
    openchoreo.dev/project: "url-shortener"
    openchoreo.dev/component: "snip-api-service"
spec:
  workflow:
    kind: ClusterWorkflow
    name: dockerfile-builder
    parameters:
      repository:
        url: "https://github.com/openchoreo/sample-workloads"
        revision:
          branch: "main"
        appPath: "/project-url-shortener/api-service"
      docker:
        context: "/project-url-shortener/api-service"
        filePath: "/project-url-shortener/api-service/Dockerfile"
