// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	gen "github.com/openchoreo/openchoreo/internal/openchoreo-api/api/gen"
	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// DeleteClusterComponentType provides a mock function with given fields: ctx, cctName
func (_m *MockClient) DeleteClusterComponentType(ctx context.Context, cctName string) error {
	ret := _m.Called(ctx, cctName)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClusterComponentType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, cctName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockClient_DeleteClusterComponentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClusterComponentType'
type MockClient_DeleteClusterComponentType_Call struct {
	*mock.Call
}

// DeleteClusterComponentType is a helper method to define mock.On call
//   - ctx context.Context
//   - cctName string
func (_e *MockClient_Expecter) DeleteClusterComponentType(ctx interface{}, cctName interface{}) *MockClient_DeleteClusterComponentType_Call {
	return &MockClient_DeleteClusterComponentType_Call{Call: _e.mock.On("DeleteClusterComponentType", ctx, cctName)}
}

func (_c *MockClient_DeleteClusterComponentType_Call) Run(run func(ctx context.Context, cctName string)) *MockClient_DeleteClusterComponentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_DeleteClusterComponentType_Call) Return(_a0 error) *MockClient_DeleteClusterComponentType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockClient_DeleteClusterComponentType_Call) RunAndReturn(run func(context.Context, string) error) *MockClient_DeleteClusterComponentType_Call {
	_c.Call.Return(run)
	return _c
}

// GetClusterComponentType provides a mock function with given fields: ctx, cctName
func (_m *MockClient) GetClusterComponentType(ctx context.Context, cctName string) (*gen.ClusterComponentType, error) {
	ret := _m.Called(ctx, cctName)

	if len(ret) == 0 {
		panic("no return value specified for GetClusterComponentType")
	}

	var r0 *gen.ClusterComponentType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*gen.ClusterComponentType, error)); ok {
		return rf(ctx, cctName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *gen.ClusterComponentType); ok {
		r0 = rf(ctx, cctName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ClusterComponentType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, cctName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_GetClusterComponentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClusterComponentType'
type MockClient_GetClusterComponentType_Call struct {
	*mock.Call
}

// GetClusterComponentType is a helper method to define mock.On call
//   - ctx context.Context
//   - cctName string
func (_e *MockClient_Expecter) GetClusterComponentType(ctx interface{}, cctName interface{}) *MockClient_GetClusterComponentType_Call {
	return &MockClient_GetClusterComponentType_Call{Call: _e.mock.On("GetClusterComponentType", ctx, cctName)}
}

func (_c *MockClient_GetClusterComponentType_Call) Run(run func(ctx context.Context, cctName string)) *MockClient_GetClusterComponentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockClient_GetClusterComponentType_Call) Return(_a0 *gen.ClusterComponentType, _a1 error) *MockClient_GetClusterComponentType_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_GetClusterComponentType_Call) RunAndReturn(run func(context.Context, string) (*gen.ClusterComponentType, error)) *MockClient_GetClusterComponentType_Call {
	_c.Call.Return(run)
	return _c
}

// ListClusterComponentTypes provides a mock function with given fields: ctx, params
func (_m *MockClient) ListClusterComponentTypes(ctx context.Context, params *gen.ListClusterComponentTypesParams) (*gen.ClusterComponentTypeList, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListClusterComponentTypes")
	}

	var r0 *gen.ClusterComponentTypeList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ListClusterComponentTypesParams) (*gen.ClusterComponentTypeList, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *gen.ListClusterComponentTypesParams) *gen.ClusterComponentTypeList); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gen.ClusterComponentTypeList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *gen.ListClusterComponentTypesParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockClient_ListClusterComponentTypes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClusterComponentTypes'
type MockClient_ListClusterComponentTypes_Call struct {
	*mock.Call
}

// ListClusterComponentTypes is a helper method to define mock.On call
//   - ctx context.Context
//   - params *gen.ListClusterComponentTypesParams
func (_e *MockClient_Expecter) ListClusterComponentTypes(ctx interface{}, params interface{}) *MockClient_ListClusterComponentTypes_Call {
	return &MockClient_ListClusterComponentTypes_Call{Call: _e.mock.On("ListClusterComponentTypes", ctx, params)}
}

func (_c *MockClient_ListClusterComponentTypes_Call) Run(run func(ctx context.Context, params *gen.ListClusterComponentTypesParams)) *MockClient_ListClusterComponentTypes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*gen.ListClusterComponentTypesParams))
	})
	return _c
}

func (_c *MockClient_ListClusterComponentTypes_Call) Return(_a0 *gen.ClusterComponentTypeList, _a1 error) *MockClient_ListClusterComponentTypes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockClient_ListClusterComponentTypes_Call) RunAndReturn(run func(context.Context, *gen.ListClusterComponentTypesParams) (*gen.ClusterComponentTypeList, error)) *MockClient_ListClusterComponentTypes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
